"""Bundesliga Players"""

BUNDESLIGA_PLAYERS = [
    # ============ BAYERN MÜNİH ============
    {"name": "Harry Kane", "team_history": [{"team": "Tottenham", "years": "2011-2023", "logo": "⚪"}, {"team": "Bayern Münih", "years": "2023-", "logo": "🔴"}], "nationality": "İngiltere", "position": "Forvet", "age": 31, "current_team": "Bayern Münih", "difficulty": "easy"},
    {"name": "Jamal Musiala", "team_history": [{"team": "Chelsea", "years": "2016-2019", "logo": "🔵"}, {"team": "Bayern Münih", "years": "2019-", "logo": "🔴"}], "nationality": "Almanya", "position": "Orta Saha", "age": 21, "current_team": "Bayern Münih", "difficulty": "easy"},
    {"name": "Leroy Sané", "team_history": [{"team": "Schalke 04", "years": "2014-2016", "logo": "🔵"}, {"team": "Manchester City", "years": "2016-2020", "logo": "🔵"}, {"team": "Bayern Münih", "years": "2020-", "logo": "🔴"}], "nationality": "Almanya", "position": "Kanat", "age": 28, "current_team": "Bayern Münih", "difficulty": "easy"},
    {"name": "Serge Gnabry", "team_history": [{"team": "Arsenal", "years": "2012-2016", "logo": "🔴"}, {"team": "West Brom", "years": "2015-2016 (Kiralık)", "logo": "⚪"}, {"team": "Werder Bremen", "years": "2016-2017", "logo": "🟢"}, {"team": "Hoffenheim", "years": "2017-2018 (Kiralık)", "logo": "🔵"}, {"team": "Bayern Münih", "years": "2018-", "logo": "🔴"}], "nationality": "Almanya", "position": "Kanat", "age": 29, "current_team": "Bayern Münih", "difficulty": "easy"},
    {"name": "Joshua Kimmich", "team_history": [{"team": "RB Leipzig", "years": "2013-2015", "logo": "🔴"}, {"team": "Bayern Münih", "years": "2015-", "logo": "🔴"}], "nationality": "Almanya", "position": "Defansif Orta Saha", "age": 29, "current_team": "Bayern Münih", "difficulty": "easy"},
    {"name": "Thomas Müller", "team_history": [{"team": "Bayern Münih", "years": "2008-", "logo": "🔴"}], "nationality": "Almanya", "position": "İkinci Forvet", "age": 35, "current_team": "Bayern Münih", "difficulty": "easy"},
    {"name": "Manuel Neuer", "team_history": [{"team": "Schalke 04", "years": "2004-2011", "logo": "🔵"}, {"team": "Bayern Münih", "years": "2011-", "logo": "🔴"}], "nationality": "Almanya", "position": "Kaleci", "age": 38, "current_team": "Bayern Münih", "difficulty": "easy"},
    {"name": "Alphonso Davies", "team_history": [{"team": "Vancouver Whitecaps", "years": "2016-2018", "logo": "🔵"}, {"team": "Bayern Münih", "years": "2018-", "logo": "🔴"}], "nationality": "Kanada", "position": "Sol Bek", "age": 23, "current_team": "Bayern Münih", "difficulty": "easy"},
    {"name": "Kim Min-jae", "team_history": [{"team": "Jeonbuk Hyundai", "years": "2017-2019", "logo": "🟢"}, {"team": "Beijing Guoan", "years": "2019-2021", "logo": "🟢"}, {"team": "Fenerbahçe", "years": "2021-2022", "logo": "🟡"}, {"team": "Napoli", "years": "2022-2023", "logo": "🔵"}, {"team": "Bayern Münih", "years": "2023-", "logo": "🔴"}], "nationality": "Güney Kore", "position": "Stoper", "age": 28, "current_team": "Bayern Münih", "difficulty": "easy"},
    {"name": "Dayot Upamecano", "team_history": [{"team": "Valenciennes", "years": "2015-2015", "logo": "🔴"}, {"team": "Red Bull Salzburg", "years": "2015-2017", "logo": "🔴"}, {"team": "RB Leipzig", "years": "2017-2021", "logo": "🔴"}, {"team": "Bayern Münih", "years": "2021-", "logo": "🔴"}], "nationality": "Fransa", "position": "Stoper", "age": 25, "current_team": "Bayern Münih", "difficulty": "medium"},
    {"name": "Leon Goretzka", "team_history": [{"team": "Bochum", "years": "2012-2013", "logo": "🔵"}, {"team": "Schalke 04", "years": "2013-2018", "logo": "🔵"}, {"team": "Bayern Münih", "years": "2018-", "logo": "🔴"}], "nationality": "Almanya", "position": "Orta Saha", "age": 29, "current_team": "Bayern Münih", "difficulty": "easy"},
    {"name": "Konrad Laimer", "team_history": [{"team": "Red Bull Salzburg", "years": "2015-2017", "logo": "🔴"}, {"team": "RB Leipzig", "years": "2017-2023", "logo": "🔴"}, {"team": "Bayern Münih", "years": "2023-", "logo": "🔴"}], "nationality": "Avusturya", "position": "Orta Saha", "age": 27, "current_team": "Bayern Münih", "difficulty": "medium"},
    {"name": "Kingsley Coman", "team_history": [{"team": "PSG", "years": "2013-2014", "logo": "🔵"}, {"team": "Juventus", "years": "2014-2015", "logo": "⚫"}, {"team": "Bayern Münih", "years": "2015-", "logo": "🔴"}], "nationality": "Fransa", "position": "Kanat", "age": 28, "current_team": "Bayern Münih", "difficulty": "easy"},
    {"name": "Eric Dier", "team_history": [{"team": "Sporting CP", "years": "2012-2014", "logo": "🟢"}, {"team": "Tottenham", "years": "2014-2024", "logo": "⚪"}, {"team": "Bayern Münih", "years": "2024-", "logo": "🔴"}], "nationality": "İngiltere", "position": "Stoper", "age": 30, "current_team": "Bayern Münih", "difficulty": "easy"},
    {"name": "Sacha Boey", "team_history": [{"team": "Rennes", "years": "2019-2021", "logo": "🔴"}, {"team": "Galatasaray", "years": "2021-2024", "logo": "🟡"}, {"team": "Bayern Münih", "years": "2024-", "logo": "🔴"}], "nationality": "Fransa", "position": "Sağ Bek", "age": 24, "current_team": "Bayern Münih", "difficulty": "medium"},
    {"name": "Michael Olise", "team_history": [{"team": "Reading", "years": "2019-2021", "logo": "🔵"}, {"team": "Crystal Palace", "years": "2021-2024", "logo": "🔴"}, {"team": "Bayern Münih", "years": "2024-", "logo": "🔴"}], "nationality": "Fransa", "position": "Kanat", "age": 22, "current_team": "Bayern Münih", "difficulty": "easy"},
    {"name": "João Palhinha", "team_history": [{"team": "Sporting CP", "years": "2017-2022", "logo": "🟢"}, {"team": "Braga", "years": "2019-2020 (Kiralık)", "logo": "🔴"}, {"team": "Fulham", "years": "2022-2024", "logo": "⚪"}, {"team": "Bayern Münih", "years": "2024-", "logo": "🔴"}], "nationality": "Portekiz", "position": "Defansif Orta Saha", "age": 29, "current_team": "Bayern Münih", "difficulty": "easy"},
    {"name": "Hiroki Ito", "team_history": [{"team": "Jubilo Iwata", "years": "2017-2021", "logo": "🔵"}, {"team": "Stuttgart", "years": "2021-2024", "logo": "⚪"}, {"team": "Bayern Münih", "years": "2024-", "logo": "🔴"}], "nationality": "Japonya", "position": "Stoper", "age": 25, "current_team": "Bayern Münih", "difficulty": "medium"},
    
    # ============ BAYER LEVERKUSEN ============
    {"name": "Florian Wirtz", "team_history": [{"team": "1. FC Köln", "years": "2016-2020", "logo": "🔴"}, {"team": "Bayer Leverkusen", "years": "2020-", "logo": "🔴"}], "nationality": "Almanya", "position": "Orta Saha", "age": 21, "current_team": "Bayer Leverkusen", "difficulty": "easy"},
    {"name": "Granit Xhaka", "team_history": [{"team": "Basel", "years": "2010-2012", "logo": "🔴"}, {"team": "Borussia M'gladbach", "years": "2012-2016", "logo": "🟢"}, {"team": "Arsenal", "years": "2016-2023", "logo": "🔴"}, {"team": "Bayer Leverkusen", "years": "2023-", "logo": "🔴"}], "nationality": "İsviçre", "position": "Orta Saha", "age": 31, "current_team": "Bayer Leverkusen", "difficulty": "easy"},
    {"name": "Victor Boniface", "team_history": [{"team": "Bodø/Glimt", "years": "2021-2022", "logo": "🟡"}, {"team": "Union St. Gilloise", "years": "2022-2023", "logo": "🔵"}, {"team": "Bayer Leverkusen", "years": "2023-", "logo": "🔴"}], "nationality": "Nijerya", "position": "Forvet", "age": 23, "current_team": "Bayer Leverkusen", "difficulty": "medium"},
    {"name": "Jeremie Frimpong", "team_history": [{"team": "Manchester City", "years": "2019-2020", "logo": "🔵"}, {"team": "Celtic", "years": "2019-2021", "logo": "🟢"}, {"team": "Bayer Leverkusen", "years": "2021-", "logo": "🔴"}], "nationality": "Hollanda", "position": "Sağ Bek", "age": 24, "current_team": "Bayer Leverkusen", "difficulty": "medium"},
    {"name": "Jonathan Tah", "team_history": [{"team": "Hamburg", "years": "2013-2015", "logo": "🔵"}, {"team": "Bayer Leverkusen", "years": "2015-", "logo": "🔴"}], "nationality": "Almanya", "position": "Stoper", "age": 28, "current_team": "Bayer Leverkusen", "difficulty": "medium"},
    {"name": "Exequiel Palacios", "team_history": [{"team": "River Plate", "years": "2015-2020", "logo": "🔴"}, {"team": "Bayer Leverkusen", "years": "2020-", "logo": "🔴"}], "nationality": "Arjantin", "position": "Orta Saha", "age": 26, "current_team": "Bayer Leverkusen", "difficulty": "medium"},
    {"name": "Robert Andrich", "team_history": [{"team": "Dynamo Dresden", "years": "2016-2018", "logo": "🟡"}, {"team": "Heidenheim", "years": "2018-2019", "logo": "🔴"}, {"team": "Union Berlin", "years": "2019-2021", "logo": "🔴"}, {"team": "Bayer Leverkusen", "years": "2021-", "logo": "🔴"}], "nationality": "Almanya", "position": "Orta Saha", "age": 29, "current_team": "Bayer Leverkusen", "difficulty": "medium"},
    {"name": "Alejandro Grimaldo", "team_history": [{"team": "Barcelona", "years": "2013-2016", "logo": "🔵"}, {"team": "Benfica", "years": "2016-2023", "logo": "🔴"}, {"team": "Bayer Leverkusen", "years": "2023-", "logo": "🔴"}], "nationality": "İspanya", "position": "Sol Bek", "age": 28, "current_team": "Bayer Leverkusen", "difficulty": "medium"},
    {"name": "Patrik Schick", "team_history": [{"team": "Sparta Prag", "years": "2015-2017", "logo": "🔴"}, {"team": "Sampdoria", "years": "2017-2018", "logo": "🔵"}, {"team": "Roma", "years": "2018-2020", "logo": "🟡"}, {"team": "RB Leipzig", "years": "2019-2020 (Kiralık)", "logo": "🔴"}, {"team": "Bayer Leverkusen", "years": "2020-", "logo": "🔴"}], "nationality": "Çekya", "position": "Forvet", "age": 28, "current_team": "Bayer Leverkusen", "difficulty": "medium"},
    {"name": "Lukáš Hrádecký", "team_history": [{"team": "Esbjerg", "years": "2012-2015", "logo": "🔵"}, {"team": "Eintracht Frankfurt", "years": "2015-2018", "logo": "⚫"}, {"team": "Bayer Leverkusen", "years": "2018-", "logo": "🔴"}], "nationality": "Finlandiya", "position": "Kaleci", "age": 34, "current_team": "Bayer Leverkusen", "difficulty": "medium"},
    {"name": "Odilon Kossounou", "team_history": [{"team": "Hammarby", "years": "2018-2019", "logo": "🟢"}, {"team": "Club Brugge", "years": "2019-2021", "logo": "🔵"}, {"team": "Bayer Leverkusen", "years": "2021-", "logo": "🔴"}], "nationality": "Fildişi Sahili", "position": "Stoper", "age": 23, "current_team": "Bayer Leverkusen", "difficulty": "medium"},
    {"name": "Nathan Tella", "team_history": [{"team": "Arsenal", "years": "2016-2019", "logo": "🔴"}, {"team": "Southampton", "years": "2019-2023", "logo": "🔴"}, {"team": "Burnley", "years": "2022-2023 (Kiralık)", "logo": "🔴"}, {"team": "Bayer Leverkusen", "years": "2023-", "logo": "🔴"}], "nationality": "İngiltere", "position": "Kanat", "age": 25, "current_team": "Bayer Leverkusen", "difficulty": "medium"},
    {"name": "Jonas Hofmann", "team_history": [{"team": "Borussia Dortmund", "years": "2011-2016", "logo": "🟡"}, {"team": "Mainz 05", "years": "2015-2016 (Kiralık)", "logo": "🔴"}, {"team": "Borussia M'gladbach", "years": "2016-2023", "logo": "🟢"}, {"team": "Bayer Leverkusen", "years": "2023-", "logo": "🔴"}], "nationality": "Almanya", "position": "Kanat", "age": 32, "current_team": "Bayer Leverkusen", "difficulty": "medium"},
    {"name": "Amine Adli", "team_history": [{"team": "Toulouse", "years": "2019-2021", "logo": "🟣"}, {"team": "Bayer Leverkusen", "years": "2021-", "logo": "🔴"}], "nationality": "Fas", "position": "Kanat", "age": 24, "current_team": "Bayer Leverkusen", "difficulty": "medium"},
    
    # ============ BORUSSIA DORTMUND ============
    {"name": "Serhou Guirassy", "team_history": [{"team": "Auxerre", "years": "2013-2016", "logo": "⚪"}, {"team": "Köln", "years": "2016-2017", "logo": "🔴"}, {"team": "Amiens", "years": "2017-2019", "logo": "⚫"}, {"team": "Rennes", "years": "2019-2021", "logo": "🔴"}, {"team": "Stuttgart", "years": "2021-2024", "logo": "⚪"}, {"team": "Borussia Dortmund", "years": "2024-", "logo": "🟡"}], "nationality": "Gine", "position": "Forvet", "age": 28, "current_team": "Borussia Dortmund", "difficulty": "easy"},
    {"name": "Julian Brandt", "team_history": [{"team": "Bayer Leverkusen", "years": "2014-2019", "logo": "🔴"}, {"team": "Borussia Dortmund", "years": "2019-", "logo": "🟡"}], "nationality": "Almanya", "position": "Orta Saha", "age": 28, "current_team": "Borussia Dortmund", "difficulty": "easy"},
    {"name": "Karim Adeyemi", "team_history": [{"team": "Red Bull Salzburg", "years": "2018-2022", "logo": "🔴"}, {"team": "Borussia Dortmund", "years": "2022-", "logo": "🟡"}], "nationality": "Almanya", "position": "Kanat", "age": 22, "current_team": "Borussia Dortmund", "difficulty": "medium"},
    {"name": "Gregor Kobel", "team_history": [{"team": "Hoffenheim", "years": "2017-2019", "logo": "🔵"}, {"team": "Augsburg", "years": "2019-2019 (Kiralık)", "logo": "🔴"}, {"team": "Stuttgart", "years": "2019-2021", "logo": "⚪"}, {"team": "Borussia Dortmund", "years": "2021-", "logo": "🟡"}], "nationality": "İsviçre", "position": "Kaleci", "age": 26, "current_team": "Borussia Dortmund", "difficulty": "medium"},
    {"name": "Nico Schlotterbeck", "team_history": [{"team": "Freiburg", "years": "2019-2022", "logo": "⚫"}, {"team": "Union Berlin", "years": "2020-2021 (Kiralık)", "logo": "🔴"}, {"team": "Borussia Dortmund", "years": "2022-", "logo": "🟡"}], "nationality": "Almanya", "position": "Stoper", "age": 25, "current_team": "Borussia Dortmund", "difficulty": "medium"},
    {"name": "Marcel Sabitzer", "team_history": [{"team": "Admira Wacker", "years": "2010-2013", "logo": "🔴"}, {"team": "Rapid Wien", "years": "2013-2014", "logo": "🟢"}, {"team": "Red Bull Salzburg", "years": "2014-2015", "logo": "🔴"}, {"team": "RB Leipzig", "years": "2015-2021", "logo": "🔴"}, {"team": "Bayern Münih", "years": "2021-2023", "logo": "🔴"}, {"team": "Manchester United", "years": "2023 (Kiralık)", "logo": "🔴"}, {"team": "Borussia Dortmund", "years": "2023-", "logo": "🟡"}], "nationality": "Avusturya", "position": "Orta Saha", "age": 30, "current_team": "Borussia Dortmund", "difficulty": "easy"},
    {"name": "Emre Can", "team_history": [{"team": "Bayern Münih", "years": "2012-2014", "logo": "🔴"}, {"team": "Bayer Leverkusen", "years": "2013-2014 (Kiralık)", "logo": "🔴"}, {"team": "Liverpool", "years": "2014-2018", "logo": "🔴"}, {"team": "Juventus", "years": "2018-2020", "logo": "⚫"}, {"team": "Borussia Dortmund", "years": "2020-", "logo": "🟡"}], "nationality": "Almanya", "position": "Orta Saha", "age": 30, "current_team": "Borussia Dortmund", "difficulty": "easy"},
    {"name": "Jamie Gittens", "team_history": [{"team": "Manchester City", "years": "2020-2020", "logo": "🔵"}, {"team": "Borussia Dortmund", "years": "2020-", "logo": "🟡"}], "nationality": "İngiltere", "position": "Kanat", "age": 20, "current_team": "Borussia Dortmund", "difficulty": "medium"},
    {"name": "Donyell Malen", "team_history": [{"team": "Arsenal", "years": "2015-2017", "logo": "🔴"}, {"team": "PSV", "years": "2017-2021", "logo": "🔴"}, {"team": "Borussia Dortmund", "years": "2021-", "logo": "🟡"}], "nationality": "Hollanda", "position": "Forvet", "age": 25, "current_team": "Borussia Dortmund", "difficulty": "medium"},
    {"name": "Niklas Süle", "team_history": [{"team": "Hoffenheim", "years": "2013-2017", "logo": "🔵"}, {"team": "Bayern Münih", "years": "2017-2022", "logo": "🔴"}, {"team": "Borussia Dortmund", "years": "2022-", "logo": "🟡"}], "nationality": "Almanya", "position": "Stoper", "age": 29, "current_team": "Borussia Dortmund", "difficulty": "medium"},
    {"name": "Ramy Bensebaini", "team_history": [{"team": "Paradou AC", "years": "2014-2016", "logo": "🟡"}, {"team": "Montpellier", "years": "2016-2017", "logo": "🟠"}, {"team": "Rennes", "years": "2017-2019", "logo": "🔴"}, {"team": "Borussia M'gladbach", "years": "2019-2023", "logo": "🟢"}, {"team": "Borussia Dortmund", "years": "2023-", "logo": "🟡"}], "nationality": "Cezayir", "position": "Sol Bek", "age": 29, "current_team": "Borussia Dortmund", "difficulty": "medium"},
    {"name": "Pascal Groß", "team_history": [{"team": "Hoffenheim", "years": "2012-2013", "logo": "🔵"}, {"team": "Karlsruher SC", "years": "2013-2014 (Kiralık)", "logo": "🔵"}, {"team": "Ingolstadt", "years": "2014-2017", "logo": "🔴"}, {"team": "Brighton", "years": "2017-2024", "logo": "🔵"}, {"team": "Borussia Dortmund", "years": "2024-", "logo": "🟡"}], "nationality": "Almanya", "position": "Orta Saha", "age": 33, "current_team": "Borussia Dortmund", "difficulty": "medium"},
    {"name": "Waldemar Anton", "team_history": [{"team": "Hannover 96", "years": "2016-2019", "logo": "🔴"}, {"team": "Stuttgart", "years": "2019-2024", "logo": "⚪"}, {"team": "Borussia Dortmund", "years": "2024-", "logo": "🟡"}], "nationality": "Almanya", "position": "Stoper", "age": 28, "current_team": "Borussia Dortmund", "difficulty": "medium"},
    {"name": "Maximilian Beier", "team_history": [{"team": "Hoffenheim", "years": "2020-2024", "logo": "🔵"}, {"team": "Hannover 96", "years": "2022-2023 (Kiralık)", "logo": "🔴"}, {"team": "Borussia Dortmund", "years": "2024-", "logo": "🟡"}], "nationality": "Almanya", "position": "Forvet", "age": 21, "current_team": "Borussia Dortmund", "difficulty": "medium"},
    
    # ============ RB LEIPZIG ============
    {"name": "Xavi Simons", "team_history": [{"team": "Barcelona", "years": "2016-2019", "logo": "🔵"}, {"team": "PSG", "years": "2019-2022", "logo": "🔵"}, {"team": "PSV", "years": "2022-2023", "logo": "🔴"}, {"team": "RB Leipzig", "years": "2023-", "logo": "🔴"}], "nationality": "Hollanda", "position": "Orta Saha", "age": 21, "current_team": "RB Leipzig", "difficulty": "easy"},
    {"name": "Benjamin Sesko", "team_history": [{"team": "Red Bull Salzburg", "years": "2019-2023", "logo": "🔴"}, {"team": "RB Leipzig", "years": "2023-", "logo": "🔴"}], "nationality": "Slovenya", "position": "Forvet", "age": 21, "current_team": "RB Leipzig", "difficulty": "easy"},
    {"name": "Lois Openda", "team_history": [{"team": "Club Brugge", "years": "2018-2021", "logo": "🔵"}, {"team": "Vitesse", "years": "2020-2021 (Kiralık)", "logo": "🟡"}, {"team": "Lens", "years": "2021-2023", "logo": "🔴"}, {"team": "RB Leipzig", "years": "2023-", "logo": "🔴"}], "nationality": "Belçika", "position": "Forvet", "age": 24, "current_team": "RB Leipzig", "difficulty": "medium"},
    {"name": "David Raum", "team_history": [{"team": "Greuther Fürth", "years": "2018-2021", "logo": "🟢"}, {"team": "Hoffenheim", "years": "2021-2022", "logo": "🔵"}, {"team": "RB Leipzig", "years": "2022-", "logo": "🔴"}], "nationality": "Almanya", "position": "Sol Bek", "age": 26, "current_team": "RB Leipzig", "difficulty": "medium"},
    {"name": "Christoph Baumgartner", "team_history": [{"team": "Hoffenheim", "years": "2019-2023", "logo": "🔵"}, {"team": "RB Leipzig", "years": "2023-", "logo": "🔴"}], "nationality": "Avusturya", "position": "Orta Saha", "age": 25, "current_team": "RB Leipzig", "difficulty": "medium"},
    {"name": "Willi Orbán", "team_history": [{"team": "Kaiserslautern", "years": "2013-2015", "logo": "🔴"}, {"team": "RB Leipzig", "years": "2015-", "logo": "🔴"}], "nationality": "Macaristan", "position": "Stoper", "age": 31, "current_team": "RB Leipzig", "difficulty": "medium"},
    {"name": "Péter Gulácsi", "team_history": [{"team": "Liverpool", "years": "2008-2013", "logo": "🔴"}, {"team": "Hereford United", "years": "2010 (Kiralık)", "logo": "⚫"}, {"team": "Tranmere Rovers", "years": "2011 (Kiralık)", "logo": "⚪"}, {"team": "Red Bull Salzburg", "years": "2013-2015", "logo": "🔴"}, {"team": "RB Leipzig", "years": "2015-", "logo": "🔴"}], "nationality": "Macaristan", "position": "Kaleci", "age": 34, "current_team": "RB Leipzig", "difficulty": "medium"},
    {"name": "Amadou Haidara", "team_history": [{"team": "JMG Academy", "years": "2014-2017", "logo": "🟢"}, {"team": "Red Bull Salzburg", "years": "2017-2019", "logo": "🔴"}, {"team": "RB Leipzig", "years": "2019-", "logo": "🔴"}], "nationality": "Mali", "position": "Orta Saha", "age": 26, "current_team": "RB Leipzig", "difficulty": "medium"},
    {"name": "Lukas Klostermann", "team_history": [{"team": "Bochum", "years": "2014-2014", "logo": "🔵"}, {"team": "RB Leipzig", "years": "2014-", "logo": "🔴"}], "nationality": "Almanya", "position": "Sağ Bek", "age": 28, "current_team": "RB Leipzig", "difficulty": "medium"},
    {"name": "Antonio Nusa", "team_history": [{"team": "Stabæk", "years": "2019-2020", "logo": "🔵"}, {"team": "Club Brugge", "years": "2020-2024", "logo": "🔵"}, {"team": "RB Leipzig", "years": "2024-", "logo": "🔴"}], "nationality": "Norveç", "position": "Kanat", "age": 19, "current_team": "RB Leipzig", "difficulty": "medium"},
    {"name": "Castello Lukeba", "team_history": [{"team": "Lyon", "years": "2020-2023", "logo": "🔵"}, {"team": "RB Leipzig", "years": "2023-", "logo": "🔴"}], "nationality": "Fransa", "position": "Stoper", "age": 21, "current_team": "RB Leipzig", "difficulty": "medium"},
    
    # ============ STUTTGART ============
    {"name": "Deniz Undav", "team_history": [{"team": "Meppen", "years": "2019-2021", "logo": "🔵"}, {"team": "Union St. Gilloise", "years": "2021-2023", "logo": "🔵"}, {"team": "Brighton", "years": "2023-2024", "logo": "🔵"}, {"team": "Stuttgart", "years": "2024-", "logo": "⚪"}], "nationality": "Almanya", "position": "Forvet", "age": 28, "current_team": "Stuttgart", "difficulty": "medium"},
    {"name": "Chris Führich", "team_history": [{"team": "Borussia Dortmund", "years": "2017-2019", "logo": "🟡"}, {"team": "Paderborn", "years": "2019-2021", "logo": "🔵"}, {"team": "Stuttgart", "years": "2021-", "logo": "⚪"}], "nationality": "Almanya", "position": "Kanat", "age": 27, "current_team": "Stuttgart", "difficulty": "medium"},
    {"name": "Angelo Stiller", "team_history": [{"team": "Bayern Münih", "years": "2019-2021", "logo": "🔴"}, {"team": "Hoffenheim", "years": "2021-2023", "logo": "🔵"}, {"team": "Stuttgart", "years": "2023-", "logo": "⚪"}], "nationality": "Almanya", "position": "Orta Saha", "age": 23, "current_team": "Stuttgart", "difficulty": "medium"},
    {"name": "Enzo Millot", "team_history": [{"team": "Monaco", "years": "2020-2022", "logo": "🔴"}, {"team": "Stuttgart", "years": "2022-", "logo": "⚪"}], "nationality": "Fransa", "position": "Orta Saha", "age": 22, "current_team": "Stuttgart", "difficulty": "medium"},
    {"name": "Alexander Nübel", "team_history": [{"team": "Schalke 04", "years": "2015-2020", "logo": "🔵"}, {"team": "Bayern Münih", "years": "2020-", "logo": "🔴"}, {"team": "Monaco", "years": "2021-2023 (Kiralık)", "logo": "🔴"}, {"team": "Stuttgart", "years": "2023- (Kiralık)", "logo": "⚪"}], "nationality": "Almanya", "position": "Kaleci", "age": 27, "current_team": "Stuttgart", "difficulty": "medium"},
    {"name": "Jeff Chabot", "team_history": [{"team": "Köln", "years": "2018-2022", "logo": "🔴"}, {"team": "Sampdoria", "years": "2022-2023", "logo": "🔵"}, {"team": "Stuttgart", "years": "2023-", "logo": "⚪"}], "nationality": "Almanya", "position": "Stoper", "age": 26, "current_team": "Stuttgart", "difficulty": "hard"},
    {"name": "Jamie Leweling", "team_history": [{"team": "Greuther Fürth", "years": "2019-2021", "logo": "🟢"}, {"team": "Union Berlin", "years": "2021-2023", "logo": "🔴"}, {"team": "Stuttgart", "years": "2023-", "logo": "⚪"}], "nationality": "Almanya", "position": "Kanat", "age": 23, "current_team": "Stuttgart", "difficulty": "medium"},
    {"name": "Josha Vagnoman", "team_history": [{"team": "Hamburg", "years": "2018-2022", "logo": "🔵"}, {"team": "Stuttgart", "years": "2022-", "logo": "⚪"}], "nationality": "Almanya", "position": "Sağ Bek", "age": 23, "current_team": "Stuttgart", "difficulty": "medium"},
    {"name": "Ermedin Demirović", "team_history": [{"team": "Alaves", "years": "2018-2019", "logo": "🔵"}, {"team": "Sochaux", "years": "2019-2020", "logo": "🔵"}, {"team": "Freiburg", "years": "2020-2023", "logo": "⚫"}, {"team": "Augsburg", "years": "2023-2024", "logo": "🔴"}, {"team": "Stuttgart", "years": "2024-", "logo": "⚪"}], "nationality": "Bosna Hersek", "position": "Forvet", "age": 26, "current_team": "Stuttgart", "difficulty": "medium"},
    
    # ============ EINTRACHT FRANKFURT ============
    {"name": "Omar Marmoush", "team_history": [{"team": "Wolfsburg", "years": "2017-2022", "logo": "🟢"}, {"team": "St. Pauli", "years": "2021-2022 (Kiralık)", "logo": "🟤"}, {"team": "Stuttgart", "years": "2022-2023 (Kiralık)", "logo": "⚪"}, {"team": "Eintracht Frankfurt", "years": "2023-", "logo": "⚫"}], "nationality": "Mısır", "position": "Forvet", "age": 25, "current_team": "Eintracht Frankfurt", "difficulty": "easy"},
    {"name": "Hugo Ekitiké", "team_history": [{"team": "Reims", "years": "2019-2022", "logo": "🔴"}, {"team": "PSG", "years": "2022-2024", "logo": "🔵"}, {"team": "Eintracht Frankfurt", "years": "2023-", "logo": "⚫"}], "nationality": "Fransa", "position": "Forvet", "age": 22, "current_team": "Eintracht Frankfurt", "difficulty": "medium"},
    {"name": "Mario Götze", "team_history": [{"team": "Borussia Dortmund", "years": "2009-2013", "logo": "🟡"}, {"team": "Bayern Münih", "years": "2013-2016", "logo": "🔴"}, {"team": "Borussia Dortmund", "years": "2016-2020", "logo": "🟡"}, {"team": "PSV", "years": "2020-2022", "logo": "🔴"}, {"team": "Eintracht Frankfurt", "years": "2022-", "logo": "⚫"}], "nationality": "Almanya", "position": "Orta Saha", "age": 32, "current_team": "Eintracht Frankfurt", "difficulty": "easy"},
    {"name": "Kevin Trapp", "team_history": [{"team": "Kaiserslautern", "years": "2010-2012", "logo": "🔴"}, {"team": "Eintracht Frankfurt", "years": "2012-2015", "logo": "⚫"}, {"team": "PSG", "years": "2015-2018", "logo": "🔵"}, {"team": "Eintracht Frankfurt", "years": "2018-", "logo": "⚫"}], "nationality": "Almanya", "position": "Kaleci", "age": 34, "current_team": "Eintracht Frankfurt", "difficulty": "easy"},
    {"name": "Robin Koch", "team_history": [{"team": "Kaiserslautern", "years": "2015-2017", "logo": "🔴"}, {"team": "Freiburg", "years": "2017-2020", "logo": "⚫"}, {"team": "Leeds United", "years": "2020-2023", "logo": "⚪"}, {"team": "Eintracht Frankfurt", "years": "2023-", "logo": "⚫"}], "nationality": "Almanya", "position": "Stoper", "age": 28, "current_team": "Eintracht Frankfurt", "difficulty": "medium"},
    {"name": "Ansgar Knauff", "team_history": [{"team": "Borussia Dortmund", "years": "2020-2023", "logo": "🟡"}, {"team": "Eintracht Frankfurt", "years": "2022-", "logo": "⚫"}], "nationality": "Almanya", "position": "Kanat", "age": 22, "current_team": "Eintracht Frankfurt", "difficulty": "medium"},
    {"name": "Rasmus Kristensen", "team_history": [{"team": "Ajax", "years": "2018-2019", "logo": "⚪"}, {"team": "Red Bull Salzburg", "years": "2019-2022", "logo": "🔴"}, {"team": "Leeds United", "years": "2022-2024", "logo": "⚪"}, {"team": "Roma", "years": "2023-2024 (Kiralık)", "logo": "🟡"}, {"team": "Eintracht Frankfurt", "years": "2024-", "logo": "⚫"}], "nationality": "Danimarka", "position": "Sağ Bek", "age": 27, "current_team": "Eintracht Frankfurt", "difficulty": "medium"},
    
    # ============ OTHER BUNDESLIGA ============
    # Wolfsburg
    {"name": "Jonas Wind", "team_history": [{"team": "Copenhagen", "years": "2017-2022", "logo": "🔵"}, {"team": "Wolfsburg", "years": "2022-", "logo": "🟢"}], "nationality": "Danimarka", "position": "Forvet", "age": 25, "current_team": "Wolfsburg", "difficulty": "medium"},
    {"name": "Patrick Wimmer", "team_history": [{"team": "Austria Wien", "years": "2018-2020", "logo": "🟣"}, {"team": "Arminia Bielefeld", "years": "2020-2022", "logo": "🔵"}, {"team": "Wolfsburg", "years": "2022-", "logo": "🟢"}], "nationality": "Avusturya", "position": "Kanat", "age": 23, "current_team": "Wolfsburg", "difficulty": "medium"},
    {"name": "Kamil Grabara", "team_history": [{"team": "Liverpool", "years": "2016-2021", "logo": "🔴"}, {"team": "Aarhus", "years": "2019-2020 (Kiralık)", "logo": "⚪"}, {"team": "Copenhagen", "years": "2021-2024", "logo": "🔵"}, {"team": "Wolfsburg", "years": "2024-", "logo": "🟢"}], "nationality": "Polonya", "position": "Kaleci", "age": 25, "current_team": "Wolfsburg", "difficulty": "medium"},
    
    # Borussia Mönchengladbach
    {"name": "Alassane Pléa", "team_history": [{"team": "Lyon", "years": "2012-2014", "logo": "🔵"}, {"team": "Nice", "years": "2014-2018", "logo": "🔴"}, {"team": "Borussia M'gladbach", "years": "2018-", "logo": "🟢"}], "nationality": "Fransa", "position": "Forvet", "age": 31, "current_team": "Borussia M'gladbach", "difficulty": "medium"},
    {"name": "Ko Itakura", "team_history": [{"team": "Manchester City", "years": "2019-2022", "logo": "🔵"}, {"team": "Groningen", "years": "2019-2020 (Kiralık)", "logo": "🟢"}, {"team": "Schalke 04", "years": "2021-2022 (Kiralık)", "logo": "🔵"}, {"team": "Borussia M'gladbach", "years": "2022-", "logo": "🟢"}], "nationality": "Japonya", "position": "Stoper", "age": 27, "current_team": "Borussia M'gladbach", "difficulty": "medium"},
    {"name": "Julian Weigl", "team_history": [{"team": "1860 Munich", "years": "2013-2015", "logo": "🔵"}, {"team": "Borussia Dortmund", "years": "2015-2020", "logo": "🟡"}, {"team": "Benfica", "years": "2020-2022", "logo": "🔴"}, {"team": "Borussia M'gladbach", "years": "2022-", "logo": "🟢"}], "nationality": "Almanya", "position": "Orta Saha", "age": 28, "current_team": "Borussia M'gladbach", "difficulty": "medium"},
    {"name": "Tim Kleindienst", "team_history": [{"team": "Energie Cottbus", "years": "2014-2016", "logo": "🔴"}, {"team": "Freiburg", "years": "2016-2018", "logo": "⚫"}, {"team": "Gent", "years": "2018-2019", "logo": "🔵"}, {"team": "Heidenheim", "years": "2019-2024", "logo": "🔴"}, {"team": "Borussia M'gladbach", "years": "2024-", "logo": "🟢"}], "nationality": "Almanya", "position": "Forvet", "age": 29, "current_team": "Borussia M'gladbach", "difficulty": "medium"},
    
    # Freiburg
    {"name": "Vincenzo Grifo", "team_history": [{"team": "Hoffenheim", "years": "2013-2016", "logo": "🔵"}, {"team": "Freiburg", "years": "2016-2017", "logo": "⚫"}, {"team": "Borussia M'gladbach", "years": "2017-2018", "logo": "🟢"}, {"team": "Hoffenheim", "years": "2018-2019", "logo": "🔵"}, {"team": "Freiburg", "years": "2019-", "logo": "⚫"}], "nationality": "İtalya", "position": "Kanat", "age": 31, "current_team": "Freiburg", "difficulty": "medium"},
    {"name": "Ritsu Doan", "team_history": [{"team": "Groningen", "years": "2017-2019", "logo": "🟢"}, {"team": "PSV", "years": "2019-2022", "logo": "🔴"}, {"team": "Arminia Bielefeld", "years": "2021-2022 (Kiralık)", "logo": "🔵"}, {"team": "Freiburg", "years": "2022-", "logo": "⚫"}], "nationality": "Japonya", "position": "Kanat", "age": 26, "current_team": "Freiburg", "difficulty": "medium"},
    {"name": "Michael Gregoritsch", "team_history": [{"team": "Hoffenheim", "years": "2013-2014", "logo": "🔵"}, {"team": "Hamburg", "years": "2014-2017", "logo": "🔵"}, {"team": "Augsburg", "years": "2017-2022", "logo": "🔴"}, {"team": "Schalke 04", "years": "2019-2020 (Kiralık)", "logo": "🔵"}, {"team": "Freiburg", "years": "2022-", "logo": "⚫"}], "nationality": "Avusturya", "position": "Forvet", "age": 30, "current_team": "Freiburg", "difficulty": "medium"},
    {"name": "Maximilian Philipp", "team_history": [{"team": "Freiburg", "years": "2013-2017", "logo": "⚫"}, {"team": "Borussia Dortmund", "years": "2017-2019", "logo": "🟡"}, {"team": "Dynamo Moscow", "years": "2019-2020 (Kiralık)", "logo": "🔵"}, {"team": "Wolfsburg", "years": "2020-2023", "logo": "🟢"}, {"team": "Freiburg", "years": "2023-", "logo": "⚫"}], "nationality": "Almanya", "position": "Forvet", "age": 30, "current_team": "Freiburg", "difficulty": "medium"},
    
    # Hoffenheim
    {"name": "Andrej Kramarić", "team_history": [{"team": "Dinamo Zagreb", "years": "2009-2015", "logo": "🔵"}, {"team": "Rijeka", "years": "2012-2013 (Kiralık)", "logo": "⚪"}, {"team": "Leicester City", "years": "2015-2016", "logo": "🔵"}, {"team": "Hoffenheim", "years": "2016-", "logo": "🔵"}], "nationality": "Hırvatistan", "position": "Forvet", "age": 33, "current_team": "Hoffenheim", "difficulty": "medium"},
    {"name": "Anton Stach", "team_history": [{"team": "Greuther Fürth", "years": "2019-2021", "logo": "🟢"}, {"team": "Mainz 05", "years": "2021-2023", "logo": "🔴"}, {"team": "Hoffenheim", "years": "2023-", "logo": "🔵"}], "nationality": "Almanya", "position": "Orta Saha", "age": 25, "current_team": "Hoffenheim", "difficulty": "medium"},
    {"name": "Adam Hložek", "team_history": [{"team": "Sparta Prag", "years": "2018-2022", "logo": "🔴"}, {"team": "Bayer Leverkusen", "years": "2022-2024", "logo": "🔴"}, {"team": "Hoffenheim", "years": "2024-", "logo": "🔵"}], "nationality": "Çekya", "position": "Forvet", "age": 22, "current_team": "Hoffenheim", "difficulty": "medium"},
    
    # Mainz 05
    {"name": "Jonathan Burkardt", "team_history": [{"team": "Mainz 05", "years": "2019-", "logo": "🔴"}], "nationality": "Almanya", "position": "Forvet", "age": 24, "current_team": "Mainz 05", "difficulty": "medium"},
    {"name": "Brajan Gruda", "team_history": [{"team": "Mainz 05", "years": "2023-", "logo": "🔴"}], "nationality": "Almanya", "position": "Kanat", "age": 19, "current_team": "Mainz 05", "difficulty": "medium"},
    {"name": "Nadiem Amiri", "team_history": [{"team": "Hoffenheim", "years": "2013-2019", "logo": "🔵"}, {"team": "Bayer Leverkusen", "years": "2019-2023", "logo": "🔴"}, {"team": "Mainz 05", "years": "2023-", "logo": "🔴"}], "nationality": "Almanya", "position": "Orta Saha", "age": 27, "current_team": "Mainz 05", "difficulty": "medium"},
    
    # Union Berlin
    {"name": "Benedict Hollerbach", "team_history": [{"team": "Mainz 05", "years": "2021-2023", "logo": "🔴"}, {"team": "Union Berlin", "years": "2023-", "logo": "🔴"}], "nationality": "Almanya", "position": "Kanat", "age": 23, "current_team": "Union Berlin", "difficulty": "hard"},
    {"name": "Kevin Volland", "team_history": [{"team": "1860 Munich", "years": "2010-2011", "logo": "🔵"}, {"team": "Hoffenheim", "years": "2011-2016", "logo": "🔵"}, {"team": "Bayer Leverkusen", "years": "2016-2020", "logo": "🔴"}, {"team": "Monaco", "years": "2020-2024", "logo": "🔴"}, {"team": "Union Berlin", "years": "2024-", "logo": "🔴"}], "nationality": "Almanya", "position": "Forvet", "age": 32, "current_team": "Union Berlin", "difficulty": "medium"},
    {"name": "Robin Gosens", "team_history": [{"team": "Vitesse", "years": "2014-2017", "logo": "🟡"}, {"team": "Heracles", "years": "2015-2017 (Kiralık)", "logo": "⚫"}, {"team": "Atalanta", "years": "2017-2022", "logo": "🔵"}, {"team": "Inter", "years": "2022-2023", "logo": "🔵"}, {"team": "Union Berlin", "years": "2023-", "logo": "🔴"}], "nationality": "Almanya", "position": "Sol Bek", "age": 30, "current_team": "Union Berlin", "difficulty": "easy"},
]
