"""La Liga Players"""

LA_LIGA_PLAYERS = [
    # ============ REAL MADRID ============
    {"name": "Jude Bellingham", "team_history": [{"team": "Birmingham City", "years": "2019-2020", "logo": "🔵"}, {"team": "Borussia Dortmund", "years": "2020-2023", "logo": "🟡"}, {"team": "Real Madrid", "years": "2023-", "logo": "⚪"}], "nationality": "İngiltere", "position": "Orta Saha", "age": 21, "current_team": "Real Madrid", "difficulty": "easy"},
    {"name": "Vinícius Júnior", "team_history": [{"team": "Flamengo", "years": "2017-2018", "logo": "🔴"}, {"team": "Real Madrid", "years": "2018-", "logo": "⚪"}], "nationality": "Brezilya", "position": "Sol Kanat", "age": 24, "current_team": "Real Madrid", "difficulty": "easy"},
    {"name": "Kylian Mbappé", "team_history": [{"team": "Monaco", "years": "2015-2017", "logo": "🔴"}, {"team": "Paris Saint-Germain", "years": "2017-2024", "logo": "🔵"}, {"team": "Real Madrid", "years": "2024-", "logo": "⚪"}], "nationality": "Fransa", "position": "Forvet", "age": 25, "current_team": "Real Madrid", "difficulty": "easy"},
    {"name": "Luka Modrić", "team_history": [{"team": "Dinamo Zagreb", "years": "2003-2008", "logo": "🔵"}, {"team": "Tottenham", "years": "2008-2012", "logo": "⚪"}, {"team": "Real Madrid", "years": "2012-", "logo": "⚪"}], "nationality": "Hırvatistan", "position": "Orta Saha", "age": 39, "current_team": "Real Madrid", "difficulty": "easy"},
    {"name": "Thibaut Courtois", "team_history": [{"team": "Genk", "years": "2009-2011", "logo": "🔵"}, {"team": "Atlético Madrid", "years": "2011-2014", "logo": "🔴"}, {"team": "Chelsea", "years": "2014-2018", "logo": "🔵"}, {"team": "Real Madrid", "years": "2018-", "logo": "⚪"}], "nationality": "Belçika", "position": "Kaleci", "age": 32, "current_team": "Real Madrid", "difficulty": "easy"},
    {"name": "Arda Güler", "team_history": [{"team": "Fenerbahçe", "years": "2021-2023", "logo": "🟡"}, {"team": "Real Madrid", "years": "2023-", "logo": "⚪"}], "nationality": "Türkiye", "position": "Orta Saha", "age": 19, "current_team": "Real Madrid", "difficulty": "easy"},
    {"name": "Federico Valverde", "team_history": [{"team": "Peñarol", "years": "2015-2016", "logo": "🟡"}, {"team": "Real Madrid", "years": "2016-", "logo": "⚪"}, {"team": "Deportivo La Coruña", "years": "2017-2018 (Kiralık)", "logo": "🔵"}], "nationality": "Uruguay", "position": "Orta Saha", "age": 26, "current_team": "Real Madrid", "difficulty": "easy"},
    {"name": "Eduardo Camavinga", "team_history": [{"team": "Rennes", "years": "2018-2021", "logo": "🔴"}, {"team": "Real Madrid", "years": "2021-", "logo": "⚪"}], "nationality": "Fransa", "position": "Orta Saha", "age": 21, "current_team": "Real Madrid", "difficulty": "easy"},
    {"name": "Aurelien Tchouaméni", "team_history": [{"team": "Bordeaux", "years": "2018-2020", "logo": "🔵"}, {"team": "Monaco", "years": "2020-2022", "logo": "🔴"}, {"team": "Real Madrid", "years": "2022-", "logo": "⚪"}], "nationality": "Fransa", "position": "Defansif Orta Saha", "age": 24, "current_team": "Real Madrid", "difficulty": "medium"},
    {"name": "Antonio Rüdiger", "team_history": [{"team": "Stuttgart", "years": "2011-2015", "logo": "⚪"}, {"team": "Roma", "years": "2015-2017", "logo": "🟡"}, {"team": "Chelsea", "years": "2017-2022", "logo": "🔵"}, {"team": "Real Madrid", "years": "2022-", "logo": "⚪"}], "nationality": "Almanya", "position": "Stoper", "age": 31, "current_team": "Real Madrid", "difficulty": "easy"},
    {"name": "Dani Carvajal", "team_history": [{"team": "Real Madrid", "years": "2010-2012", "logo": "⚪"}, {"team": "Bayer Leverkusen", "years": "2012-2013", "logo": "🔴"}, {"team": "Real Madrid", "years": "2013-", "logo": "⚪"}], "nationality": "İspanya", "position": "Sağ Bek", "age": 32, "current_team": "Real Madrid", "difficulty": "easy"},
    {"name": "Ferland Mendy", "team_history": [{"team": "Lyon", "years": "2017-2019", "logo": "🔵"}, {"team": "Real Madrid", "years": "2019-", "logo": "⚪"}], "nationality": "Fransa", "position": "Sol Bek", "age": 29, "current_team": "Real Madrid", "difficulty": "medium"},
    {"name": "David Alaba", "team_history": [{"team": "Bayern Münih", "years": "2008-2021", "logo": "🔴"}, {"team": "Real Madrid", "years": "2021-", "logo": "⚪"}], "nationality": "Avusturya", "position": "Stoper", "age": 32, "current_team": "Real Madrid", "difficulty": "easy"},
    {"name": "Rodrygo", "team_history": [{"team": "Santos", "years": "2017-2019", "logo": "⚫"}, {"team": "Real Madrid", "years": "2019-", "logo": "⚪"}], "nationality": "Brezilya", "position": "Kanat", "age": 23, "current_team": "Real Madrid", "difficulty": "easy"},
    {"name": "Brahim Díaz", "team_history": [{"team": "Manchester City", "years": "2016-2019", "logo": "🔵"}, {"team": "Real Madrid", "years": "2019-", "logo": "⚪"}, {"team": "AC Milan", "years": "2020-2023 (Kiralık)", "logo": "🔴"}], "nationality": "İspanya", "position": "Orta Saha", "age": 25, "current_team": "Real Madrid", "difficulty": "medium"},
    {"name": "Endrick", "team_history": [{"team": "Palmeiras", "years": "2022-2024", "logo": "🟢"}, {"team": "Real Madrid", "years": "2024-", "logo": "⚪"}], "nationality": "Brezilya", "position": "Forvet", "age": 18, "current_team": "Real Madrid", "difficulty": "easy"},
    {"name": "Eder Militão", "team_history": [{"team": "São Paulo", "years": "2017-2018", "logo": "🔴"}, {"team": "Porto", "years": "2018-2019", "logo": "🔵"}, {"team": "Real Madrid", "years": "2019-", "logo": "⚪"}], "nationality": "Brezilya", "position": "Stoper", "age": 26, "current_team": "Real Madrid", "difficulty": "medium"},
    {"name": "Lucas Vázquez", "team_history": [{"team": "Real Madrid", "years": "2015-", "logo": "⚪"}, {"team": "Espanyol", "years": "2014-2015 (Kiralık)", "logo": "🔵"}], "nationality": "İspanya", "position": "Sağ Bek", "age": 33, "current_team": "Real Madrid", "difficulty": "medium"},
    
    # ============ BARCELONA ============
    {"name": "Lamine Yamal", "team_history": [{"team": "Barcelona", "years": "2023-", "logo": "🔵"}], "nationality": "İspanya", "position": "Sağ Kanat", "age": 17, "current_team": "Barcelona", "difficulty": "easy"},
    {"name": "Robert Lewandowski", "team_history": [{"team": "Lech Poznań", "years": "2008-2010", "logo": "🔵"}, {"team": "Borussia Dortmund", "years": "2010-2014", "logo": "🟡"}, {"team": "Bayern Münih", "years": "2014-2022", "logo": "🔴"}, {"team": "Barcelona", "years": "2022-", "logo": "🔵"}], "nationality": "Polonya", "position": "Forvet", "age": 36, "current_team": "Barcelona", "difficulty": "easy"},
    {"name": "Pedri", "team_history": [{"team": "Las Palmas", "years": "2018-2020", "logo": "🟡"}, {"team": "Barcelona", "years": "2020-", "logo": "🔵"}], "nationality": "İspanya", "position": "Orta Saha", "age": 21, "current_team": "Barcelona", "difficulty": "easy"},
    {"name": "Gavi", "team_history": [{"team": "Barcelona", "years": "2021-", "logo": "🔵"}], "nationality": "İspanya", "position": "Orta Saha", "age": 19, "current_team": "Barcelona", "difficulty": "easy"},
    {"name": "Frenkie de Jong", "team_history": [{"team": "Willem II", "years": "2015-2016", "logo": "🔴"}, {"team": "Ajax", "years": "2016-2019", "logo": "⚪"}, {"team": "Barcelona", "years": "2019-", "logo": "🔵"}], "nationality": "Hollanda", "position": "Orta Saha", "age": 27, "current_team": "Barcelona", "difficulty": "easy"},
    {"name": "Raphinha", "team_history": [{"team": "Vitória Guimarães", "years": "2016-2019", "logo": "⚪"}, {"team": "Sporting CP", "years": "2018-2019 (Kiralık)", "logo": "🟢"}, {"team": "Rennes", "years": "2019-2020", "logo": "🔴"}, {"team": "Leeds United", "years": "2020-2022", "logo": "⚪"}, {"team": "Barcelona", "years": "2022-", "logo": "🔵"}], "nationality": "Brezilya", "position": "Sağ Kanat", "age": 27, "current_team": "Barcelona", "difficulty": "easy"},
    {"name": "Ronald Araújo", "team_history": [{"team": "Boston River", "years": "2017-2018", "logo": "🔵"}, {"team": "Barcelona", "years": "2018-", "logo": "🔵"}], "nationality": "Uruguay", "position": "Stoper", "age": 25, "current_team": "Barcelona", "difficulty": "medium"},
    {"name": "Jules Koundé", "team_history": [{"team": "Bordeaux", "years": "2018-2019", "logo": "🔵"}, {"team": "Sevilla", "years": "2019-2022", "logo": "⚪"}, {"team": "Barcelona", "years": "2022-", "logo": "🔵"}], "nationality": "Fransa", "position": "Stoper", "age": 25, "current_team": "Barcelona", "difficulty": "easy"},
    {"name": "Marc-André ter Stegen", "team_history": [{"team": "Borussia M'gladbach", "years": "2011-2014", "logo": "🟢"}, {"team": "Barcelona", "years": "2014-", "logo": "🔵"}], "nationality": "Almanya", "position": "Kaleci", "age": 32, "current_team": "Barcelona", "difficulty": "easy"},
    {"name": "Ferran Torres", "team_history": [{"team": "Valencia", "years": "2017-2020", "logo": "⚪"}, {"team": "Manchester City", "years": "2020-2022", "logo": "🔵"}, {"team": "Barcelona", "years": "2022-", "logo": "🔵"}], "nationality": "İspanya", "position": "Kanat", "age": 24, "current_team": "Barcelona", "difficulty": "easy"},
    {"name": "Dani Olmo", "team_history": [{"team": "Barcelona", "years": "2007-2014", "logo": "🔵"}, {"team": "Dinamo Zagreb", "years": "2014-2020", "logo": "🔵"}, {"team": "RB Leipzig", "years": "2020-2024", "logo": "🔴"}, {"team": "Barcelona", "years": "2024-", "logo": "🔵"}], "nationality": "İspanya", "position": "Orta Saha", "age": 26, "current_team": "Barcelona", "difficulty": "easy"},
    {"name": "Alejandro Balde", "team_history": [{"team": "Barcelona", "years": "2021-", "logo": "🔵"}], "nationality": "İspanya", "position": "Sol Bek", "age": 20, "current_team": "Barcelona", "difficulty": "medium"},
    {"name": "Pau Cubarsí", "team_history": [{"team": "Barcelona", "years": "2023-", "logo": "🔵"}], "nationality": "İspanya", "position": "Stoper", "age": 17, "current_team": "Barcelona", "difficulty": "medium"},
    {"name": "Iñaki Peña", "team_history": [{"team": "Barcelona", "years": "2020-", "logo": "🔵"}, {"team": "Galatasaray", "years": "2022-2023 (Kiralık)", "logo": "🟡"}], "nationality": "İspanya", "position": "Kaleci", "age": 25, "current_team": "Barcelona", "difficulty": "medium"},
    {"name": "Andreas Christensen", "team_history": [{"team": "Chelsea", "years": "2012-2022", "logo": "🔵"}, {"team": "Borussia M'gladbach", "years": "2015-2017 (Kiralık)", "logo": "🟢"}, {"team": "Barcelona", "years": "2022-", "logo": "🔵"}], "nationality": "Danimarka", "position": "Stoper", "age": 28, "current_team": "Barcelona", "difficulty": "medium"},
    {"name": "Fermín López", "team_history": [{"team": "Barcelona", "years": "2023-", "logo": "🔵"}], "nationality": "İspanya", "position": "Orta Saha", "age": 21, "current_team": "Barcelona", "difficulty": "medium"},
    {"name": "Pablo Torre", "team_history": [{"team": "Racing Santander", "years": "2020-2022", "logo": "🟢"}, {"team": "Barcelona", "years": "2022-", "logo": "🔵"}], "nationality": "İspanya", "position": "Orta Saha", "age": 21, "current_team": "Barcelona", "difficulty": "hard"},
    {"name": "Eric García", "team_history": [{"team": "Barcelona", "years": "2008-2017", "logo": "🔵"}, {"team": "Manchester City", "years": "2017-2021", "logo": "🔵"}, {"team": "Barcelona", "years": "2021-", "logo": "🔵"}], "nationality": "İspanya", "position": "Stoper", "age": 23, "current_team": "Barcelona", "difficulty": "medium"},
    
    # ============ ATLÉTICO MADRID ============
    {"name": "Antoine Griezmann", "team_history": [{"team": "Real Sociedad", "years": "2009-2014", "logo": "🔵"}, {"team": "Atlético Madrid", "years": "2014-2019", "logo": "🔴"}, {"team": "Barcelona", "years": "2019-2021", "logo": "🔵"}, {"team": "Atlético Madrid", "years": "2021-", "logo": "🔴"}], "nationality": "Fransa", "position": "İkinci Forvet", "age": 33, "current_team": "Atlético Madrid", "difficulty": "easy"},
    {"name": "Julián Álvarez", "team_history": [{"team": "River Plate", "years": "2018-2022", "logo": "🔴"}, {"team": "Manchester City", "years": "2022-2024", "logo": "🔵"}, {"team": "Atlético Madrid", "years": "2024-", "logo": "🔴"}], "nationality": "Arjantin", "position": "Forvet", "age": 24, "current_team": "Atlético Madrid", "difficulty": "easy"},
    {"name": "Jan Oblak", "team_history": [{"team": "Benfica", "years": "2010-2014", "logo": "🔴"}, {"team": "Atlético Madrid", "years": "2014-", "logo": "🔴"}], "nationality": "Slovenya", "position": "Kaleci", "age": 31, "current_team": "Atlético Madrid", "difficulty": "easy"},
    {"name": "Koke", "team_history": [{"team": "Atlético Madrid", "years": "2009-", "logo": "🔴"}], "nationality": "İspanya", "position": "Orta Saha", "age": 32, "current_team": "Atlético Madrid", "difficulty": "easy"},
    {"name": "Marcos Llorente", "team_history": [{"team": "Real Madrid", "years": "2015-2019", "logo": "⚪"}, {"team": "Alavés", "years": "2017-2018 (Kiralık)", "logo": "🔵"}, {"team": "Atlético Madrid", "years": "2019-", "logo": "🔴"}], "nationality": "İspanya", "position": "Orta Saha", "age": 29, "current_team": "Atlético Madrid", "difficulty": "medium"},
    {"name": "José María Giménez", "team_history": [{"team": "Danubio", "years": "2011-2013", "logo": "⚪"}, {"team": "Atlético Madrid", "years": "2013-", "logo": "🔴"}], "nationality": "Uruguay", "position": "Stoper", "age": 29, "current_team": "Atlético Madrid", "difficulty": "medium"},
    {"name": "Rodrigo De Paul", "team_history": [{"team": "Racing Club", "years": "2013-2016", "logo": "🔵"}, {"team": "Valencia", "years": "2016-2018", "logo": "⚪"}, {"team": "Udinese", "years": "2018-2021", "logo": "⚫"}, {"team": "Atlético Madrid", "years": "2021-", "logo": "🔴"}], "nationality": "Arjantin", "position": "Orta Saha", "age": 30, "current_team": "Atlético Madrid", "difficulty": "easy"},
    {"name": "Alexander Sørloth", "team_history": [{"team": "Rosenborg", "years": "2014-2018", "logo": "⚫"}, {"team": "Crystal Palace", "years": "2018-2019", "logo": "🔴"}, {"team": "Gent", "years": "2018-2019 (Kiralık)", "logo": "🔵"}, {"team": "Trabzonspor", "years": "2019-2020 (Kiralık)", "logo": "🔵"}, {"team": "RB Leipzig", "years": "2020-2021", "logo": "🔴"}, {"team": "Real Sociedad", "years": "2021-2023", "logo": "🔵"}, {"team": "Villarreal", "years": "2023-2024", "logo": "🟡"}, {"team": "Atlético Madrid", "years": "2024-", "logo": "🔴"}], "nationality": "Norveç", "position": "Forvet", "age": 28, "current_team": "Atlético Madrid", "difficulty": "medium"},
    {"name": "Samuel Lino", "team_history": [{"team": "Gil Vicente", "years": "2020-2022", "logo": "🔴"}, {"team": "Valencia", "years": "2022-2023", "logo": "⚪"}, {"team": "Atlético Madrid", "years": "2022-", "logo": "🔴"}], "nationality": "Brezilya", "position": "Sol Kanat", "age": 24, "current_team": "Atlético Madrid", "difficulty": "medium"},
    {"name": "Axel Witsel", "team_history": [{"team": "Standard Liège", "years": "2006-2012", "logo": "🔴"}, {"team": "Benfica", "years": "2012-2012", "logo": "🔴"}, {"team": "Zenit St. Petersburg", "years": "2012-2017", "logo": "🔵"}, {"team": "Tianjin Tianhai", "years": "2017-2018", "logo": "🟠"}, {"team": "Borussia Dortmund", "years": "2018-2022", "logo": "🟡"}, {"team": "Atlético Madrid", "years": "2022-", "logo": "🔴"}], "nationality": "Belçika", "position": "Orta Saha", "age": 35, "current_team": "Atlético Madrid", "difficulty": "easy"},
    {"name": "Conor Gallagher", "team_history": [{"team": "Chelsea", "years": "2017-2024", "logo": "🔵"}, {"team": "Charlton", "years": "2019-2020 (Kiralık)", "logo": "🔴"}, {"team": "Swansea", "years": "2020 (Kiralık)", "logo": "⚪"}, {"team": "West Brom", "years": "2020-2021 (Kiralık)", "logo": "⚪"}, {"team": "Crystal Palace", "years": "2021-2022 (Kiralık)", "logo": "🔴"}, {"team": "Atlético Madrid", "years": "2024-", "logo": "🔴"}], "nationality": "İngiltere", "position": "Orta Saha", "age": 24, "current_team": "Atlético Madrid", "difficulty": "easy"},
    {"name": "Robin Le Normand", "team_history": [{"team": "Real Sociedad", "years": "2018-2024", "logo": "🔵"}, {"team": "Atlético Madrid", "years": "2024-", "logo": "🔴"}], "nationality": "İspanya", "position": "Stoper", "age": 27, "current_team": "Atlético Madrid", "difficulty": "medium"},
    {"name": "Clement Lenglet", "team_history": [{"team": "Nancy", "years": "2014-2017", "logo": "🔴"}, {"team": "Sevilla", "years": "2017-2018", "logo": "⚪"}, {"team": "Barcelona", "years": "2018-2023", "logo": "🔵"}, {"team": "Tottenham", "years": "2022-2023 (Kiralık)", "logo": "⚪"}, {"team": "Aston Villa", "years": "2023-2024 (Kiralık)", "logo": "🟣"}, {"team": "Atlético Madrid", "years": "2024-", "logo": "🔴"}], "nationality": "Fransa", "position": "Stoper", "age": 29, "current_team": "Atlético Madrid", "difficulty": "medium"},
    {"name": "Nahuel Molina", "team_history": [{"team": "Boca Juniors", "years": "2018-2020", "logo": "🔵"}, {"team": "Rosario Central", "years": "2018-2019 (Kiralık)", "logo": "🔵"}, {"team": "Defensa y Justicia", "years": "2019-2020 (Kiralık)", "logo": "🟡"}, {"team": "Udinese", "years": "2020-2022", "logo": "⚫"}, {"team": "Atlético Madrid", "years": "2022-", "logo": "🔴"}], "nationality": "Arjantin", "position": "Sağ Bek", "age": 26, "current_team": "Atlético Madrid", "difficulty": "medium"},
    
    # ============ SEVILLA ============
    {"name": "Jesús Navas", "team_history": [{"team": "Sevilla", "years": "2003-2013", "logo": "⚪"}, {"team": "Manchester City", "years": "2013-2017", "logo": "🔵"}, {"team": "Sevilla", "years": "2017-", "logo": "⚪"}], "nationality": "İspanya", "position": "Sağ Bek", "age": 39, "current_team": "Sevilla", "difficulty": "easy"},
    {"name": "Youssef En-Nesyri", "team_history": [{"team": "Málaga", "years": "2016-2018", "logo": "🔵"}, {"team": "Leganés", "years": "2018-2020", "logo": "🔵"}, {"team": "Sevilla", "years": "2020-2024", "logo": "⚪"}, {"team": "Fenerbahçe", "years": "2024-", "logo": "🟡"}], "nationality": "Fas", "position": "Forvet", "age": 27, "current_team": "Fenerbahçe", "difficulty": "easy"},
    {"name": "Nemanja Gudelj", "team_history": [{"team": "NAC Breda", "years": "2011-2013", "logo": "🟡"}, {"team": "AZ Alkmaar", "years": "2013-2015", "logo": "🔴"}, {"team": "Ajax", "years": "2015-2016", "logo": "⚪"}, {"team": "Tianjin Teda", "years": "2016-2017", "logo": "🔴"}, {"team": "Sporting CP", "years": "2017-2019", "logo": "🟢"}, {"team": "Sevilla", "years": "2019-", "logo": "⚪"}], "nationality": "Sırbistan", "position": "Orta Saha", "age": 33, "current_team": "Sevilla", "difficulty": "medium"},
    {"name": "Isaac Romero", "team_history": [{"team": "Sevilla Atlético", "years": "2020-2023", "logo": "⚪"}, {"team": "Sevilla", "years": "2023-", "logo": "⚪"}], "nationality": "İspanya", "position": "Forvet", "age": 23, "current_team": "Sevilla", "difficulty": "hard"},
    
    # ============ REAL SOCIEDAD ============
    {"name": "Take Kubo", "team_history": [{"team": "Real Madrid", "years": "2019-2022", "logo": "⚪"}, {"team": "Mallorca", "years": "2019-2020 (Kiralık)", "logo": "🔴"}, {"team": "Villarreal", "years": "2020-2021 (Kiralık)", "logo": "🟡"}, {"team": "Getafe", "years": "2021-2022 (Kiralık)", "logo": "🔵"}, {"team": "Real Sociedad", "years": "2022-", "logo": "🔵"}], "nationality": "Japonya", "position": "Kanat", "age": 23, "current_team": "Real Sociedad", "difficulty": "easy"},
    {"name": "Mikel Oyarzabal", "team_history": [{"team": "Real Sociedad", "years": "2015-", "logo": "🔵"}], "nationality": "İspanya", "position": "Sol Kanat", "age": 27, "current_team": "Real Sociedad", "difficulty": "medium"},
    {"name": "Martin Zubimendi", "team_history": [{"team": "Real Sociedad", "years": "2020-", "logo": "🔵"}], "nationality": "İspanya", "position": "Defansif Orta Saha", "age": 25, "current_team": "Real Sociedad", "difficulty": "medium"},
    {"name": "Brais Méndez", "team_history": [{"team": "Celta Vigo", "years": "2017-2022", "logo": "🔵"}, {"team": "Real Sociedad", "years": "2022-", "logo": "🔵"}], "nationality": "İspanya", "position": "Orta Saha", "age": 27, "current_team": "Real Sociedad", "difficulty": "medium"},
    {"name": "Álex Remiro", "team_history": [{"team": "Athletic Bilbao", "years": "2016-2019", "logo": "🔴"}, {"team": "Real Sociedad", "years": "2019-", "logo": "🔵"}], "nationality": "İspanya", "position": "Kaleci", "age": 29, "current_team": "Real Sociedad", "difficulty": "medium"},
    {"name": "Igor Zubeldia", "team_history": [{"team": "Real Sociedad", "years": "2018-", "logo": "🔵"}], "nationality": "İspanya", "position": "Stoper", "age": 27, "current_team": "Real Sociedad", "difficulty": "hard"},
    
    # ============ VILLARREAL ============
    {"name": "Gerard Moreno", "team_history": [{"team": "Villarreal", "years": "2009-2015", "logo": "🟡"}, {"team": "Mallorca", "years": "2015-2016", "logo": "🔴"}, {"team": "Espanyol", "years": "2016-2018", "logo": "🔵"}, {"team": "Villarreal", "years": "2018-", "logo": "🟡"}], "nationality": "İspanya", "position": "Forvet", "age": 32, "current_team": "Villarreal", "difficulty": "easy"},
    {"name": "Álex Baena", "team_history": [{"team": "Villarreal", "years": "2020-", "logo": "🟡"}, {"team": "Girona", "years": "2021-2022 (Kiralık)", "logo": "🔴"}], "nationality": "İspanya", "position": "Orta Saha", "age": 23, "current_team": "Villarreal", "difficulty": "medium"},
    {"name": "Yéremy Pino", "team_history": [{"team": "Villarreal", "years": "2020-", "logo": "🟡"}], "nationality": "İspanya", "position": "Sağ Kanat", "age": 21, "current_team": "Villarreal", "difficulty": "easy"},
    {"name": "Juan Foyth", "team_history": [{"team": "Estudiantes", "years": "2015-2017", "logo": "🔴"}, {"team": "Tottenham", "years": "2017-2021", "logo": "⚪"}, {"team": "Villarreal", "years": "2020-", "logo": "🟡"}], "nationality": "Arjantin", "position": "Sağ Bek", "age": 26, "current_team": "Villarreal", "difficulty": "medium"},
    {"name": "Filip Jörgensen", "team_history": [{"team": "Villarreal", "years": "2022-2024", "logo": "🟡"}, {"team": "Chelsea", "years": "2024-", "logo": "🔵"}], "nationality": "Danimarka", "position": "Kaleci", "age": 22, "current_team": "Chelsea", "difficulty": "medium"},
    
    # ============ ATHLETIC BILBAO ============
    {"name": "Nico Williams", "team_history": [{"team": "Athletic Bilbao", "years": "2021-", "logo": "🔴"}], "nationality": "İspanya", "position": "Sol Kanat", "age": 22, "current_team": "Athletic Bilbao", "difficulty": "easy"},
    {"name": "Iñaki Williams", "team_history": [{"team": "Athletic Bilbao", "years": "2014-", "logo": "🔴"}], "nationality": "İspanya", "position": "Sağ Kanat", "age": 30, "current_team": "Athletic Bilbao", "difficulty": "easy"},
    {"name": "Oihan Sancet", "team_history": [{"team": "Athletic Bilbao", "years": "2020-", "logo": "🔴"}], "nationality": "İspanya", "position": "Orta Saha", "age": 24, "current_team": "Athletic Bilbao", "difficulty": "medium"},
    {"name": "Unai Simón", "team_history": [{"team": "Athletic Bilbao", "years": "2018-", "logo": "🔴"}], "nationality": "İspanya", "position": "Kaleci", "age": 27, "current_team": "Athletic Bilbao", "difficulty": "easy"},
    {"name": "Dani Vivian", "team_history": [{"team": "Athletic Bilbao", "years": "2020-", "logo": "🔴"}, {"team": "Mirandés", "years": "2019-2020 (Kiralık)", "logo": "🔴"}], "nationality": "İspanya", "position": "Stoper", "age": 25, "current_team": "Athletic Bilbao", "difficulty": "medium"},
    {"name": "Yuri Berchiche", "team_history": [{"team": "Real Sociedad", "years": "2013-2017", "logo": "🔵"}, {"team": "PSG", "years": "2017-2018", "logo": "🔵"}, {"team": "Athletic Bilbao", "years": "2018-", "logo": "🔴"}], "nationality": "İspanya", "position": "Sol Bek", "age": 34, "current_team": "Athletic Bilbao", "difficulty": "medium"},
    {"name": "Gorka Guruzeta", "team_history": [{"team": "Amorebieta", "years": "2019-2022", "logo": "🟢"}, {"team": "Athletic Bilbao", "years": "2022-", "logo": "🔴"}], "nationality": "İspanya", "position": "Forvet", "age": 28, "current_team": "Athletic Bilbao", "difficulty": "medium"},
    
    # ============ REAL BETIS ============
    {"name": "Isco", "team_history": [{"team": "Valencia", "years": "2010-2011", "logo": "⚪"}, {"team": "Málaga", "years": "2011-2013", "logo": "🔵"}, {"team": "Real Madrid", "years": "2013-2022", "logo": "⚪"}, {"team": "Sevilla", "years": "2022-2023", "logo": "⚪"}, {"team": "Real Betis", "years": "2023-", "logo": "🟢"}], "nationality": "İspanya", "position": "Orta Saha", "age": 32, "current_team": "Real Betis", "difficulty": "easy"},
    {"name": "Giovani Lo Celso", "team_history": [{"team": "Rosario Central", "years": "2015-2016", "logo": "🔵"}, {"team": "PSG", "years": "2016-2019", "logo": "🔵"}, {"team": "Real Betis", "years": "2018-2019 (Kiralık)", "logo": "🟢"}, {"team": "Tottenham", "years": "2019-2022", "logo": "⚪"}, {"team": "Villarreal", "years": "2022-2023 (Kiralık)", "logo": "🟡"}, {"team": "Real Betis", "years": "2023-", "logo": "🟢"}], "nationality": "Arjantin", "position": "Orta Saha", "age": 28, "current_team": "Real Betis", "difficulty": "easy"},
    {"name": "Nabil Fekir", "team_history": [{"team": "Lyon", "years": "2013-2019", "logo": "🔵"}, {"team": "Real Betis", "years": "2019-", "logo": "🟢"}], "nationality": "Fransa", "position": "Orta Saha", "age": 31, "current_team": "Real Betis", "difficulty": "easy"},
    {"name": "Johnny Cardoso", "team_history": [{"team": "Internacional", "years": "2021-2024", "logo": "🔴"}, {"team": "Real Betis", "years": "2024-", "logo": "🟢"}], "nationality": "ABD", "position": "Orta Saha", "age": 23, "current_team": "Real Betis", "difficulty": "medium"},
    {"name": "Diego Llorente", "team_history": [{"team": "Real Madrid", "years": "2015-2017", "logo": "⚪"}, {"team": "Málaga", "years": "2016-2017 (Kiralık)", "logo": "🔵"}, {"team": "Real Sociedad", "years": "2017-2020", "logo": "🔵"}, {"team": "Leeds United", "years": "2020-2023", "logo": "⚪"}, {"team": "Roma", "years": "2023-2024 (Kiralık)", "logo": "🟡"}, {"team": "Real Betis", "years": "2024-", "logo": "🟢"}], "nationality": "İspanya", "position": "Stoper", "age": 31, "current_team": "Real Betis", "difficulty": "medium"},
    {"name": "Marc Roca", "team_history": [{"team": "Espanyol", "years": "2017-2020", "logo": "🔵"}, {"team": "Bayern Münih", "years": "2020-2022", "logo": "🔴"}, {"team": "Leeds United", "years": "2022-2024", "logo": "⚪"}, {"team": "Real Betis", "years": "2024-", "logo": "🟢"}], "nationality": "İspanya", "position": "Orta Saha", "age": 28, "current_team": "Real Betis", "difficulty": "medium"},
    {"name": "Ayoze Pérez", "team_history": [{"team": "Tenerife", "years": "2012-2014", "logo": "🔵"}, {"team": "Newcastle", "years": "2014-2019", "logo": "⚫"}, {"team": "Leicester City", "years": "2019-2023", "logo": "🔵"}, {"team": "Real Betis", "years": "2023-", "logo": "🟢"}], "nationality": "İspanya", "position": "Forvet", "age": 31, "current_team": "Real Betis", "difficulty": "medium"},
    {"name": "Rui Silva", "team_history": [{"team": "Nacional", "years": "2017-2020", "logo": "⚫"}, {"team": "Granada", "years": "2020-2021", "logo": "🔴"}, {"team": "Real Betis", "years": "2021-", "logo": "🟢"}], "nationality": "Portekiz", "position": "Kaleci", "age": 30, "current_team": "Real Betis", "difficulty": "medium"},
    
    # ============ GIRONA ============
    {"name": "Artem Dovbyk", "team_history": [{"team": "Dnipro-1", "years": "2021-2023", "logo": "🔵"}, {"team": "Girona", "years": "2023-2024", "logo": "🔴"}, {"team": "Roma", "years": "2024-", "logo": "🟡"}], "nationality": "Ukrayna", "position": "Forvet", "age": 27, "current_team": "Roma", "difficulty": "easy"},
    {"name": "Bryan Gil", "team_history": [{"team": "Sevilla", "years": "2018-2021", "logo": "⚪"}, {"team": "Leganés", "years": "2019-2020 (Kiralık)", "logo": "🔵"}, {"team": "Eibar", "years": "2020-2021 (Kiralık)", "logo": "🔴"}, {"team": "Tottenham", "years": "2021-2024", "logo": "⚪"}, {"team": "Valencia", "years": "2022-2023 (Kiralık)", "logo": "⚪"}, {"team": "Sevilla", "years": "2023-2024 (Kiralık)", "logo": "⚪"}, {"team": "Girona", "years": "2024-", "logo": "🔴"}], "nationality": "İspanya", "position": "Kanat", "age": 23, "current_team": "Girona", "difficulty": "medium"},
    {"name": "Miguel Gutiérrez", "team_history": [{"team": "Real Madrid", "years": "2020-2023", "logo": "⚪"}, {"team": "Girona", "years": "2023-", "logo": "🔴"}], "nationality": "İspanya", "position": "Sol Bek", "age": 23, "current_team": "Girona", "difficulty": "medium"},
    {"name": "Daley Blind", "team_history": [{"team": "Ajax", "years": "2008-2014", "logo": "⚪"}, {"team": "Manchester United", "years": "2014-2018", "logo": "🔴"}, {"team": "Ajax", "years": "2018-2022", "logo": "⚪"}, {"team": "Bayern Münih", "years": "2022-2023", "logo": "🔴"}, {"team": "Girona", "years": "2023-", "logo": "🔴"}], "nationality": "Hollanda", "position": "Stoper", "age": 34, "current_team": "Girona", "difficulty": "easy"},
    {"name": "Paulo Gazzaniga", "team_history": [{"team": "Gillingham", "years": "2012-2013", "logo": "🔵"}, {"team": "Southampton", "years": "2013-2017", "logo": "🔴"}, {"team": "Tottenham", "years": "2017-2021", "logo": "⚪"}, {"team": "Elche", "years": "2021 (Kiralık)", "logo": "🟢"}, {"team": "Fulham", "years": "2021-2022", "logo": "⚪"}, {"team": "Girona", "years": "2022-", "logo": "🔴"}], "nationality": "Arjantin", "position": "Kaleci", "age": 32, "current_team": "Girona", "difficulty": "medium"},
    
    # ============ OTHER LA LIGA ============
    # Valencia
    {"name": "Hugo Duro", "team_history": [{"team": "Getafe", "years": "2019-2021", "logo": "🔵"}, {"team": "Real Madrid", "years": "2020-2021 (Kiralık)", "logo": "⚪"}, {"team": "Valencia", "years": "2021-", "logo": "⚪"}], "nationality": "İspanya", "position": "Forvet", "age": 25, "current_team": "Valencia", "difficulty": "medium"},
    {"name": "Giorgi Mamardashvili", "team_history": [{"team": "Dinamo Tbilisi", "years": "2019-2021", "logo": "🔵"}, {"team": "Valencia", "years": "2021-", "logo": "⚪"}], "nationality": "Gürcistan", "position": "Kaleci", "age": 23, "current_team": "Valencia", "difficulty": "easy"},
    {"name": "Javi Guerra", "team_history": [{"team": "Valencia", "years": "2022-", "logo": "⚪"}], "nationality": "İspanya", "position": "Orta Saha", "age": 21, "current_team": "Valencia", "difficulty": "medium"},
    {"name": "Pepelu", "team_history": [{"team": "Levante", "years": "2019-2024", "logo": "🔵"}, {"team": "Valencia", "years": "2024-", "logo": "⚪"}], "nationality": "İspanya", "position": "Orta Saha", "age": 26, "current_team": "Valencia", "difficulty": "medium"},
    
    # Celta Vigo
    {"name": "Iago Aspas", "team_history": [{"team": "Celta Vigo", "years": "2008-2013", "logo": "🔵"}, {"team": "Liverpool", "years": "2013-2015", "logo": "🔴"}, {"team": "Sevilla", "years": "2014-2015 (Kiralık)", "logo": "⚪"}, {"team": "Celta Vigo", "years": "2015-", "logo": "🔵"}], "nationality": "İspanya", "position": "Forvet", "age": 37, "current_team": "Celta Vigo", "difficulty": "easy"},
    {"name": "Borja Iglesias", "team_history": [{"team": "Celta Vigo", "years": "2014-2018", "logo": "🔵"}, {"team": "Zaragoza", "years": "2016-2017 (Kiralık)", "logo": "⚪"}, {"team": "Espanyol", "years": "2018-2019", "logo": "🔵"}, {"team": "Real Betis", "years": "2019-2024", "logo": "🟢"}, {"team": "Bayer Leverkusen", "years": "2024 (Kiralık)", "logo": "🔴"}, {"team": "Celta Vigo", "years": "2024-", "logo": "🔵"}], "nationality": "İspanya", "position": "Forvet", "age": 31, "current_team": "Celta Vigo", "difficulty": "medium"},
    {"name": "Oscar Mingueza", "team_history": [{"team": "Barcelona", "years": "2020-2022", "logo": "🔵"}, {"team": "Celta Vigo", "years": "2022-", "logo": "🔵"}], "nationality": "İspanya", "position": "Sağ Bek", "age": 25, "current_team": "Celta Vigo", "difficulty": "medium"},
    
    # Mallorca
    {"name": "Vedat Muriqi", "team_history": [{"team": "Prishtina", "years": "2014-2018", "logo": "🔵"}, {"team": "Rizespor", "years": "2018-2019", "logo": "🟢"}, {"team": "Fenerbahçe", "years": "2019-2020", "logo": "🟡"}, {"team": "Lazio", "years": "2020-2022", "logo": "🔵"}, {"team": "Mallorca", "years": "2022-", "logo": "🔴"}], "nationality": "Kosova", "position": "Forvet", "age": 30, "current_team": "Mallorca", "difficulty": "medium"},
    {"name": "Predrag Rajković", "team_history": [{"team": "Crvena zvezda", "years": "2011-2017", "logo": "🔴"}, {"team": "Maccabi Tel Aviv", "years": "2017-2019", "logo": "🟡"}, {"team": "Reims", "years": "2019-2023", "logo": "🔴"}, {"team": "Mallorca", "years": "2023-", "logo": "🔴"}], "nationality": "Sırbistan", "position": "Kaleci", "age": 29, "current_team": "Mallorca", "difficulty": "medium"},
    
    # Getafe
    {"name": "Mason Greenwood", "team_history": [{"team": "Manchester United", "years": "2018-2023", "logo": "🔴"}, {"team": "Getafe", "years": "2023-2024", "logo": "🔵"}, {"team": "Marsilya", "years": "2024-", "logo": "🔵"}], "nationality": "İngiltere", "position": "Forvet", "age": 23, "current_team": "Marsilya", "difficulty": "easy"},
    {"name": "Borja Mayoral", "team_history": [{"team": "Real Madrid", "years": "2016-2022", "logo": "⚪"}, {"team": "Wolfsburg", "years": "2017-2018 (Kiralık)", "logo": "🟢"}, {"team": "Levante", "years": "2018-2019 (Kiralık)", "logo": "🔵"}, {"team": "Roma", "years": "2020-2022 (Kiralık)", "logo": "🟡"}, {"team": "Getafe", "years": "2022-", "logo": "🔵"}], "nationality": "İspanya", "position": "Forvet", "age": 27, "current_team": "Getafe", "difficulty": "medium"},
]
