"""Football Legends - Efsane Oyuncular"""

LEGENDS_PLAYERS = [
    # ============ HOLLANDA EFSANELERİ ============
    {"name": "Arjen Robben", "team_history": [{"team": "Groningen", "years": "2000-2002", "logo": "🟢"}, {"team": "PSV", "years": "2002-2004", "logo": "🔴"}, {"team": "Chelsea", "years": "2004-2007", "logo": "🔵"}, {"team": "Real Madrid", "years": "2007-2009", "logo": "⚪"}, {"team": "Bayern Münih", "years": "2009-2019", "logo": "🔴"}, {"team": "Groningen", "years": "2020-2021", "logo": "🟢"}], "nationality": "Hollanda", "position": "Sağ Kanat", "age": 40, "current_team": "Emekli", "difficulty": "easy"},
    {"name": "Wesley Sneijder", "team_history": [{"team": "Ajax", "years": "2002-2007", "logo": "⚪"}, {"team": "Real Madrid", "years": "2007-2009", "logo": "⚪"}, {"team": "Inter", "years": "2009-2013", "logo": "🔵"}, {"team": "Galatasaray", "years": "2013-2017", "logo": "🟡"}, {"team": "Nice", "years": "2017-2018", "logo": "🔴"}, {"team": "Al-Gharafa", "years": "2018-2019", "logo": "🟡"}], "nationality": "Hollanda", "position": "Orta Saha", "age": 40, "current_team": "Emekli", "difficulty": "easy"},
    {"name": "Robin van Persie", "team_history": [{"team": "Feyenoord", "years": "2001-2004", "logo": "🔴"}, {"team": "Arsenal", "years": "2004-2012", "logo": "🔴"}, {"team": "Manchester United", "years": "2012-2015", "logo": "🔴"}, {"team": "Fenerbahçe", "years": "2015-2018", "logo": "🟡"}, {"team": "Feyenoord", "years": "2018-2019", "logo": "🔴"}], "nationality": "Hollanda", "position": "Forvet", "age": 40, "current_team": "Emekli", "difficulty": "easy"},
    {"name": "Ruud van Nistelrooy", "team_history": [{"team": "Den Bosch", "years": "1993-1998", "logo": "🔵"}, {"team": "Heerenveen", "years": "1998-1999", "logo": "🔵"}, {"team": "PSV", "years": "1999-2001", "logo": "🔴"}, {"team": "Manchester United", "years": "2001-2006", "logo": "🔴"}, {"team": "Real Madrid", "years": "2006-2010", "logo": "⚪"}, {"team": "Hamburg", "years": "2010-2011", "logo": "🔵"}, {"team": "Málaga", "years": "2011-2012", "logo": "🔵"}], "nationality": "Hollanda", "position": "Forvet", "age": 48, "current_team": "Emekli", "difficulty": "easy"},
    {"name": "Dennis Bergkamp", "team_history": [{"team": "Ajax", "years": "1986-1993", "logo": "⚪"}, {"team": "Inter", "years": "1993-1995", "logo": "🔵"}, {"team": "Arsenal", "years": "1995-2006", "logo": "🔴"}], "nationality": "Hollanda", "position": "İkinci Forvet", "age": 55, "current_team": "Emekli", "difficulty": "easy"},
    {"name": "Marco van Basten", "team_history": [{"team": "Ajax", "years": "1981-1987", "logo": "⚪"}, {"team": "AC Milan", "years": "1987-1995", "logo": "🔴"}], "nationality": "Hollanda", "position": "Forvet", "age": 59, "current_team": "Emekli", "difficulty": "medium"},
    {"name": "Johan Cruyff", "team_history": [{"team": "Ajax", "years": "1964-1973", "logo": "⚪"}, {"team": "Barcelona", "years": "1973-1978", "logo": "🔵"}, {"team": "Los Angeles Aztecs", "years": "1979", "logo": "🟢"}, {"team": "Washington Diplomats", "years": "1980-1981", "logo": "🔴"}, {"team": "Levante", "years": "1981", "logo": "🔵"}, {"team": "Ajax", "years": "1981-1983", "logo": "⚪"}, {"team": "Feyenoord", "years": "1983-1984", "logo": "🔴"}], "nationality": "Hollanda", "position": "Forvet", "age": 0, "current_team": "Vefat", "difficulty": "medium"},
    {"name": "Clarence Seedorf", "team_history": [{"team": "Ajax", "years": "1992-1995", "logo": "⚪"}, {"team": "Sampdoria", "years": "1995-1996", "logo": "🔵"}, {"team": "Real Madrid", "years": "1996-1999", "logo": "⚪"}, {"team": "Inter", "years": "1999-2002", "logo": "🔵"}, {"team": "AC Milan", "years": "2002-2012", "logo": "🔴"}, {"team": "Botafogo", "years": "2012-2014", "logo": "⚫"}], "nationality": "Hollanda", "position": "Orta Saha", "age": 48, "current_team": "Emekli", "difficulty": "easy"},
    {"name": "Patrick Kluivert", "team_history": [{"team": "Ajax", "years": "1994-1997", "logo": "⚪"}, {"team": "AC Milan", "years": "1997-1998", "logo": "🔴"}, {"team": "Barcelona", "years": "1998-2004", "logo": "🔵"}, {"team": "Newcastle", "years": "2004-2005", "logo": "⚫"}, {"team": "Valencia", "years": "2005-2006", "logo": "⚪"}, {"team": "PSV", "years": "2006-2007", "logo": "🔴"}, {"team": "Lille", "years": "2007-2008", "logo": "🔴"}], "nationality": "Hollanda", "position": "Forvet", "age": 48, "current_team": "Emekli", "difficulty": "easy"},
    {"name": "Edgar Davids", "team_history": [{"team": "Ajax", "years": "1991-1996", "logo": "⚪"}, {"team": "AC Milan", "years": "1996-1998", "logo": "🔴"}, {"team": "Juventus", "years": "1998-2004", "logo": "⚫"}, {"team": "Barcelona", "years": "2003-2004 (Kiralık)", "logo": "🔵"}, {"team": "Inter", "years": "2004-2005", "logo": "🔵"}, {"team": "Tottenham", "years": "2005-2007", "logo": "⚪"}, {"team": "Ajax", "years": "2007-2008", "logo": "⚪"}, {"team": "Barnet", "years": "2012-2013", "logo": "🟠"}], "nationality": "Hollanda", "position": "Orta Saha", "age": 51, "current_team": "Emekli", "difficulty": "medium"},
    
    # ============ FRANSA EFSANELERİ ============
    {"name": "Zinedine Zidane", "team_history": [{"team": "Cannes", "years": "1988-1992", "logo": "🔴"}, {"team": "Bordeaux", "years": "1992-1996", "logo": "🔵"}, {"team": "Juventus", "years": "1996-2001", "logo": "⚫"}, {"team": "Real Madrid", "years": "2001-2006", "logo": "⚪"}], "nationality": "Fransa", "position": "Orta Saha", "age": 52, "current_team": "Emekli", "difficulty": "easy"},
    {"name": "Thierry Henry", "team_history": [{"team": "Monaco", "years": "1994-1999", "logo": "🔴"}, {"team": "Juventus", "years": "1999", "logo": "⚫"}, {"team": "Arsenal", "years": "1999-2007", "logo": "🔴"}, {"team": "Barcelona", "years": "2007-2010", "logo": "🔵"}, {"team": "New York Red Bulls", "years": "2010-2014", "logo": "🔴"}, {"team": "Arsenal", "years": "2012 (Kiralık)", "logo": "🔴"}], "nationality": "Fransa", "position": "Forvet", "age": 47, "current_team": "Emekli", "difficulty": "easy"},
    {"name": "Franck Ribéry", "team_history": [{"team": "Boulogne", "years": "2002-2003", "logo": "🔴"}, {"team": "Alès", "years": "2003", "logo": "🔴"}, {"team": "Brest", "years": "2003-2004", "logo": "🔴"}, {"team": "Metz", "years": "2004-2005", "logo": "🟤"}, {"team": "Galatasaray", "years": "2005", "logo": "🟡"}, {"team": "Marsilya", "years": "2005-2007", "logo": "🔵"}, {"team": "Bayern Münih", "years": "2007-2019", "logo": "🔴"}, {"team": "Fiorentina", "years": "2019-2021", "logo": "🟣"}, {"team": "Salernitana", "years": "2021-2022", "logo": "🟣"}], "nationality": "Fransa", "position": "Sol Kanat", "age": 41, "current_team": "Emekli", "difficulty": "easy"},
    {"name": "David Trezeguet", "team_history": [{"team": "Platense", "years": "1994-1995", "logo": "⚪"}, {"team": "Monaco", "years": "1995-2000", "logo": "🔴"}, {"team": "Juventus", "years": "2000-2010", "logo": "⚫"}, {"team": "Hercules", "years": "2010-2011", "logo": "🔵"}, {"team": "River Plate", "years": "2012-2013", "logo": "🔴"}, {"team": "Newell's Old Boys", "years": "2013", "logo": "🔴"}, {"team": "Pune City", "years": "2014-2015", "logo": "🟣"}], "nationality": "Fransa", "position": "Forvet", "age": 47, "current_team": "Emekli", "difficulty": "easy"},
    {"name": "Patrick Vieira", "team_history": [{"team": "Cannes", "years": "1993-1995", "logo": "🔴"}, {"team": "AC Milan", "years": "1995-1996", "logo": "🔴"}, {"team": "Arsenal", "years": "1996-2005", "logo": "🔴"}, {"team": "Juventus", "years": "2005-2006", "logo": "⚫"}, {"team": "Inter", "years": "2006-2010", "logo": "🔵"}, {"team": "Manchester City", "years": "2010-2011", "logo": "🔵"}], "nationality": "Fransa", "position": "Orta Saha", "age": 48, "current_team": "Emekli", "difficulty": "easy"},
    {"name": "Eric Cantona", "team_history": [{"team": "Auxerre", "years": "1983-1988", "logo": "⚪"}, {"team": "Martigues", "years": "1985-1986 (Kiralık)", "logo": "🔵"}, {"team": "Marsilya", "years": "1988-1991", "logo": "🔵"}, {"team": "Bordeaux", "years": "1989 (Kiralık)", "logo": "🔵"}, {"team": "Montpellier", "years": "1989-1990 (Kiralık)", "logo": "🟠"}, {"team": "Nîmes", "years": "1991-1992", "logo": "🔴"}, {"team": "Leeds United", "years": "1992", "logo": "⚪"}, {"team": "Manchester United", "years": "1992-1997", "logo": "🔴"}], "nationality": "Fransa", "position": "Forvet", "age": 58, "current_team": "Emekli", "difficulty": "easy"},
    {"name": "Michel Platini", "team_history": [{"team": "Nancy", "years": "1972-1979", "logo": "🔴"}, {"team": "Saint-Étienne", "years": "1979-1982", "logo": "🟢"}, {"team": "Juventus", "years": "1982-1987", "logo": "⚫"}], "nationality": "Fransa", "position": "Orta Saha", "age": 69, "current_team": "Emekli", "difficulty": "medium"},
    {"name": "Jean-Pierre Papin", "team_history": [{"team": "Valenciennes", "years": "1984-1985", "logo": "🔴"}, {"team": "Club Brugge", "years": "1985-1986", "logo": "🔵"}, {"team": "Marsilya", "years": "1986-1992", "logo": "🔵"}, {"team": "AC Milan", "years": "1992-1994", "logo": "🔴"}, {"team": "Bayern Münih", "years": "1994-1996", "logo": "🔴"}, {"team": "Bordeaux", "years": "1996-1998", "logo": "🔵"}, {"team": "Guingamp", "years": "1998-1999", "logo": "🔴"}], "nationality": "Fransa", "position": "Forvet", "age": 61, "current_team": "Emekli", "difficulty": "medium"},
    {"name": "Lilian Thuram", "team_history": [{"team": "Monaco", "years": "1991-1996", "logo": "🔴"}, {"team": "Parma", "years": "1996-2001", "logo": "🟡"}, {"team": "Juventus", "years": "2001-2006", "logo": "⚫"}, {"team": "Barcelona", "years": "2006-2008", "logo": "🔵"}], "nationality": "Fransa", "position": "Sağ Bek", "age": 52, "current_team": "Emekli", "difficulty": "medium"},
    
    # ============ İNGİLTERE EFSANELERİ ============
    {"name": "David Beckham", "team_history": [{"team": "Manchester United", "years": "1992-2003", "logo": "🔴"}, {"team": "Preston North End", "years": "1995 (Kiralık)", "logo": "⚪"}, {"team": "Real Madrid", "years": "2003-2007", "logo": "⚪"}, {"team": "LA Galaxy", "years": "2007-2012", "logo": "🔵"}, {"team": "AC Milan", "years": "2009 (Kiralık)", "logo": "🔴"}, {"team": "AC Milan", "years": "2010 (Kiralık)", "logo": "🔴"}, {"team": "Paris Saint-Germain", "years": "2013", "logo": "🔵"}], "nationality": "İngiltere", "position": "Sağ Kanat", "age": 49, "current_team": "Emekli", "difficulty": "easy"},
    {"name": "Steven Gerrard", "team_history": [{"team": "Liverpool", "years": "1998-2015", "logo": "🔴"}, {"team": "LA Galaxy", "years": "2015-2016", "logo": "🔵"}], "nationality": "İngiltere", "position": "Orta Saha", "age": 44, "current_team": "Emekli", "difficulty": "easy"},
    {"name": "Frank Lampard", "team_history": [{"team": "West Ham", "years": "1995-2001", "logo": "🟣"}, {"team": "Swansea City", "years": "1996 (Kiralık)", "logo": "⚪"}, {"team": "Chelsea", "years": "2001-2014", "logo": "🔵"}, {"team": "Manchester City", "years": "2014-2015", "logo": "🔵"}, {"team": "New York City", "years": "2015-2016", "logo": "🔵"}], "nationality": "İngiltere", "position": "Orta Saha", "age": 46, "current_team": "Emekli", "difficulty": "easy"},
    {"name": "Paul Scholes", "team_history": [{"team": "Manchester United", "years": "1993-2011", "logo": "🔴"}, {"team": "Manchester United", "years": "2012-2013", "logo": "🔴"}], "nationality": "İngiltere", "position": "Orta Saha", "age": 49, "current_team": "Emekli", "difficulty": "easy"},
    {"name": "Wayne Rooney", "team_history": [{"team": "Everton", "years": "2002-2004", "logo": "🔵"}, {"team": "Manchester United", "years": "2004-2017", "logo": "🔴"}, {"team": "Everton", "years": "2017-2018", "logo": "🔵"}, {"team": "DC United", "years": "2018-2019", "logo": "⚫"}, {"team": "Derby County", "years": "2020-2021", "logo": "⚪"}], "nationality": "İngiltere", "position": "Forvet", "age": 39, "current_team": "Emekli", "difficulty": "easy"},
    {"name": "Michael Owen", "team_history": [{"team": "Liverpool", "years": "1996-2004", "logo": "🔴"}, {"team": "Real Madrid", "years": "2004-2005", "logo": "⚪"}, {"team": "Newcastle", "years": "2005-2009", "logo": "⚫"}, {"team": "Manchester United", "years": "2009-2012", "logo": "🔴"}, {"team": "Stoke City", "years": "2012-2013", "logo": "🔴"}], "nationality": "İngiltere", "position": "Forvet", "age": 44, "current_team": "Emekli", "difficulty": "easy"},
    {"name": "Alan Shearer", "team_history": [{"team": "Southampton", "years": "1988-1992", "logo": "🔴"}, {"team": "Blackburn", "years": "1992-1996", "logo": "🔵"}, {"team": "Newcastle", "years": "1996-2006", "logo": "⚫"}], "nationality": "İngiltere", "position": "Forvet", "age": 54, "current_team": "Emekli", "difficulty": "easy"},
    {"name": "Rio Ferdinand", "team_history": [{"team": "West Ham", "years": "1996-2000", "logo": "🟣"}, {"team": "Bournemouth", "years": "1997 (Kiralık)", "logo": "🔴"}, {"team": "Leeds United", "years": "2000-2002", "logo": "⚪"}, {"team": "Manchester United", "years": "2002-2014", "logo": "🔴"}, {"team": "QPR", "years": "2014-2015", "logo": "🔵"}], "nationality": "İngiltere", "position": "Stoper", "age": 45, "current_team": "Emekli", "difficulty": "easy"},
    {"name": "John Terry", "team_history": [{"team": "Chelsea", "years": "1998-2017", "logo": "🔵"}, {"team": "Nottingham Forest", "years": "2000 (Kiralık)", "logo": "🔴"}, {"team": "Aston Villa", "years": "2017-2018", "logo": "🟣"}], "nationality": "İngiltere", "position": "Stoper", "age": 43, "current_team": "Emekli", "difficulty": "easy"},
    {"name": "Ashley Cole", "team_history": [{"team": "Arsenal", "years": "1999-2006", "logo": "🔴"}, {"team": "Crystal Palace", "years": "2000 (Kiralık)", "logo": "🔴"}, {"team": "Chelsea", "years": "2006-2014", "logo": "🔵"}, {"team": "Roma", "years": "2014-2015", "logo": "🟡"}, {"team": "LA Galaxy", "years": "2016-2018", "logo": "🔵"}, {"team": "Derby County", "years": "2019", "logo": "⚪"}], "nationality": "İngiltere", "position": "Sol Bek", "age": 43, "current_team": "Emekli", "difficulty": "easy"},
    {"name": "Gary Neville", "team_history": [{"team": "Manchester United", "years": "1992-2011", "logo": "🔴"}], "nationality": "İngiltere", "position": "Sağ Bek", "age": 49, "current_team": "Emekli", "difficulty": "medium"},
    {"name": "Peter Schmeichel", "team_history": [{"team": "Hvidovre IF", "years": "1981-1984", "logo": "⚪"}, {"team": "Brøndby", "years": "1987-1991", "logo": "🟡"}, {"team": "Manchester United", "years": "1991-1999", "logo": "🔴"}, {"team": "Sporting CP", "years": "1999-2001", "logo": "🟢"}, {"team": "Aston Villa", "years": "2001-2002", "logo": "🟣"}, {"team": "Manchester City", "years": "2002-2003", "logo": "🔵"}], "nationality": "Danimarka", "position": "Kaleci", "age": 60, "current_team": "Emekli", "difficulty": "easy"},
    
    # ============ BREZİLYA EFSANELERİ ============
    {"name": "Ronaldo Nazário", "team_history": [{"team": "Cruzeiro", "years": "1993-1994", "logo": "🔵"}, {"team": "PSV", "years": "1994-1996", "logo": "🔴"}, {"team": "Barcelona", "years": "1996-1997", "logo": "🔵"}, {"team": "Inter", "years": "1997-2002", "logo": "🔵"}, {"team": "Real Madrid", "years": "2002-2007", "logo": "⚪"}, {"team": "AC Milan", "years": "2007-2008", "logo": "🔴"}, {"team": "Corinthians", "years": "2009-2011", "logo": "⚫"}], "nationality": "Brezilya", "position": "Forvet", "age": 48, "current_team": "Emekli", "difficulty": "easy"},
    {"name": "Ronaldinho", "team_history": [{"team": "Grêmio", "years": "1998-2001", "logo": "🔵"}, {"team": "Paris Saint-Germain", "years": "2001-2003", "logo": "🔵"}, {"team": "Barcelona", "years": "2003-2008", "logo": "🔵"}, {"team": "AC Milan", "years": "2008-2010", "logo": "🔴"}, {"team": "Flamengo", "years": "2011", "logo": "🔴"}, {"team": "Atlético Mineiro", "years": "2012-2013", "logo": "⚫"}, {"team": "Querétaro", "years": "2014-2015", "logo": "🔵"}, {"team": "Fluminense", "years": "2015", "logo": "🟣"}], "nationality": "Brezilya", "position": "Orta Saha", "age": 44, "current_team": "Emekli", "difficulty": "easy"},
    {"name": "Kaká", "team_history": [{"team": "São Paulo", "years": "2001-2003", "logo": "🔴"}, {"team": "AC Milan", "years": "2003-2009", "logo": "🔴"}, {"team": "Real Madrid", "years": "2009-2013", "logo": "⚪"}, {"team": "AC Milan", "years": "2013-2014", "logo": "🔴"}, {"team": "Orlando City", "years": "2015-2017", "logo": "🟣"}], "nationality": "Brezilya", "position": "Orta Saha", "age": 42, "current_team": "Emekli", "difficulty": "easy"},
    {"name": "Rivaldo", "team_history": [{"team": "Santa Cruz", "years": "1991-1992", "logo": "🔴"}, {"team": "Mogi Mirim", "years": "1992-1993", "logo": "🟢"}, {"team": "Corinthians", "years": "1993-1994", "logo": "⚫"}, {"team": "Palmeiras", "years": "1994-1996", "logo": "🟢"}, {"team": "Deportivo La Coruña", "years": "1996-1997", "logo": "🔵"}, {"team": "Barcelona", "years": "1997-2002", "logo": "🔵"}, {"team": "AC Milan", "years": "2002-2004", "logo": "🔴"}, {"team": "Cruzeiro", "years": "2004-2005", "logo": "🔵"}, {"team": "Olympiacos", "years": "2004-2007", "logo": "🔴"}, {"team": "AEK Athens", "years": "2007-2008", "logo": "🟡"}, {"team": "Bunyodkor", "years": "2008-2010", "logo": "🟢"}, {"team": "São Paulo", "years": "2011", "logo": "🔴"}, {"team": "São Caetano", "years": "2013-2014", "logo": "🔵"}, {"team": "Mogi Mirim", "years": "2014-2015", "logo": "🟢"}], "nationality": "Brezilya", "position": "Orta Saha", "age": 52, "current_team": "Emekli", "difficulty": "easy"},
    {"name": "Roberto Carlos", "team_history": [{"team": "União São João", "years": "1991-1993", "logo": "🔴"}, {"team": "Palmeiras", "years": "1993-1995", "logo": "🟢"}, {"team": "Inter", "years": "1995-1996", "logo": "🔵"}, {"team": "Real Madrid", "years": "1996-2007", "logo": "⚪"}, {"team": "Fenerbahçe", "years": "2007-2009", "logo": "🟡"}, {"team": "Corinthians", "years": "2010-2011", "logo": "⚫"}, {"team": "Anzhi Makhachkala", "years": "2011-2012", "logo": "🟡"}], "nationality": "Brezilya", "position": "Sol Bek", "age": 51, "current_team": "Emekli", "difficulty": "easy"},
    {"name": "Cafu", "team_history": [{"team": "São Paulo", "years": "1989-1994", "logo": "🔴"}, {"team": "Real Zaragoza", "years": "1994-1995", "logo": "🔵"}, {"team": "Palmeiras", "years": "1995", "logo": "🟢"}, {"team": "Roma", "years": "1997-2003", "logo": "🟡"}, {"team": "AC Milan", "years": "2003-2008", "logo": "🔴"}], "nationality": "Brezilya", "position": "Sağ Bek", "age": 54, "current_team": "Emekli", "difficulty": "easy"},
    {"name": "Romário", "team_history": [{"team": "Vasco da Gama", "years": "1985-1988", "logo": "⚫"}, {"team": "PSV", "years": "1988-1993", "logo": "🔴"}, {"team": "Barcelona", "years": "1993-1995", "logo": "🔵"}, {"team": "Flamengo", "years": "1995-1996", "logo": "🔴"}, {"team": "Valencia", "years": "1996-1997", "logo": "⚪"}, {"team": "Flamengo", "years": "1998-1999", "logo": "🔴"}, {"team": "Vasco da Gama", "years": "2000-2002", "logo": "⚫"}, {"team": "Fluminense", "years": "2002-2004", "logo": "🟣"}, {"team": "Al-Sadd", "years": "2003-2004", "logo": "⚪"}, {"team": "Fluminense", "years": "2004-2005", "logo": "🟣"}, {"team": "Vasco da Gama", "years": "2005-2006", "logo": "⚫"}, {"team": "Miami FC", "years": "2006", "logo": "🔵"}, {"team": "Adelaide United", "years": "2006-2007", "logo": "🔴"}, {"team": "Vasco da Gama", "years": "2007-2008", "logo": "⚫"}, {"team": "America Rio", "years": "2009", "logo": "🔴"}], "nationality": "Brezilya", "position": "Forvet", "age": 58, "current_team": "Emekli", "difficulty": "easy"},
    {"name": "Adriano", "team_history": [{"team": "Flamengo", "years": "1999-2001", "logo": "🔴"}, {"team": "Inter", "years": "2001-2009", "logo": "🔵"}, {"team": "Parma", "years": "2002-2004 (Kiralık)", "logo": "🟡"}, {"team": "Fiorentina", "years": "2004 (Kiralık)", "logo": "🟣"}, {"team": "São Paulo", "years": "2008 (Kiralık)", "logo": "🔴"}, {"team": "Flamengo", "years": "2009-2010", "logo": "🔴"}, {"team": "Roma", "years": "2010-2011", "logo": "🟡"}, {"team": "Corinthians", "years": "2011-2012", "logo": "⚫"}, {"team": "Flamengo", "years": "2012", "logo": "🔴"}, {"team": "Atlético Paranaense", "years": "2014", "logo": "🔴"}, {"team": "Miami United", "years": "2016", "logo": "🟣"}], "nationality": "Brezilya", "position": "Forvet", "age": 42, "current_team": "Emekli", "difficulty": "medium"},
    {"name": "Pelé", "team_history": [{"team": "Santos", "years": "1956-1974", "logo": "⚫"}, {"team": "New York Cosmos", "years": "1975-1977", "logo": "🟢"}], "nationality": "Brezilya", "position": "Forvet", "age": 0, "current_team": "Vefat", "difficulty": "easy"},
    
    # ============ ARJANTİN EFSANELERİ ============
    {"name": "Diego Maradona", "team_history": [{"team": "Argentinos Juniors", "years": "1976-1981", "logo": "🔴"}, {"team": "Boca Juniors", "years": "1981-1982", "logo": "🔵"}, {"team": "Barcelona", "years": "1982-1984", "logo": "🔵"}, {"team": "Napoli", "years": "1984-1991", "logo": "🔵"}, {"team": "Sevilla", "years": "1992-1993", "logo": "⚪"}, {"team": "Newell's Old Boys", "years": "1993", "logo": "🔴"}, {"team": "Boca Juniors", "years": "1995-1997", "logo": "🔵"}], "nationality": "Arjantin", "position": "Orta Saha", "age": 0, "current_team": "Vefat", "difficulty": "easy"},
    {"name": "Gabriel Batistuta", "team_history": [{"team": "Newell's Old Boys", "years": "1988-1989", "logo": "🔴"}, {"team": "River Plate", "years": "1989-1991", "logo": "🔴"}, {"team": "Boca Juniors", "years": "1990-1991", "logo": "🔵"}, {"team": "Fiorentina", "years": "1991-2000", "logo": "🟣"}, {"team": "Roma", "years": "2000-2003", "logo": "🟡"}, {"team": "Inter", "years": "2003", "logo": "🔵"}, {"team": "Al-Arabi", "years": "2003-2005", "logo": "🟢"}], "nationality": "Arjantin", "position": "Forvet", "age": 55, "current_team": "Emekli", "difficulty": "easy"},
    {"name": "Javier Zanetti", "team_history": [{"team": "Talleres", "years": "1991-1993", "logo": "🔵"}, {"team": "Banfield", "years": "1993-1995", "logo": "🟢"}, {"team": "Inter", "years": "1995-2014", "logo": "🔵"}], "nationality": "Arjantin", "position": "Sağ Bek", "age": 50, "current_team": "Emekli", "difficulty": "easy"},
    {"name": "Juan Sebastián Verón", "team_history": [{"team": "Estudiantes", "years": "1993-1996", "logo": "🔴"}, {"team": "Boca Juniors", "years": "1996-1996", "logo": "🔵"}, {"team": "Sampdoria", "years": "1996-1999", "logo": "🔵"}, {"team": "Parma", "years": "1999-2001", "logo": "🟡"}, {"team": "Lazio", "years": "2000-2001", "logo": "🔵"}, {"team": "Manchester United", "years": "2001-2003", "logo": "🔴"}, {"team": "Chelsea", "years": "2003-2004", "logo": "🔵"}, {"team": "Inter", "years": "2004-2006", "logo": "🔵"}, {"team": "Estudiantes", "years": "2006-2014", "logo": "🔴"}], "nationality": "Arjantin", "position": "Orta Saha", "age": 49, "current_team": "Emekli", "difficulty": "medium"},
    {"name": "Juan Román Riquelme", "team_history": [{"team": "Argentinos Juniors", "years": "1995-1996", "logo": "🔴"}, {"team": "Boca Juniors", "years": "1996-2002", "logo": "🔵"}, {"team": "Barcelona", "years": "2002-2005", "logo": "🔵"}, {"team": "Villarreal", "years": "2003-2007 (Kiralık/Transfer)", "logo": "🟡"}, {"team": "Boca Juniors", "years": "2007-2014", "logo": "🔵"}, {"team": "Argentinos Juniors", "years": "2014-2015", "logo": "🔴"}], "nationality": "Arjantin", "position": "Orta Saha", "age": 46, "current_team": "Emekli", "difficulty": "medium"},
    {"name": "Sergio Agüero", "team_history": [{"team": "Independiente", "years": "2003-2006", "logo": "🔴"}, {"team": "Atlético Madrid", "years": "2006-2011", "logo": "🔴"}, {"team": "Manchester City", "years": "2011-2021", "logo": "🔵"}, {"team": "Barcelona", "years": "2021", "logo": "🔵"}], "nationality": "Arjantin", "position": "Forvet", "age": 36, "current_team": "Emekli", "difficulty": "easy"},
    {"name": "Carlos Tevez", "team_history": [{"team": "Boca Juniors", "years": "2001-2005", "logo": "🔵"}, {"team": "Corinthians", "years": "2005-2006", "logo": "⚫"}, {"team": "West Ham", "years": "2006-2007", "logo": "🟣"}, {"team": "Manchester United", "years": "2007-2009", "logo": "🔴"}, {"team": "Manchester City", "years": "2009-2013", "logo": "🔵"}, {"team": "Juventus", "years": "2013-2015", "logo": "⚫"}, {"team": "Boca Juniors", "years": "2015-2021", "logo": "🔵"}], "nationality": "Arjantin", "position": "Forvet", "age": 40, "current_team": "Emekli", "difficulty": "easy"},
    {"name": "Gonzalo Higuaín", "team_history": [{"team": "River Plate", "years": "2004-2007", "logo": "🔴"}, {"team": "Real Madrid", "years": "2007-2013", "logo": "⚪"}, {"team": "Napoli", "years": "2013-2016", "logo": "🔵"}, {"team": "Juventus", "years": "2016-2019", "logo": "⚫"}, {"team": "AC Milan", "years": "2018-2019 (Kiralık)", "logo": "🔴"}, {"team": "Chelsea", "years": "2019 (Kiralık)", "logo": "🔵"}, {"team": "Inter Miami", "years": "2020-2022", "logo": "🩷"}], "nationality": "Arjantin", "position": "Forvet", "age": 36, "current_team": "Emekli", "difficulty": "easy"},
    {"name": "Ángel Di María", "team_history": [{"team": "Rosario Central", "years": "2005-2007", "logo": "🔵"}, {"team": "Benfica", "years": "2007-2010", "logo": "🔴"}, {"team": "Real Madrid", "years": "2010-2014", "logo": "⚪"}, {"team": "Manchester United", "years": "2014-2015", "logo": "🔴"}, {"team": "Paris Saint-Germain", "years": "2015-2022", "logo": "🔵"}, {"team": "Juventus", "years": "2022-2023", "logo": "⚫"}, {"team": "Benfica", "years": "2023-", "logo": "🔴"}], "nationality": "Arjantin", "position": "Kanat", "age": 36, "current_team": "Benfica", "difficulty": "easy"},
    
    # ============ İTALYA EFSANELERİ ============
    {"name": "Paolo Maldini", "team_history": [{"team": "AC Milan", "years": "1984-2009", "logo": "🔴"}], "nationality": "İtalya", "position": "Sol Bek", "age": 56, "current_team": "Emekli", "difficulty": "easy"},
    {"name": "Franco Baresi", "team_history": [{"team": "AC Milan", "years": "1977-1997", "logo": "🔴"}], "nationality": "İtalya", "position": "Stoper", "age": 64, "current_team": "Emekli", "difficulty": "medium"},
    {"name": "Alessandro Del Piero", "team_history": [{"team": "Padova", "years": "1991-1993", "logo": "⚪"}, {"team": "Juventus", "years": "1993-2012", "logo": "⚫"}, {"team": "Sydney FC", "years": "2012-2014", "logo": "🔵"}, {"team": "Delhi Dynamos", "years": "2014", "logo": "🟠"}], "nationality": "İtalya", "position": "İkinci Forvet", "age": 49, "current_team": "Emekli", "difficulty": "easy"},
    {"name": "Francesco Totti", "team_history": [{"team": "Roma", "years": "1992-2017", "logo": "🟡"}], "nationality": "İtalya", "position": "İkinci Forvet", "age": 48, "current_team": "Emekli", "difficulty": "easy"},
    {"name": "Roberto Baggio", "team_history": [{"team": "Vicenza", "years": "1982-1985", "logo": "🔴"}, {"team": "Fiorentina", "years": "1985-1990", "logo": "🟣"}, {"team": "Juventus", "years": "1990-1995", "logo": "⚫"}, {"team": "AC Milan", "years": "1995-1997", "logo": "🔴"}, {"team": "Bologna", "years": "1997-1998", "logo": "🔴"}, {"team": "Inter", "years": "1998-2000", "logo": "🔵"}, {"team": "Brescia", "years": "2000-2004", "logo": "🔵"}], "nationality": "İtalya", "position": "İkinci Forvet", "age": 57, "current_team": "Emekli", "difficulty": "easy"},
    {"name": "Gianluigi Buffon", "team_history": [{"team": "Parma", "years": "1995-2001", "logo": "🟡"}, {"team": "Juventus", "years": "2001-2018", "logo": "⚫"}, {"team": "Paris Saint-Germain", "years": "2018-2019", "logo": "🔵"}, {"team": "Juventus", "years": "2019-2021", "logo": "⚫"}, {"team": "Parma", "years": "2021-2023", "logo": "🟡"}], "nationality": "İtalya", "position": "Kaleci", "age": 46, "current_team": "Emekli", "difficulty": "easy"},
    {"name": "Andrea Pirlo", "team_history": [{"team": "Brescia", "years": "1995-1998", "logo": "🔵"}, {"team": "Inter", "years": "1998-2001", "logo": "🔵"}, {"team": "Reggina", "years": "1999-2000 (Kiralık)", "logo": "🟣"}, {"team": "Brescia", "years": "2001", "logo": "🔵"}, {"team": "AC Milan", "years": "2001-2011", "logo": "🔴"}, {"team": "Juventus", "years": "2011-2015", "logo": "⚫"}, {"team": "New York City", "years": "2015-2017", "logo": "🔵"}], "nationality": "İtalya", "position": "Orta Saha", "age": 45, "current_team": "Emekli", "difficulty": "easy"},
    {"name": "Fabio Cannavaro", "team_history": [{"team": "Napoli", "years": "1992-1995", "logo": "🔵"}, {"team": "Parma", "years": "1995-2002", "logo": "🟡"}, {"team": "Inter", "years": "2002-2004", "logo": "🔵"}, {"team": "Juventus", "years": "2004-2006", "logo": "⚫"}, {"team": "Real Madrid", "years": "2006-2009", "logo": "⚪"}, {"team": "Juventus", "years": "2009-2010", "logo": "⚫"}, {"team": "Al-Ahli", "years": "2010-2011", "logo": "🟢"}], "nationality": "İtalya", "position": "Stoper", "age": 50, "current_team": "Emekli", "difficulty": "easy"},
    {"name": "Gianfranco Zola", "team_history": [{"team": "Nuorese", "years": "1984-1986", "logo": "🔵"}, {"team": "Torres", "years": "1986-1989", "logo": "🔴"}, {"team": "Napoli", "years": "1989-1993", "logo": "🔵"}, {"team": "Parma", "years": "1993-1996", "logo": "🟡"}, {"team": "Chelsea", "years": "1996-2003", "logo": "🔵"}, {"team": "Cagliari", "years": "2003-2005", "logo": "🔴"}], "nationality": "İtalya", "position": "Forvet", "age": 58, "current_team": "Emekli", "difficulty": "easy"},
    {"name": "Filippo Inzaghi", "team_history": [{"team": "Piacenza", "years": "1991-1995", "logo": "🔴"}, {"team": "Leffe", "years": "1992-1993 (Kiralık)", "logo": "🔵"}, {"team": "Verona", "years": "1993-1994 (Kiralık)", "logo": "🟡"}, {"team": "Parma", "years": "1995-1996", "logo": "🟡"}, {"team": "Atalanta", "years": "1996-1997", "logo": "🔵"}, {"team": "Juventus", "years": "1997-2001", "logo": "⚫"}, {"team": "AC Milan", "years": "2001-2012", "logo": "🔴"}], "nationality": "İtalya", "position": "Forvet", "age": 50, "current_team": "Emekli", "difficulty": "easy"},
    
    # ============ İSPANYA EFSANELERİ ============
    {"name": "Xavi Hernández", "team_history": [{"team": "Barcelona", "years": "1998-2015", "logo": "🔵"}, {"team": "Al-Sadd", "years": "2015-2019", "logo": "⚪"}], "nationality": "İspanya", "position": "Orta Saha", "age": 44, "current_team": "Emekli", "difficulty": "easy"},
    {"name": "Andrés Iniesta", "team_history": [{"team": "Barcelona", "years": "2002-2018", "logo": "🔵"}, {"team": "Vissel Kobe", "years": "2018-2023", "logo": "🔴"}, {"team": "Emirates Club", "years": "2023-", "logo": "🟢"}], "nationality": "İspanya", "position": "Orta Saha", "age": 40, "current_team": "Emirates Club", "difficulty": "easy"},
    {"name": "Fernando Torres", "team_history": [{"team": "Atlético Madrid", "years": "2001-2007", "logo": "🔴"}, {"team": "Liverpool", "years": "2007-2011", "logo": "🔴"}, {"team": "Chelsea", "years": "2011-2014", "logo": "🔵"}, {"team": "AC Milan", "years": "2014-2015 (Kiralık)", "logo": "🔴"}, {"team": "Atlético Madrid", "years": "2015-2018", "logo": "🔴"}, {"team": "Sagan Tosu", "years": "2018-2019", "logo": "🔵"}], "nationality": "İspanya", "position": "Forvet", "age": 40, "current_team": "Emekli", "difficulty": "easy"},
    {"name": "David Villa", "team_history": [{"team": "Sporting Gijón", "years": "2001-2003", "logo": "🔴"}, {"team": "Real Zaragoza", "years": "2003-2005", "logo": "🔵"}, {"team": "Valencia", "years": "2005-2010", "logo": "⚪"}, {"team": "Barcelona", "years": "2010-2013", "logo": "🔵"}, {"team": "Atlético Madrid", "years": "2013-2014", "logo": "🔴"}, {"team": "New York City", "years": "2014-2018", "logo": "🔵"}, {"team": "Vissel Kobe", "years": "2019", "logo": "🔴"}], "nationality": "İspanya", "position": "Forvet", "age": 42, "current_team": "Emekli", "difficulty": "easy"},
    {"name": "Raúl González", "team_history": [{"team": "Real Madrid", "years": "1994-2010", "logo": "⚪"}, {"team": "Schalke 04", "years": "2010-2012", "logo": "🔵"}, {"team": "Al-Sadd", "years": "2012-2014", "logo": "⚪"}, {"team": "New York Cosmos", "years": "2014-2015", "logo": "🟢"}], "nationality": "İspanya", "position": "Forvet", "age": 47, "current_team": "Emekli", "difficulty": "easy"},
    {"name": "Iker Casillas", "team_history": [{"team": "Real Madrid", "years": "1999-2015", "logo": "⚪"}, {"team": "Porto", "years": "2015-2020", "logo": "🔵"}], "nationality": "İspanya", "position": "Kaleci", "age": 43, "current_team": "Emekli", "difficulty": "easy"},
    {"name": "Carles Puyol", "team_history": [{"team": "Barcelona", "years": "1999-2014", "logo": "🔵"}], "nationality": "İspanya", "position": "Stoper", "age": 46, "current_team": "Emekli", "difficulty": "easy"},
    {"name": "Sergio Ramos", "team_history": [{"team": "Sevilla", "years": "2003-2005", "logo": "⚪"}, {"team": "Real Madrid", "years": "2005-2021", "logo": "⚪"}, {"team": "Paris Saint-Germain", "years": "2021-2023", "logo": "🔵"}, {"team": "Sevilla", "years": "2023-", "logo": "⚪"}], "nationality": "İspanya", "position": "Stoper", "age": 38, "current_team": "Sevilla", "difficulty": "easy"},
    {"name": "Gerard Piqué", "team_history": [{"team": "Barcelona", "years": "2002-2004", "logo": "🔵"}, {"team": "Manchester United", "years": "2004-2008", "logo": "🔴"}, {"team": "Real Zaragoza", "years": "2006-2007 (Kiralık)", "logo": "🔵"}, {"team": "Barcelona", "years": "2008-2022", "logo": "🔵"}], "nationality": "İspanya", "position": "Stoper", "age": 37, "current_team": "Emekli", "difficulty": "easy"},
    
    # ============ ALMANYA EFSANELERİ ============
    {"name": "Michael Ballack", "team_history": [{"team": "Chemnitzer FC", "years": "1995-1997", "logo": "🔵"}, {"team": "Kaiserslautern", "years": "1997-1999", "logo": "🔴"}, {"team": "Bayer Leverkusen", "years": "1999-2002", "logo": "🔴"}, {"team": "Bayern Münih", "years": "2002-2006", "logo": "🔴"}, {"team": "Chelsea", "years": "2006-2010", "logo": "🔵"}, {"team": "Bayer Leverkusen", "years": "2010-2012", "logo": "🔴"}], "nationality": "Almanya", "position": "Orta Saha", "age": 47, "current_team": "Emekli", "difficulty": "easy"},
    {"name": "Miroslav Klose", "team_history": [{"team": "Kaiserslautern", "years": "1999-2004", "logo": "🔴"}, {"team": "Werder Bremen", "years": "2004-2007", "logo": "🟢"}, {"team": "Bayern Münih", "years": "2007-2011", "logo": "🔴"}, {"team": "Lazio", "years": "2011-2016", "logo": "🔵"}], "nationality": "Almanya", "position": "Forvet", "age": 46, "current_team": "Emekli", "difficulty": "easy"},
    {"name": "Oliver Kahn", "team_history": [{"team": "Karlsruher SC", "years": "1987-1994", "logo": "🔵"}, {"team": "Bayern Münih", "years": "1994-2008", "logo": "🔴"}], "nationality": "Almanya", "position": "Kaleci", "age": 55, "current_team": "Emekli", "difficulty": "easy"},
    {"name": "Bastian Schweinsteiger", "team_history": [{"team": "Bayern Münih", "years": "2002-2015", "logo": "🔴"}, {"team": "Manchester United", "years": "2015-2017", "logo": "🔴"}, {"team": "Chicago Fire", "years": "2017-2019", "logo": "🔴"}], "nationality": "Almanya", "position": "Orta Saha", "age": 40, "current_team": "Emekli", "difficulty": "easy"},
    {"name": "Philipp Lahm", "team_history": [{"team": "Bayern Münih", "years": "2002-2017", "logo": "🔴"}, {"team": "Stuttgart", "years": "2003-2005 (Kiralık)", "logo": "⚪"}], "nationality": "Almanya", "position": "Sağ Bek", "age": 40, "current_team": "Emekli", "difficulty": "easy"},
    {"name": "Lothar Matthäus", "team_history": [{"team": "Borussia M'gladbach", "years": "1979-1984", "logo": "🟢"}, {"team": "Bayern Münih", "years": "1984-1988", "logo": "🔴"}, {"team": "Inter", "years": "1988-1992", "logo": "🔵"}, {"team": "Bayern Münih", "years": "1992-2000", "logo": "🔴"}, {"team": "New York MetroStars", "years": "2000", "logo": "🔴"}], "nationality": "Almanya", "position": "Orta Saha", "age": 63, "current_team": "Emekli", "difficulty": "medium"},
    {"name": "Per Mertesacker", "team_history": [{"team": "Hannover 96", "years": "2003-2006", "logo": "🔴"}, {"team": "Werder Bremen", "years": "2006-2011", "logo": "🟢"}, {"team": "Arsenal", "years": "2011-2018", "logo": "🔴"}], "nationality": "Almanya", "position": "Stoper", "age": 39, "current_team": "Emekli", "difficulty": "medium"},
    
    # ============ DİĞER ÜLKE EFSANELERİ ============
    {"name": "Didier Drogba", "team_history": [{"team": "Le Mans", "years": "2001-2002", "logo": "🟠"}, {"team": "Guingamp", "years": "2002-2003", "logo": "🔴"}, {"team": "Marsilya", "years": "2003-2004", "logo": "🔵"}, {"team": "Chelsea", "years": "2004-2012", "logo": "🔵"}, {"team": "Shanghai Shenhua", "years": "2012", "logo": "🔵"}, {"team": "Galatasaray", "years": "2013-2014", "logo": "🟡"}, {"team": "Chelsea", "years": "2014-2015", "logo": "🔵"}, {"team": "Montreal Impact", "years": "2015-2016", "logo": "🔵"}, {"team": "Phoenix Rising", "years": "2017-2018", "logo": "🔴"}], "nationality": "Fildişi Sahili", "position": "Forvet", "age": 46, "current_team": "Emekli", "difficulty": "easy"},
    {"name": "Samuel Eto'o", "team_history": [{"team": "Real Madrid", "years": "1997-2000", "logo": "⚪"}, {"team": "Leganés", "years": "1997-1998 (Kiralık)", "logo": "🔵"}, {"team": "Espanyol", "years": "1998-1999 (Kiralık)", "logo": "🔵"}, {"team": "Mallorca", "years": "1999-2004", "logo": "🔴"}, {"team": "Barcelona", "years": "2004-2009", "logo": "🔵"}, {"team": "Inter", "years": "2009-2011", "logo": "🔵"}, {"team": "Anzhi Makhachkala", "years": "2011-2013", "logo": "🟡"}, {"team": "Chelsea", "years": "2013-2014", "logo": "🔵"}, {"team": "Everton", "years": "2014", "logo": "🔵"}, {"team": "Sampdoria", "years": "2015", "logo": "🔵"}, {"team": "Antalyaspor", "years": "2015-2018", "logo": "🔴"}, {"team": "Konyaspor", "years": "2018-2019", "logo": "🟢"}, {"team": "Qatar SC", "years": "2019", "logo": "🟣"}], "nationality": "Kamerun", "position": "Forvet", "age": 43, "current_team": "Emekli", "difficulty": "easy"},
    {"name": "George Weah", "team_history": [{"team": "Mighty Barrolle", "years": "1985-1987", "logo": "🟢"}, {"team": "Invincible Eleven", "years": "1986-1988", "logo": "🔵"}, {"team": "Tonnerre Yaoundé", "years": "1988-1988", "logo": "🟡"}, {"team": "Monaco", "years": "1988-1992", "logo": "🔴"}, {"team": "Paris Saint-Germain", "years": "1992-1995", "logo": "🔵"}, {"team": "AC Milan", "years": "1995-1999", "logo": "🔴"}, {"team": "Chelsea", "years": "1999-2000", "logo": "🔵"}, {"team": "Manchester City", "years": "2000", "logo": "🔵"}, {"team": "Marsilya", "years": "2000-2001", "logo": "🔵"}, {"team": "Al-Jazira", "years": "2001-2003", "logo": "⚪"}], "nationality": "Liberya", "position": "Forvet", "age": 57, "current_team": "Emekli", "difficulty": "medium"},
    {"name": "Zlatan Ibrahimović", "team_history": [{"team": "Malmö FF", "years": "1999-2001", "logo": "🔵"}, {"team": "Ajax", "years": "2001-2004", "logo": "⚪"}, {"team": "Juventus", "years": "2004-2006", "logo": "⚫"}, {"team": "Inter", "years": "2006-2009", "logo": "🔵"}, {"team": "Barcelona", "years": "2009-2011", "logo": "🔵"}, {"team": "AC Milan", "years": "2010-2012 (Kiralık/Transfer)", "logo": "🔴"}, {"team": "Paris Saint-Germain", "years": "2012-2016", "logo": "🔵"}, {"team": "Manchester United", "years": "2016-2018", "logo": "🔴"}, {"team": "LA Galaxy", "years": "2018-2019", "logo": "🔵"}, {"team": "AC Milan", "years": "2020-2023", "logo": "🔴"}], "nationality": "İsveç", "position": "Forvet", "age": 42, "current_team": "Emekli", "difficulty": "easy"},
    {"name": "Henrik Larsson", "team_history": [{"team": "Högaborgs BK", "years": "1988-1992", "logo": "🟢"}, {"team": "Helsingborgs IF", "years": "1992-1993", "logo": "🔴"}, {"team": "Feyenoord", "years": "1993-1997", "logo": "🔴"}, {"team": "Celtic", "years": "1997-2004", "logo": "🟢"}, {"team": "Barcelona", "years": "2004-2006", "logo": "🔵"}, {"team": "Helsingborgs IF", "years": "2006-2009", "logo": "🔴"}, {"team": "Manchester United", "years": "2007 (Kiralık)", "logo": "🔴"}], "nationality": "İsveç", "position": "Forvet", "age": 52, "current_team": "Emekli", "difficulty": "easy"},
    {"name": "Gheorghe Hagi", "team_history": [{"team": "Farul Constanța", "years": "1982-1983", "logo": "🔵"}, {"team": "Sportul Studențesc", "years": "1983-1987", "logo": "🔴"}, {"team": "Steaua București", "years": "1987-1990", "logo": "🔴"}, {"team": "Real Madrid", "years": "1990-1992", "logo": "⚪"}, {"team": "Brescia", "years": "1992-1994", "logo": "🔵"}, {"team": "Barcelona", "years": "1994-1996", "logo": "🔵"}, {"team": "Galatasaray", "years": "1996-2001", "logo": "🟡"}], "nationality": "Romanya", "position": "Orta Saha", "age": 59, "current_team": "Emekli", "difficulty": "easy"},
    {"name": "Hristo Stoichkov", "team_history": [{"team": "CSKA Sofia", "years": "1984-1990", "logo": "🔴"}, {"team": "Barcelona", "years": "1990-1995", "logo": "🔵"}, {"team": "Parma", "years": "1995-1996", "logo": "🟡"}, {"team": "Barcelona", "years": "1996-1998", "logo": "🔵"}, {"team": "CSKA Sofia", "years": "1998", "logo": "🔴"}, {"team": "Al-Nasr", "years": "1998-1999", "logo": "🔵"}, {"team": "Kashiwa Reysol", "years": "1999", "logo": "🟡"}, {"team": "Chicago Fire", "years": "2000-2002", "logo": "🔴"}, {"team": "DC United", "years": "2003", "logo": "⚫"}], "nationality": "Bulgaristan", "position": "Sol Kanat", "age": 58, "current_team": "Emekli", "difficulty": "medium"},
    {"name": "Davor Šuker", "team_history": [{"team": "Osijek", "years": "1984-1989", "logo": "🔵"}, {"team": "Dinamo Zagreb", "years": "1989-1991", "logo": "🔵"}, {"team": "Sevilla", "years": "1991-1996", "logo": "⚪"}, {"team": "Real Madrid", "years": "1996-1999", "logo": "⚪"}, {"team": "Arsenal", "years": "1999-2000", "logo": "🔴"}, {"team": "West Ham", "years": "2000-2001", "logo": "🟣"}, {"team": "1860 Munich", "years": "2003", "logo": "🔵"}], "nationality": "Hırvatistan", "position": "Forvet", "age": 56, "current_team": "Emekli", "difficulty": "medium"},
    {"name": "Dimitar Berbatov", "team_history": [{"team": "CSKA Sofia", "years": "1998-2001", "logo": "🔴"}, {"team": "Bayer Leverkusen", "years": "2001-2006", "logo": "🔴"}, {"team": "Tottenham", "years": "2006-2008", "logo": "⚪"}, {"team": "Manchester United", "years": "2008-2012", "logo": "🔴"}, {"team": "Fulham", "years": "2012-2014", "logo": "⚪"}, {"team": "Monaco", "years": "2014-2015", "logo": "🔴"}, {"team": "PAOK", "years": "2015-2016", "logo": "⚫"}, {"team": "Kerala Blasters", "years": "2017-2018", "logo": "🟡"}], "nationality": "Bulgaristan", "position": "Forvet", "age": 43, "current_team": "Emekli", "difficulty": "easy"},
    {"name": "Andriy Shevchenko", "team_history": [{"team": "Dynamo Kyiv", "years": "1994-1999", "logo": "⚪"}, {"team": "AC Milan", "years": "1999-2006", "logo": "🔴"}, {"team": "Chelsea", "years": "2006-2009", "logo": "🔵"}, {"team": "AC Milan", "years": "2008-2009 (Kiralık)", "logo": "🔴"}, {"team": "Dynamo Kyiv", "years": "2009-2012", "logo": "⚪"}], "nationality": "Ukrayna", "position": "Forvet", "age": 48, "current_team": "Emekli", "difficulty": "easy"},
]
