"""Ligue 1 Players"""

LIGUE_1_PLAYERS = [
    # ============ PSG ============
    {"name": "Ousmane Dembélé", "team_history": [{"team": "Rennes", "years": "2015-2016", "logo": "🔴"}, {"team": "Borussia Dortmund", "years": "2016-2017", "logo": "🟡"}, {"team": "Barcelona", "years": "2017-2023", "logo": "🔵"}, {"team": "Paris Saint-Germain", "years": "2023-", "logo": "🔵"}], "nationality": "Fransa", "position": "Sağ Kanat", "age": 27, "current_team": "Paris Saint-Germain", "difficulty": "easy"},
    {"name": "Achraf Hakimi", "team_history": [{"team": "Real Madrid", "years": "2016-2020", "logo": "⚪"}, {"team": "Borussia Dortmund", "years": "2018-2020 (Kiralık)", "logo": "🟡"}, {"team": "Inter", "years": "2020-2021", "logo": "🔵"}, {"team": "Paris Saint-Germain", "years": "2021-", "logo": "🔵"}], "nationality": "Fas", "position": "Sağ Bek", "age": 25, "current_team": "Paris Saint-Germain", "difficulty": "easy"},
    {"name": "Gianluigi Donnarumma", "team_history": [{"team": "AC Milan", "years": "2015-2021", "logo": "🔴"}, {"team": "Paris Saint-Germain", "years": "2021-", "logo": "🔵"}], "nationality": "İtalya", "position": "Kaleci", "age": 25, "current_team": "Paris Saint-Germain", "difficulty": "easy"},
    {"name": "Marquinhos", "team_history": [{"team": "Corinthians", "years": "2011-2012", "logo": "⚫"}, {"team": "Roma", "years": "2012-2013", "logo": "🟡"}, {"team": "Paris Saint-Germain", "years": "2013-", "logo": "🔵"}], "nationality": "Brezilya", "position": "Stoper", "age": 30, "current_team": "Paris Saint-Germain", "difficulty": "easy"},
    {"name": "Bradley Barcola", "team_history": [{"team": "Lyon", "years": "2021-2023", "logo": "🔵"}, {"team": "Paris Saint-Germain", "years": "2023-", "logo": "🔵"}], "nationality": "Fransa", "position": "Sol Kanat", "age": 22, "current_team": "Paris Saint-Germain", "difficulty": "easy"},
    {"name": "Randal Kolo Muani", "team_history": [{"team": "Nantes", "years": "2018-2022", "logo": "🟡"}, {"team": "Eintracht Frankfurt", "years": "2022-2023", "logo": "⚫"}, {"team": "Paris Saint-Germain", "years": "2023-", "logo": "🔵"}], "nationality": "Fransa", "position": "Forvet", "age": 25, "current_team": "Paris Saint-Germain", "difficulty": "easy"},
    {"name": "Vitinha", "team_history": [{"team": "Porto", "years": "2018-2022", "logo": "🔵"}, {"team": "Wolverhampton", "years": "2020-2021 (Kiralık)", "logo": "🟠"}, {"team": "Paris Saint-Germain", "years": "2022-", "logo": "🔵"}], "nationality": "Portekiz", "position": "Orta Saha", "age": 24, "current_team": "Paris Saint-Germain", "difficulty": "medium"},
    {"name": "Warren Zaïre-Emery", "team_history": [{"team": "Paris Saint-Germain", "years": "2022-", "logo": "🔵"}], "nationality": "Fransa", "position": "Orta Saha", "age": 18, "current_team": "Paris Saint-Germain", "difficulty": "medium"},
    {"name": "Fabián Ruiz", "team_history": [{"team": "Real Betis", "years": "2015-2018", "logo": "🟢"}, {"team": "Napoli", "years": "2018-2022", "logo": "🔵"}, {"team": "Paris Saint-Germain", "years": "2022-", "logo": "🔵"}], "nationality": "İspanya", "position": "Orta Saha", "age": 28, "current_team": "Paris Saint-Germain", "difficulty": "medium"},
    {"name": "Lucas Hernández", "team_history": [{"team": "Atlético Madrid", "years": "2014-2019", "logo": "🔴"}, {"team": "Bayern Münih", "years": "2019-2023", "logo": "🔴"}, {"team": "Paris Saint-Germain", "years": "2023-", "logo": "🔵"}], "nationality": "Fransa", "position": "Stoper", "age": 28, "current_team": "Paris Saint-Germain", "difficulty": "easy"},
    {"name": "Nuno Mendes", "team_history": [{"team": "Sporting CP", "years": "2019-2021", "logo": "🟢"}, {"team": "Paris Saint-Germain", "years": "2021-", "logo": "🔵"}], "nationality": "Portekiz", "position": "Sol Bek", "age": 22, "current_team": "Paris Saint-Germain", "difficulty": "medium"},
    {"name": "Milan Škriniar", "team_history": [{"team": "Sampdoria", "years": "2016-2017", "logo": "🔵"}, {"team": "Inter", "years": "2017-2023", "logo": "🔵"}, {"team": "Paris Saint-Germain", "years": "2023-", "logo": "🔵"}], "nationality": "Slovakya", "position": "Stoper", "age": 29, "current_team": "Paris Saint-Germain", "difficulty": "easy"},
    {"name": "Lee Kang-in", "team_history": [{"team": "Valencia", "years": "2018-2023", "logo": "⚪"}, {"team": "Mallorca", "years": "2022-2023 (Kiralık)", "logo": "🔴"}, {"team": "Paris Saint-Germain", "years": "2023-", "logo": "🔵"}], "nationality": "Güney Kore", "position": "Orta Saha", "age": 23, "current_team": "Paris Saint-Germain", "difficulty": "medium"},
    {"name": "Marco Asensio", "team_history": [{"team": "Mallorca", "years": "2014-2015", "logo": "🔴"}, {"team": "Real Madrid", "years": "2015-2023", "logo": "⚪"}, {"team": "Espanyol", "years": "2015-2016 (Kiralık)", "logo": "🔵"}, {"team": "Paris Saint-Germain", "years": "2023-", "logo": "🔵"}], "nationality": "İspanya", "position": "Kanat", "age": 28, "current_team": "Paris Saint-Germain", "difficulty": "easy"},
    {"name": "Gonçalo Ramos", "team_history": [{"team": "Benfica", "years": "2020-2023", "logo": "🔴"}, {"team": "Paris Saint-Germain", "years": "2023-", "logo": "🔵"}], "nationality": "Portekiz", "position": "Forvet", "age": 23, "current_team": "Paris Saint-Germain", "difficulty": "medium"},
    {"name": "João Neves", "team_history": [{"team": "Benfica", "years": "2021-2024", "logo": "🔴"}, {"team": "Paris Saint-Germain", "years": "2024-", "logo": "🔵"}], "nationality": "Portekiz", "position": "Orta Saha", "age": 19, "current_team": "Paris Saint-Germain", "difficulty": "easy"},
    {"name": "Désiré Doué", "team_history": [{"team": "Rennes", "years": "2021-2024", "logo": "🔴"}, {"team": "Paris Saint-Germain", "years": "2024-", "logo": "🔵"}], "nationality": "Fransa", "position": "Kanat", "age": 19, "current_team": "Paris Saint-Germain", "difficulty": "medium"},
    {"name": "Willian Pacho", "team_history": [{"team": "Independiente del Valle", "years": "2019-2022", "logo": "⚫"}, {"team": "Royal Antwerp", "years": "2022-2023", "logo": "🔴"}, {"team": "Eintracht Frankfurt", "years": "2023-2024", "logo": "⚫"}, {"team": "Paris Saint-Germain", "years": "2024-", "logo": "🔵"}], "nationality": "Ekvador", "position": "Stoper", "age": 22, "current_team": "Paris Saint-Germain", "difficulty": "medium"},
    
    # ============ MARSILYA ============
    {"name": "Mason Greenwood", "team_history": [{"team": "Manchester United", "years": "2018-2023", "logo": "🔴"}, {"team": "Getafe", "years": "2023-2024", "logo": "🔵"}, {"team": "Marsilya", "years": "2024-", "logo": "🔵"}], "nationality": "İngiltere", "position": "Forvet", "age": 23, "current_team": "Marsilya", "difficulty": "easy"},
    {"name": "Pierre-Emerick Aubameyang", "team_history": [{"team": "AC Milan", "years": "2008-2011", "logo": "🔴"}, {"team": "Monaco", "years": "2011-2012", "logo": "🔴"}, {"team": "Saint-Étienne", "years": "2011-2013 (Kiralık)", "logo": "🟢"}, {"team": "Borussia Dortmund", "years": "2013-2018", "logo": "🟡"}, {"team": "Arsenal", "years": "2018-2022", "logo": "🔴"}, {"team": "Barcelona", "years": "2022-2023", "logo": "🔵"}, {"team": "Chelsea", "years": "2022-2023", "logo": "🔵"}, {"team": "Marsilya", "years": "2023-2024", "logo": "🔵"}, {"team": "Al-Qadsiah", "years": "2024-", "logo": "🟡"}], "nationality": "Gabon", "position": "Forvet", "age": 35, "current_team": "Al-Qadsiah", "difficulty": "easy"},
    {"name": "Adrien Rabiot", "team_history": [{"team": "PSG", "years": "2012-2019", "logo": "🔵"}, {"team": "Juventus", "years": "2019-2024", "logo": "⚫"}, {"team": "Marsilya", "years": "2024-", "logo": "🔵"}], "nationality": "Fransa", "position": "Orta Saha", "age": 29, "current_team": "Marsilya", "difficulty": "easy"},
    {"name": "Amine Harit", "team_history": [{"team": "Nantes", "years": "2015-2017", "logo": "🟡"}, {"team": "Schalke 04", "years": "2017-2022", "logo": "🔵"}, {"team": "Marsilya", "years": "2021-", "logo": "🔵"}], "nationality": "Fas", "position": "Orta Saha", "age": 27, "current_team": "Marsilya", "difficulty": "medium"},
    {"name": "Quentin Merlin", "team_history": [{"team": "Nantes", "years": "2020-2024", "logo": "🟡"}, {"team": "Marsilya", "years": "2024-", "logo": "🔵"}], "nationality": "Fransa", "position": "Sol Bek", "age": 22, "current_team": "Marsilya", "difficulty": "medium"},
    {"name": "Leonardo Balerdi", "team_history": [{"team": "Boca Juniors", "years": "2016-2019", "logo": "🔵"}, {"team": "Borussia Dortmund", "years": "2019-2021", "logo": "🟡"}, {"team": "Marsilya", "years": "2021-", "logo": "🔵"}], "nationality": "Arjantin", "position": "Stoper", "age": 25, "current_team": "Marsilya", "difficulty": "medium"},
    {"name": "Geoffrey Kondogbia", "team_history": [{"team": "Lens", "years": "2011-2013", "logo": "🔴"}, {"team": "Sevilla", "years": "2013-2015", "logo": "⚪"}, {"team": "Monaco", "years": "2013-2015", "logo": "🔴"}, {"team": "Inter", "years": "2015-2017", "logo": "🔵"}, {"team": "Valencia", "years": "2017-2020", "logo": "⚪"}, {"team": "Atlético Madrid", "years": "2020-2024", "logo": "🔴"}, {"team": "Marsilya", "years": "2024-", "logo": "🔵"}], "nationality": "Orta Afrika Cumhuriyeti", "position": "Orta Saha", "age": 31, "current_team": "Marsilya", "difficulty": "medium"},
    
    # ============ MONACO ============
    {"name": "Wissam Ben Yedder", "team_history": [{"team": "Toulouse", "years": "2010-2016", "logo": "🟣"}, {"team": "Sevilla", "years": "2016-2019", "logo": "⚪"}, {"team": "Monaco", "years": "2019-2024", "logo": "🔴"}], "nationality": "Fransa", "position": "Forvet", "age": 34, "current_team": "Serbest", "difficulty": "easy"},
    {"name": "Aleksandr Golovin", "team_history": [{"team": "CSKA Moscow", "years": "2015-2018", "logo": "🔴"}, {"team": "Monaco", "years": "2018-", "logo": "🔴"}], "nationality": "Rusya", "position": "Orta Saha", "age": 28, "current_team": "Monaco", "difficulty": "medium"},
    {"name": "Takumi Minamino", "team_history": [{"team": "Cerezo Osaka", "years": "2013-2015", "logo": "🟣"}, {"team": "Red Bull Salzburg", "years": "2015-2020", "logo": "🔴"}, {"team": "Liverpool", "years": "2020-2022", "logo": "🔴"}, {"team": "Southampton", "years": "2021-2022 (Kiralık)", "logo": "🔴"}, {"team": "Monaco", "years": "2022-", "logo": "🔴"}], "nationality": "Japonya", "position": "Orta Saha", "age": 29, "current_team": "Monaco", "difficulty": "easy"},
    {"name": "Denis Zakaria", "team_history": [{"team": "Young Boys", "years": "2015-2017", "logo": "🟡"}, {"team": "Borussia M'gladbach", "years": "2017-2022", "logo": "🟢"}, {"team": "Juventus", "years": "2022-2023", "logo": "⚫"}, {"team": "Chelsea", "years": "2022-2023 (Kiralık)", "logo": "🔵"}, {"team": "Monaco", "years": "2023-", "logo": "🔴"}], "nationality": "İsviçre", "position": "Orta Saha", "age": 27, "current_team": "Monaco", "difficulty": "medium"},
    {"name": "Breel Embolo", "team_history": [{"team": "Basel", "years": "2014-2016", "logo": "🔴"}, {"team": "Schalke 04", "years": "2016-2019", "logo": "🔵"}, {"team": "Borussia M'gladbach", "years": "2019-2022", "logo": "🟢"}, {"team": "Monaco", "years": "2022-", "logo": "🔴"}], "nationality": "İsviçre", "position": "Forvet", "age": 27, "current_team": "Monaco", "difficulty": "medium"},
    {"name": "Youssouf Fofana", "team_history": [{"team": "Strasbourg", "years": "2017-2020", "logo": "🔵"}, {"team": "Monaco", "years": "2020-2024", "logo": "🔴"}, {"team": "AC Milan", "years": "2024-", "logo": "🔴"}], "nationality": "Fransa", "position": "Orta Saha", "age": 25, "current_team": "AC Milan", "difficulty": "medium"},
    {"name": "Eliesse Ben Seghir", "team_history": [{"team": "Monaco", "years": "2022-", "logo": "🔴"}], "nationality": "Fas", "position": "Kanat", "age": 19, "current_team": "Monaco", "difficulty": "medium"},
    {"name": "Lamine Camara", "team_history": [{"team": "Metz", "years": "2022-2024", "logo": "🟤"}, {"team": "Monaco", "years": "2024-", "logo": "🔴"}], "nationality": "Senegal", "position": "Orta Saha", "age": 20, "current_team": "Monaco", "difficulty": "medium"},
    {"name": "George Ilenikhena", "team_history": [{"team": "Royal Antwerp", "years": "2022-2024", "logo": "🔴"}, {"team": "Monaco", "years": "2024-", "logo": "🔴"}], "nationality": "Nijerya", "position": "Forvet", "age": 18, "current_team": "Monaco", "difficulty": "medium"},
    
    # ============ LILLE ============
    {"name": "Jonathan David", "team_history": [{"team": "Gent", "years": "2018-2020", "logo": "🔵"}, {"team": "Lille", "years": "2020-", "logo": "🔴"}], "nationality": "Kanada", "position": "Forvet", "age": 24, "current_team": "Lille", "difficulty": "easy"},
    {"name": "Rémy Cabella", "team_history": [{"team": "Montpellier", "years": "2009-2014", "logo": "🟠"}, {"team": "Newcastle", "years": "2014-2016", "logo": "⚫"}, {"team": "Marsilya", "years": "2015-2017 (Kiralık)", "logo": "🔵"}, {"team": "Saint-Étienne", "years": "2017-2020", "logo": "🟢"}, {"team": "Krasnodar", "years": "2020-2022", "logo": "🟢"}, {"team": "Montpellier", "years": "2022-2024", "logo": "🟠"}, {"team": "Lille", "years": "2024-", "logo": "🔴"}], "nationality": "Fransa", "position": "Orta Saha", "age": 34, "current_team": "Lille", "difficulty": "medium"},
    {"name": "Edon Zhegrova", "team_history": [{"team": "Genk", "years": "2018-2022", "logo": "🔵"}, {"team": "Basel", "years": "2020-2022 (Kiralık)", "logo": "🔴"}, {"team": "Lille", "years": "2022-", "logo": "🔴"}], "nationality": "Kosova", "position": "Kanat", "age": 25, "current_team": "Lille", "difficulty": "medium"},
    {"name": "André", "team_history": [{"team": "Grêmio", "years": "2016-2017", "logo": "🔵"}, {"team": "Corinthians", "years": "2017-2018", "logo": "⚫"}, {"team": "Sport Recife", "years": "2018-2019", "logo": "🔴"}, {"team": "Fluminense", "years": "2019-2021", "logo": "🟣"}, {"team": "Lille", "years": "2021-", "logo": "🔴"}], "nationality": "Brezilya", "position": "Orta Saha", "age": 24, "current_team": "Lille", "difficulty": "medium"},
    {"name": "Lucas Chevalier", "team_history": [{"team": "Lille", "years": "2021-", "logo": "🔴"}], "nationality": "Fransa", "position": "Kaleci", "age": 22, "current_team": "Lille", "difficulty": "medium"},
    {"name": "Bafodé Diakité", "team_history": [{"team": "Toulouse", "years": "2019-2021", "logo": "🟣"}, {"team": "Lille", "years": "2021-", "logo": "🔴"}], "nationality": "Fransa", "position": "Stoper", "age": 23, "current_team": "Lille", "difficulty": "medium"},
    {"name": "Angel Gomes", "team_history": [{"team": "Manchester United", "years": "2017-2020", "logo": "🔴"}, {"team": "Lille", "years": "2020-", "logo": "🔴"}], "nationality": "İngiltere", "position": "Orta Saha", "age": 24, "current_team": "Lille", "difficulty": "medium"},
    
    # ============ LYON ============
    {"name": "Alexandre Lacazette", "team_history": [{"team": "Lyon", "years": "2010-2017", "logo": "🔵"}, {"team": "Arsenal", "years": "2017-2022", "logo": "🔴"}, {"team": "Lyon", "years": "2022-", "logo": "🔵"}], "nationality": "Fransa", "position": "Forvet", "age": 33, "current_team": "Lyon", "difficulty": "easy"},
    {"name": "Rayan Cherki", "team_history": [{"team": "Lyon", "years": "2019-", "logo": "🔵"}], "nationality": "Fransa", "position": "Kanat", "age": 21, "current_team": "Lyon", "difficulty": "easy"},
    {"name": "Corentin Tolisso", "team_history": [{"team": "Lyon", "years": "2013-2017", "logo": "🔵"}, {"team": "Bayern Münih", "years": "2017-2022", "logo": "🔴"}, {"team": "Lyon", "years": "2022-", "logo": "🔵"}], "nationality": "Fransa", "position": "Orta Saha", "age": 30, "current_team": "Lyon", "difficulty": "easy"},
    {"name": "Nicolas Tagliafico", "team_history": [{"team": "Banfield", "years": "2011-2014", "logo": "🟢"}, {"team": "Independiente", "years": "2014-2018", "logo": "🔴"}, {"team": "Ajax", "years": "2018-2022", "logo": "⚪"}, {"team": "Lyon", "years": "2022-", "logo": "🔵"}], "nationality": "Arjantin", "position": "Sol Bek", "age": 32, "current_team": "Lyon", "difficulty": "medium"},
    {"name": "Moussa Niakhaté", "team_history": [{"team": "Valenciennes", "years": "2015-2017", "logo": "🔴"}, {"team": "Metz", "years": "2017-2018", "logo": "🟤"}, {"team": "Mainz 05", "years": "2018-2022", "logo": "🔴"}, {"team": "Nottingham Forest", "years": "2022-2024", "logo": "🔴"}, {"team": "Lyon", "years": "2024-", "logo": "🔵"}], "nationality": "Senegal", "position": "Stoper", "age": 28, "current_team": "Lyon", "difficulty": "medium"},
    {"name": "Malick Fofana", "team_history": [{"team": "La Gantoise", "years": "2022-2024", "logo": "🔵"}, {"team": "Lyon", "years": "2024-", "logo": "🔵"}], "nationality": "Belçika", "position": "Kanat", "age": 19, "current_team": "Lyon", "difficulty": "medium"},
    {"name": "Ernest Nuamah", "team_history": [{"team": "Nordsjaelland", "years": "2021-2023", "logo": "🔴"}, {"team": "Lyon", "years": "2023-", "logo": "🔵"}], "nationality": "Gana", "position": "Kanat", "age": 20, "current_team": "Lyon", "difficulty": "medium"},
    {"name": "Maxence Caqueret", "team_history": [{"team": "Lyon", "years": "2019-", "logo": "🔵"}], "nationality": "Fransa", "position": "Orta Saha", "age": 24, "current_team": "Lyon", "difficulty": "medium"},
    
    # ============ LENS ============
    {"name": "Elye Wahi", "team_history": [{"team": "Montpellier", "years": "2020-2023", "logo": "🟠"}, {"team": "Lens", "years": "2023-2024", "logo": "🔴"}, {"team": "Marsilya", "years": "2024-", "logo": "🔵"}], "nationality": "Fransa", "position": "Forvet", "age": 21, "current_team": "Marsilya", "difficulty": "medium"},
    {"name": "Florian Sotoca", "team_history": [{"team": "Grenoble", "years": "2017-2019", "logo": "🔵"}, {"team": "Lens", "years": "2019-", "logo": "🔴"}], "nationality": "Fransa", "position": "Forvet", "age": 33, "current_team": "Lens", "difficulty": "medium"},
    {"name": "Brice Samba", "team_history": [{"team": "Marseille", "years": "2013-2017", "logo": "🔵"}, {"team": "Nancy", "years": "2017-2017 (Kiralık)", "logo": "🔴"}, {"team": "Caen", "years": "2017-2019", "logo": "🔴"}, {"team": "Nottingham Forest", "years": "2019-2023", "logo": "🔴"}, {"team": "Lens", "years": "2023-", "logo": "🔴"}], "nationality": "Fransa", "position": "Kaleci", "age": 30, "current_team": "Lens", "difficulty": "medium"},
    {"name": "Kevin Danso", "team_history": [{"team": "Southampton", "years": "2018-2019", "logo": "🔴"}, {"team": "Augsburg", "years": "2019-2020", "logo": "🔴"}, {"team": "Fortuna Düsseldorf", "years": "2020 (Kiralık)", "logo": "🔴"}, {"team": "Lens", "years": "2020-", "logo": "🔴"}], "nationality": "Avusturya", "position": "Stoper", "age": 25, "current_team": "Lens", "difficulty": "medium"},
    {"name": "Abdukodir Khusanov", "team_history": [{"team": "Energetik-BGU", "years": "2020-2023", "logo": "🔵"}, {"team": "Lens", "years": "2023-", "logo": "🔴"}], "nationality": "Özbekistan", "position": "Stoper", "age": 20, "current_team": "Lens", "difficulty": "medium"},
    
    # ============ NICE ============
    {"name": "Evann Guessand", "team_history": [{"team": "Nice", "years": "2020-", "logo": "🔴"}], "nationality": "Fildişi Sahili", "position": "Forvet", "age": 23, "current_team": "Nice", "difficulty": "medium"},
    {"name": "Jeremie Boga", "team_history": [{"team": "Chelsea", "years": "2014-2018", "logo": "🔵"}, {"team": "Birmingham City", "years": "2017-2018 (Kiralık)", "logo": "🔵"}, {"team": "Granada", "years": "2017 (Kiralık)", "logo": "🔴"}, {"team": "Sassuolo", "years": "2018-2022", "logo": "🟢"}, {"team": "Atalanta", "years": "2022-2023", "logo": "🔵"}, {"team": "Nice", "years": "2023-", "logo": "🔴"}], "nationality": "Fildişi Sahili", "position": "Kanat", "age": 27, "current_team": "Nice", "difficulty": "medium"},
    {"name": "Marcin Bułka", "team_history": [{"team": "Chelsea", "years": "2016-2019", "logo": "🔵"}, {"team": "PSG", "years": "2019-2021", "logo": "🔵"}, {"team": "Cartagena", "years": "2020-2021 (Kiralık)", "logo": "⚫"}, {"team": "Nice", "years": "2021-", "logo": "🔴"}], "nationality": "Polonya", "position": "Kaleci", "age": 25, "current_team": "Nice", "difficulty": "medium"},
    {"name": "Youssouf Ndayishimiye", "team_history": [{"team": "Cercle Brugge", "years": "2019-2022", "logo": "🟢"}, {"team": "Union St. Gilloise", "years": "2021-2022", "logo": "🔵"}, {"team": "Burnley", "years": "2022-2023", "logo": "🔴"}, {"team": "Nice", "years": "2023-", "logo": "🔴"}], "nationality": "Burundi", "position": "Stoper", "age": 25, "current_team": "Nice", "difficulty": "hard"},
    
    # ============ RENNES ============
    {"name": "Arnaud Kalimuendo", "team_history": [{"team": "PSG", "years": "2019-2022", "logo": "🔵"}, {"team": "Lens", "years": "2020-2022 (Kiralık)", "logo": "🔴"}, {"team": "Rennes", "years": "2022-", "logo": "🔴"}], "nationality": "Fransa", "position": "Forvet", "age": 22, "current_team": "Rennes", "difficulty": "medium"},
    {"name": "Ludovic Blas", "team_history": [{"team": "Guingamp", "years": "2015-2017", "logo": "🔴"}, {"team": "Nantes", "years": "2019-2023", "logo": "🟡"}, {"team": "Rennes", "years": "2023-", "logo": "🔴"}], "nationality": "Fransa", "position": "Orta Saha", "age": 27, "current_team": "Rennes", "difficulty": "medium"},
    {"name": "Steve Mandanda", "team_history": [{"team": "Le Havre", "years": "2005-2007", "logo": "🔵"}, {"team": "Marsilya", "years": "2007-2016", "logo": "🔵"}, {"team": "Crystal Palace", "years": "2016-2017", "logo": "🔴"}, {"team": "Marsilya", "years": "2017-2022", "logo": "🔵"}, {"team": "Rennes", "years": "2022-", "logo": "🔴"}], "nationality": "Fransa", "position": "Kaleci", "age": 39, "current_team": "Rennes", "difficulty": "easy"},
    {"name": "Christopher Wooh", "team_history": [{"team": "Nancy", "years": "2019-2021", "logo": "🔴"}, {"team": "Lens", "years": "2021-2022", "logo": "🔴"}, {"team": "Rennes", "years": "2022-", "logo": "🔴"}], "nationality": "Kamerun", "position": "Stoper", "age": 23, "current_team": "Rennes", "difficulty": "medium"},
    
    # ============ STRASBOURG ============
    {"name": "Habib Diallo", "team_history": [{"team": "Metz", "years": "2016-2020", "logo": "🟤"}, {"team": "Strasbourg", "years": "2020-2022", "logo": "🔵"}, {"team": "Al-Shabab", "years": "2022-2023", "logo": "⚪"}, {"team": "Strasbourg", "years": "2023-", "logo": "🔵"}], "nationality": "Senegal", "position": "Forvet", "age": 29, "current_team": "Strasbourg", "difficulty": "medium"},
    {"name": "Emanuel Emegha", "team_history": [{"team": "Sparta Rotterdam", "years": "2020-2022", "logo": "🔴"}, {"team": "Sturm Graz", "years": "2022-2023", "logo": "⚫"}, {"team": "Strasbourg", "years": "2023-", "logo": "🔵"}], "nationality": "Hollanda", "position": "Forvet", "age": 22, "current_team": "Strasbourg", "difficulty": "medium"},
    
    # ============ BREST ============
    {"name": "Martin Satriano", "team_history": [{"team": "Inter", "years": "2020-", "logo": "🔵"}, {"team": "Brest", "years": "2021-2022 (Kiralık)", "logo": "🔴"}, {"team": "Empoli", "years": "2022-2023 (Kiralık)", "logo": "🔵"}, {"team": "Brest", "years": "2023-", "logo": "🔴"}], "nationality": "Uruguay", "position": "Forvet", "age": 23, "current_team": "Brest", "difficulty": "medium"},
    {"name": "Mahdi Camara", "team_history": [{"team": "Saint-Étienne", "years": "2018-2023", "logo": "🟢"}, {"team": "Brest", "years": "2023-", "logo": "🔴"}], "nationality": "Fransa", "position": "Orta Saha", "age": 26, "current_team": "Brest", "difficulty": "medium"},
    {"name": "Pierre Lees-Melou", "team_history": [{"team": "Dijon", "years": "2014-2017", "logo": "🔴"}, {"team": "Nice", "years": "2017-2021", "logo": "🔴"}, {"team": "Norwich City", "years": "2021-2022", "logo": "🟡"}, {"team": "Brest", "years": "2022-", "logo": "🔴"}], "nationality": "Fransa", "position": "Orta Saha", "age": 31, "current_team": "Brest", "difficulty": "medium"},
    {"name": "Hugo Magnetti", "team_history": [{"team": "Monaco", "years": "2018-2020", "logo": "🔴"}, {"team": "Brest", "years": "2020-", "logo": "🔴"}], "nationality": "Fransa", "position": "Orta Saha", "age": 26, "current_team": "Brest", "difficulty": "hard"},
]
