"""Serie A Players"""

SERIE_A_PLAYERS = [
    # ============ INTER ============
    {"name": "Lautaro Martínez", "team_history": [{"team": "Racing Club", "years": "2015-2018", "logo": "🔵"}, {"team": "Inter", "years": "2018-", "logo": "🔵"}], "nationality": "Arjantin", "position": "Forvet", "age": 27, "current_team": "Inter", "difficulty": "easy"},
    {"name": "Hakan Çalhanoğlu", "team_history": [{"team": "Karlsruher SC", "years": "2011-2013", "logo": "🔵"}, {"team": "Hamburg", "years": "2013-2014", "logo": "🔵"}, {"team": "Bayer Leverkusen", "years": "2014-2017", "logo": "🔴"}, {"team": "AC Milan", "years": "2017-2021", "logo": "🔴"}, {"team": "Inter", "years": "2021-", "logo": "🔵"}], "nationality": "Türkiye", "position": "Orta Saha", "age": 30, "current_team": "Inter", "difficulty": "easy"},
    {"name": "Nicolò Barella", "team_history": [{"team": "Cagliari", "years": "2015-2019", "logo": "🔴"}, {"team": "Inter", "years": "2019-", "logo": "🔵"}], "nationality": "İtalya", "position": "Orta Saha", "age": 27, "current_team": "Inter", "difficulty": "easy"},
    {"name": "Marcus Thuram", "team_history": [{"team": "Sochaux", "years": "2016-2017", "logo": "🔵"}, {"team": "Guingamp", "years": "2017-2019", "logo": "🔴"}, {"team": "Borussia M'gladbach", "years": "2019-2023", "logo": "🟢"}, {"team": "Inter", "years": "2023-", "logo": "🔵"}], "nationality": "Fransa", "position": "Forvet", "age": 27, "current_team": "Inter", "difficulty": "easy"},
    {"name": "Benjamin Pavard", "team_history": [{"team": "Lille", "years": "2015-2016", "logo": "🔴"}, {"team": "Stuttgart", "years": "2016-2019", "logo": "⚪"}, {"team": "Bayern Münih", "years": "2019-2023", "logo": "🔴"}, {"team": "Inter", "years": "2023-", "logo": "🔵"}], "nationality": "Fransa", "position": "Stoper", "age": 28, "current_team": "Inter", "difficulty": "easy"},
    {"name": "Alessandro Bastoni", "team_history": [{"team": "Atalanta", "years": "2017-2019", "logo": "🔵"}, {"team": "Parma", "years": "2018-2019 (Kiralık)", "logo": "🟡"}, {"team": "Inter", "years": "2019-", "logo": "🔵"}], "nationality": "İtalya", "position": "Stoper", "age": 25, "current_team": "Inter", "difficulty": "medium"},
    {"name": "Yann Sommer", "team_history": [{"team": "Basel", "years": "2009-2014", "logo": "🔴"}, {"team": "Borussia M'gladbach", "years": "2014-2023", "logo": "🟢"}, {"team": "Bayern Münih", "years": "2023-2023", "logo": "🔴"}, {"team": "Inter", "years": "2023-", "logo": "🔵"}], "nationality": "İsviçre", "position": "Kaleci", "age": 35, "current_team": "Inter", "difficulty": "easy"},
    {"name": "Federico Dimarco", "team_history": [{"team": "Inter", "years": "2015-", "logo": "🔵"}, {"team": "Parma", "years": "2018-2019 (Kiralık)", "logo": "🟡"}, {"team": "Verona", "years": "2020-2021 (Kiralık)", "logo": "🟡"}], "nationality": "İtalya", "position": "Sol Bek", "age": 26, "current_team": "Inter", "difficulty": "medium"},
    {"name": "Denzel Dumfries", "team_history": [{"team": "Sparta Rotterdam", "years": "2014-2017", "logo": "🔴"}, {"team": "Heerenveen", "years": "2017-2018", "logo": "🔵"}, {"team": "PSV", "years": "2018-2021", "logo": "🔴"}, {"team": "Inter", "years": "2021-", "logo": "🔵"}], "nationality": "Hollanda", "position": "Sağ Bek", "age": 28, "current_team": "Inter", "difficulty": "medium"},
    {"name": "Henrikh Mkhitaryan", "team_history": [{"team": "Shakhtar Donetsk", "years": "2010-2013", "logo": "🟠"}, {"team": "Borussia Dortmund", "years": "2013-2016", "logo": "🟡"}, {"team": "Manchester United", "years": "2016-2018", "logo": "🔴"}, {"team": "Arsenal", "years": "2018-2020", "logo": "🔴"}, {"team": "Roma", "years": "2020-2022", "logo": "🟡"}, {"team": "Inter", "years": "2022-", "logo": "🔵"}], "nationality": "Ermenistan", "position": "Orta Saha", "age": 35, "current_team": "Inter", "difficulty": "easy"},
    {"name": "Stefan de Vrij", "team_history": [{"team": "Feyenoord", "years": "2009-2014", "logo": "🔴"}, {"team": "Lazio", "years": "2014-2018", "logo": "🔵"}, {"team": "Inter", "years": "2018-", "logo": "🔵"}], "nationality": "Hollanda", "position": "Stoper", "age": 32, "current_team": "Inter", "difficulty": "medium"},
    {"name": "Francesco Acerbi", "team_history": [{"team": "Chievo", "years": "2008-2009", "logo": "🟡"}, {"team": "Milan", "years": "2009-2012", "logo": "🔴"}, {"team": "Sassuolo", "years": "2013-2016", "logo": "🟢"}, {"team": "Lazio", "years": "2016-2022", "logo": "🔵"}, {"team": "Inter", "years": "2022-", "logo": "🔵"}], "nationality": "İtalya", "position": "Stoper", "age": 36, "current_team": "Inter", "difficulty": "medium"},
    {"name": "Piotr Zieliński", "team_history": [{"team": "Udinese", "years": "2012-2014", "logo": "⚫"}, {"team": "Empoli", "years": "2014-2016 (Kiralık)", "logo": "🔵"}, {"team": "Napoli", "years": "2016-2024", "logo": "🔵"}, {"team": "Inter", "years": "2024-", "logo": "🔵"}], "nationality": "Polonya", "position": "Orta Saha", "age": 30, "current_team": "Inter", "difficulty": "easy"},
    {"name": "Mehdi Taremi", "team_history": [{"team": "Persepolis", "years": "2015-2019", "logo": "🔴"}, {"team": "Rio Ave", "years": "2019-2020", "logo": "🟢"}, {"team": "Porto", "years": "2020-2024", "logo": "🔵"}, {"team": "Inter", "years": "2024-", "logo": "🔵"}], "nationality": "İran", "position": "Forvet", "age": 31, "current_team": "Inter", "difficulty": "medium"},
    
    # ============ AC MILAN ============
    {"name": "Rafael Leão", "team_history": [{"team": "Sporting CP", "years": "2017-2018", "logo": "🟢"}, {"team": "Lille", "years": "2018-2019", "logo": "🔴"}, {"team": "AC Milan", "years": "2019-", "logo": "🔴"}], "nationality": "Portekiz", "position": "Sol Kanat", "age": 25, "current_team": "AC Milan", "difficulty": "easy"},
    {"name": "Theo Hernández", "team_history": [{"team": "Atlético Madrid", "years": "2016-2017", "logo": "🔴"}, {"team": "Real Madrid", "years": "2017-2019", "logo": "⚪"}, {"team": "Real Sociedad", "years": "2017-2018 (Kiralık)", "logo": "🔵"}, {"team": "AC Milan", "years": "2019-", "logo": "🔴"}], "nationality": "Fransa", "position": "Sol Bek", "age": 27, "current_team": "AC Milan", "difficulty": "easy"},
    {"name": "Mike Maignan", "team_history": [{"team": "PSG", "years": "2015-2015", "logo": "🔵"}, {"team": "Lille", "years": "2015-2021", "logo": "🔴"}, {"team": "AC Milan", "years": "2021-", "logo": "🔴"}], "nationality": "Fransa", "position": "Kaleci", "age": 28, "current_team": "AC Milan", "difficulty": "easy"},
    {"name": "Christian Pulisic", "team_history": [{"team": "Borussia Dortmund", "years": "2015-2019", "logo": "🟡"}, {"team": "Chelsea", "years": "2019-2023", "logo": "🔵"}, {"team": "AC Milan", "years": "2023-", "logo": "🔴"}], "nationality": "ABD", "position": "Kanat", "age": 25, "current_team": "AC Milan", "difficulty": "easy"},
    {"name": "Tijjani Reijnders", "team_history": [{"team": "AZ Alkmaar", "years": "2018-2023", "logo": "🔴"}, {"team": "AC Milan", "years": "2023-", "logo": "🔴"}], "nationality": "Hollanda", "position": "Orta Saha", "age": 25, "current_team": "AC Milan", "difficulty": "medium"},
    {"name": "Fikayo Tomori", "team_history": [{"team": "Chelsea", "years": "2016-2021", "logo": "🔵"}, {"team": "Brighton", "years": "2017-2018 (Kiralık)", "logo": "🔵"}, {"team": "Hull City", "years": "2018-2019 (Kiralık)", "logo": "🟠"}, {"team": "Derby County", "years": "2019 (Kiralık)", "logo": "⚪"}, {"team": "AC Milan", "years": "2021-", "logo": "🔴"}], "nationality": "İngiltere", "position": "Stoper", "age": 26, "current_team": "AC Milan", "difficulty": "easy"},
    {"name": "Ruben Loftus-Cheek", "team_history": [{"team": "Chelsea", "years": "2014-2023", "logo": "🔵"}, {"team": "Crystal Palace", "years": "2017-2018 (Kiralık)", "logo": "🔴"}, {"team": "Fulham", "years": "2020-2021 (Kiralık)", "logo": "⚪"}, {"team": "AC Milan", "years": "2023-", "logo": "🔴"}], "nationality": "İngiltere", "position": "Orta Saha", "age": 28, "current_team": "AC Milan", "difficulty": "easy"},
    {"name": "Samuel Chukwueze", "team_history": [{"team": "Villarreal", "years": "2018-2023", "logo": "🟡"}, {"team": "AC Milan", "years": "2023-", "logo": "🔴"}], "nationality": "Nijerya", "position": "Sağ Kanat", "age": 25, "current_team": "AC Milan", "difficulty": "medium"},
    {"name": "Davide Calabria", "team_history": [{"team": "AC Milan", "years": "2015-", "logo": "🔴"}], "nationality": "İtalya", "position": "Sağ Bek", "age": 27, "current_team": "AC Milan", "difficulty": "medium"},
    {"name": "Malick Thiaw", "team_history": [{"team": "Schalke 04", "years": "2019-2022", "logo": "🔵"}, {"team": "AC Milan", "years": "2022-", "logo": "🔴"}], "nationality": "Almanya", "position": "Stoper", "age": 23, "current_team": "AC Milan", "difficulty": "medium"},
    {"name": "Álvaro Morata", "team_history": [{"team": "Real Madrid", "years": "2010-2014", "logo": "⚪"}, {"team": "Juventus", "years": "2014-2016", "logo": "⚫"}, {"team": "Real Madrid", "years": "2016-2017", "logo": "⚪"}, {"team": "Chelsea", "years": "2017-2019", "logo": "🔵"}, {"team": "Atlético Madrid", "years": "2019-2024", "logo": "🔴"}, {"team": "Juventus", "years": "2020-2022 (Kiralık)", "logo": "⚫"}, {"team": "AC Milan", "years": "2024-", "logo": "🔴"}], "nationality": "İspanya", "position": "Forvet", "age": 32, "current_team": "AC Milan", "difficulty": "easy"},
    {"name": "Tammy Abraham", "team_history": [{"team": "Chelsea", "years": "2016-2021", "logo": "🔵"}, {"team": "Bristol City", "years": "2016-2017 (Kiralık)", "logo": "🔴"}, {"team": "Swansea", "years": "2017-2018 (Kiralık)", "logo": "⚪"}, {"team": "Aston Villa", "years": "2018-2019 (Kiralık)", "logo": "🟣"}, {"team": "Roma", "years": "2021-2024", "logo": "🟡"}, {"team": "AC Milan", "years": "2024-", "logo": "🔴"}], "nationality": "İngiltere", "position": "Forvet", "age": 27, "current_team": "AC Milan", "difficulty": "easy"},
    {"name": "Youssouf Fofana", "team_history": [{"team": "Strasbourg", "years": "2017-2020", "logo": "🔵"}, {"team": "Monaco", "years": "2020-2024", "logo": "🔴"}, {"team": "AC Milan", "years": "2024-", "logo": "🔴"}], "nationality": "Fransa", "position": "Orta Saha", "age": 25, "current_team": "AC Milan", "difficulty": "medium"},
    {"name": "Strahinja Pavlović", "team_history": [{"team": "Partizan", "years": "2018-2019", "logo": "⚫"}, {"team": "Monaco", "years": "2019-2020", "logo": "🔴"}, {"team": "Cercle Brugge", "years": "2020-2021 (Kiralık)", "logo": "🟢"}, {"team": "Red Bull Salzburg", "years": "2022-2024", "logo": "🔴"}, {"team": "AC Milan", "years": "2024-", "logo": "🔴"}], "nationality": "Sırbistan", "position": "Stoper", "age": 23, "current_team": "AC Milan", "difficulty": "medium"},
    {"name": "Emerson Royal", "team_history": [{"team": "Atlético Mineiro", "years": "2018-2019", "logo": "⚫"}, {"team": "Real Betis", "years": "2019-2021", "logo": "🟢"}, {"team": "Barcelona", "years": "2021-2021", "logo": "🔵"}, {"team": "Tottenham", "years": "2021-2024", "logo": "⚪"}, {"team": "AC Milan", "years": "2024-", "logo": "🔴"}], "nationality": "Brezilya", "position": "Sağ Bek", "age": 25, "current_team": "AC Milan", "difficulty": "medium"},
    
    # ============ JUVENTUS ============
    {"name": "Dušan Vlahović", "team_history": [{"team": "Partizan", "years": "2016-2018", "logo": "⚫"}, {"team": "Fiorentina", "years": "2018-2022", "logo": "🟣"}, {"team": "Juventus", "years": "2022-", "logo": "⚫"}], "nationality": "Sırbistan", "position": "Forvet", "age": 24, "current_team": "Juventus", "difficulty": "easy"},
    {"name": "Kenan Yıldız", "team_history": [{"team": "Bayern Münih", "years": "2019-2022", "logo": "🔴"}, {"team": "Juventus", "years": "2022-", "logo": "⚫"}], "nationality": "Türkiye", "position": "Sol Kanat", "age": 19, "current_team": "Juventus", "difficulty": "easy"},
    {"name": "Teun Koopmeiners", "team_history": [{"team": "AZ Alkmaar", "years": "2018-2021", "logo": "🔴"}, {"team": "Atalanta", "years": "2021-2024", "logo": "🔵"}, {"team": "Juventus", "years": "2024-", "logo": "⚫"}], "nationality": "Hollanda", "position": "Orta Saha", "age": 26, "current_team": "Juventus", "difficulty": "easy"},
    {"name": "Gleison Bremer", "team_history": [{"team": "Atlético Mineiro", "years": "2017-2018", "logo": "⚫"}, {"team": "Torino", "years": "2018-2022", "logo": "🟣"}, {"team": "Juventus", "years": "2022-", "logo": "⚫"}], "nationality": "Brezilya", "position": "Stoper", "age": 27, "current_team": "Juventus", "difficulty": "medium"},
    {"name": "Michele Di Gregorio", "team_history": [{"team": "Inter", "years": "2018-2020", "logo": "🔵"}, {"team": "Pordenone", "years": "2019-2020 (Kiralık)", "logo": "🟢"}, {"team": "Monza", "years": "2020-2024", "logo": "🔴"}, {"team": "Juventus", "years": "2024-", "logo": "⚫"}], "nationality": "İtalya", "position": "Kaleci", "age": 27, "current_team": "Juventus", "difficulty": "medium"},
    {"name": "Manuel Locatelli", "team_history": [{"team": "AC Milan", "years": "2016-2018", "logo": "🔴"}, {"team": "Sassuolo", "years": "2018-2021", "logo": "🟢"}, {"team": "Juventus", "years": "2021-", "logo": "⚫"}], "nationality": "İtalya", "position": "Orta Saha", "age": 26, "current_team": "Juventus", "difficulty": "medium"},
    {"name": "Andrea Cambiaso", "team_history": [{"team": "Genoa", "years": "2019-2021", "logo": "🔴"}, {"team": "Empoli", "years": "2020-2021 (Kiralık)", "logo": "🔵"}, {"team": "Bologna", "years": "2021-2022", "logo": "🔴"}, {"team": "Juventus", "years": "2022-", "logo": "⚫"}], "nationality": "İtalya", "position": "Sol Bek", "age": 24, "current_team": "Juventus", "difficulty": "medium"},
    {"name": "Weston McKennie", "team_history": [{"team": "FC Dallas", "years": "2016-2017", "logo": "🔵"}, {"team": "Schalke 04", "years": "2017-2020", "logo": "🔵"}, {"team": "Juventus", "years": "2020-", "logo": "⚫"}, {"team": "Leeds United", "years": "2023 (Kiralık)", "logo": "⚪"}], "nationality": "ABD", "position": "Orta Saha", "age": 25, "current_team": "Juventus", "difficulty": "medium"},
    {"name": "Nicolás González", "team_history": [{"team": "Argentinos Juniors", "years": "2016-2018", "logo": "🔴"}, {"team": "Stuttgart", "years": "2018-2021", "logo": "⚪"}, {"team": "Fiorentina", "years": "2021-2024", "logo": "🟣"}, {"team": "Juventus", "years": "2024-", "logo": "⚫"}], "nationality": "Arjantin", "position": "Kanat", "age": 26, "current_team": "Juventus", "difficulty": "medium"},
    {"name": "Timothy Weah", "team_history": [{"team": "PSG", "years": "2018-2019", "logo": "🔵"}, {"team": "Celtic", "years": "2019 (Kiralık)", "logo": "🟢"}, {"team": "Lille", "years": "2019-2024", "logo": "🔴"}, {"team": "Juventus", "years": "2024-", "logo": "⚫"}], "nationality": "ABD", "position": "Kanat", "age": 24, "current_team": "Juventus", "difficulty": "medium"},
    {"name": "Juan Cabal", "team_history": [{"team": "Atlético Nacional", "years": "2020-2022", "logo": "🟢"}, {"team": "Verona", "years": "2022-2024", "logo": "🟡"}, {"team": "Juventus", "years": "2024-", "logo": "⚫"}], "nationality": "Kolombiya", "position": "Sol Bek", "age": 23, "current_team": "Juventus", "difficulty": "medium"},
    {"name": "Pierre Kalulu", "team_history": [{"team": "Lyon", "years": "2018-2020", "logo": "🔵"}, {"team": "AC Milan", "years": "2020-2024", "logo": "🔴"}, {"team": "Juventus", "years": "2024- (Kiralık)", "logo": "⚫"}], "nationality": "Fransa", "position": "Stoper", "age": 24, "current_team": "Juventus", "difficulty": "medium"},
    {"name": "Khéphren Thuram", "team_history": [{"team": "Monaco", "years": "2018-2019", "logo": "🔴"}, {"team": "Nice", "years": "2019-2024", "logo": "🔴"}, {"team": "Juventus", "years": "2024-", "logo": "⚫"}], "nationality": "Fransa", "position": "Orta Saha", "age": 23, "current_team": "Juventus", "difficulty": "medium"},
    
    # ============ NAPOLI ============
    {"name": "Khvicha Kvaratskhelia", "team_history": [{"team": "Dinamo Tiflis", "years": "2017-2019", "logo": "🔵"}, {"team": "Rubin Kazan", "years": "2019-2022", "logo": "🟢"}, {"team": "Dinamo Batumi", "years": "2022 (Kiralık)", "logo": "🔵"}, {"team": "Napoli", "years": "2022-", "logo": "🔵"}], "nationality": "Gürcistan", "position": "Sol Kanat", "age": 23, "current_team": "Napoli", "difficulty": "easy"},
    {"name": "Victor Osimhen", "team_history": [{"team": "Wolfsburg", "years": "2017-2018", "logo": "🟢"}, {"team": "Charleroi", "years": "2018-2019", "logo": "⚫"}, {"team": "Lille", "years": "2019-2020", "logo": "🔴"}, {"team": "Napoli", "years": "2020-", "logo": "🔵"}, {"team": "Galatasaray", "years": "2024- (Kiralık)", "logo": "🟡"}], "nationality": "Nijerya", "position": "Forvet", "age": 25, "current_team": "Galatasaray", "difficulty": "easy"},
    {"name": "Giovanni Di Lorenzo", "team_history": [{"team": "Empoli", "years": "2017-2019", "logo": "🔵"}, {"team": "Napoli", "years": "2019-", "logo": "🔵"}], "nationality": "İtalya", "position": "Sağ Bek", "age": 31, "current_team": "Napoli", "difficulty": "medium"},
    {"name": "Amir Rrahmani", "team_history": [{"team": "Dinamo Zagreb", "years": "2016-2019", "logo": "🔵"}, {"team": "Verona", "years": "2019-2021", "logo": "🟡"}, {"team": "Napoli", "years": "2021-", "logo": "🔵"}], "nationality": "Kosova", "position": "Stoper", "age": 30, "current_team": "Napoli", "difficulty": "medium"},
    {"name": "Alex Meret", "team_history": [{"team": "Udinese", "years": "2015-2018", "logo": "⚫"}, {"team": "SPAL", "years": "2017-2018 (Kiralık)", "logo": "⚪"}, {"team": "Napoli", "years": "2018-", "logo": "🔵"}], "nationality": "İtalya", "position": "Kaleci", "age": 27, "current_team": "Napoli", "difficulty": "medium"},
    {"name": "Mathías Olivera", "team_history": [{"team": "Nacional", "years": "2016-2018", "logo": "⚪"}, {"team": "Getafe", "years": "2018-2022", "logo": "🔵"}, {"team": "Napoli", "years": "2022-", "logo": "🔵"}], "nationality": "Uruguay", "position": "Sol Bek", "age": 27, "current_team": "Napoli", "difficulty": "medium"},
    {"name": "André-Frank Zambo Anguissa", "team_history": [{"team": "Marsilya", "years": "2017-2018", "logo": "🔵"}, {"team": "Fulham", "years": "2018-2021", "logo": "⚪"}, {"team": "Villarreal", "years": "2020-2021 (Kiralık)", "logo": "🟡"}, {"team": "Napoli", "years": "2021-", "logo": "🔵"}], "nationality": "Kamerun", "position": "Orta Saha", "age": 28, "current_team": "Napoli", "difficulty": "medium"},
    {"name": "Stanislav Lobotka", "team_history": [{"team": "Trenčín", "years": "2013-2017", "logo": "🔴"}, {"team": "Celta Vigo", "years": "2017-2020", "logo": "🔵"}, {"team": "Napoli", "years": "2020-", "logo": "🔵"}], "nationality": "Slovakya", "position": "Defansif Orta Saha", "age": 30, "current_team": "Napoli", "difficulty": "medium"},
    {"name": "Romelu Lukaku", "team_history": [{"team": "Anderlecht", "years": "2009-2011", "logo": "🟣"}, {"team": "Chelsea", "years": "2011-2014", "logo": "🔵"}, {"team": "West Brom", "years": "2012-2013 (Kiralık)", "logo": "⚪"}, {"team": "Everton", "years": "2013-2017", "logo": "🔵"}, {"team": "Manchester United", "years": "2017-2019", "logo": "🔴"}, {"team": "Inter", "years": "2019-2021", "logo": "🔵"}, {"team": "Chelsea", "years": "2021-2022", "logo": "🔵"}, {"team": "Inter", "years": "2022-2023 (Kiralık)", "logo": "🔵"}, {"team": "Roma", "years": "2023-2024 (Kiralık)", "logo": "🟡"}, {"team": "Napoli", "years": "2024-", "logo": "🔵"}], "nationality": "Belçika", "position": "Forvet", "age": 31, "current_team": "Napoli", "difficulty": "easy"},
    {"name": "Scott McTominay", "team_history": [{"team": "Manchester United", "years": "2017-2024", "logo": "🔴"}, {"team": "Napoli", "years": "2024-", "logo": "🔵"}], "nationality": "İskoçya", "position": "Orta Saha", "age": 27, "current_team": "Napoli", "difficulty": "easy"},
    {"name": "Billy Gilmour", "team_history": [{"team": "Chelsea", "years": "2019-2022", "logo": "🔵"}, {"team": "Norwich City", "years": "2021-2022 (Kiralık)", "logo": "🟡"}, {"team": "Brighton", "years": "2022-2024", "logo": "🔵"}, {"team": "Napoli", "years": "2024-", "logo": "🔵"}], "nationality": "İskoçya", "position": "Orta Saha", "age": 23, "current_team": "Napoli", "difficulty": "medium"},
    {"name": "Giacomo Raspadori", "team_history": [{"team": "Sassuolo", "years": "2018-2022", "logo": "🟢"}, {"team": "Napoli", "years": "2022-", "logo": "🔵"}], "nationality": "İtalya", "position": "Forvet", "age": 24, "current_team": "Napoli", "difficulty": "medium"},
    {"name": "Matteo Politano", "team_history": [{"team": "Roma", "years": "2012-2016", "logo": "🟡"}, {"team": "Sassuolo", "years": "2016-2018", "logo": "🟢"}, {"team": "Inter", "years": "2018-2020", "logo": "🔵"}, {"team": "Napoli", "years": "2020-", "logo": "🔵"}], "nationality": "İtalya", "position": "Sağ Kanat", "age": 31, "current_team": "Napoli", "difficulty": "medium"},
    
    # ============ ROMA ============
    {"name": "Artem Dovbyk", "team_history": [{"team": "Dnipro-1", "years": "2021-2023", "logo": "🔵"}, {"team": "Girona", "years": "2023-2024", "logo": "🔴"}, {"team": "Roma", "years": "2024-", "logo": "🟡"}], "nationality": "Ukrayna", "position": "Forvet", "age": 27, "current_team": "Roma", "difficulty": "easy"},
    {"name": "Paulo Dybala", "team_history": [{"team": "Instituto", "years": "2011-2012", "logo": "🔵"}, {"team": "Palermo", "years": "2012-2015", "logo": "🟣"}, {"team": "Juventus", "years": "2015-2022", "logo": "⚫"}, {"team": "Roma", "years": "2022-", "logo": "🟡"}], "nationality": "Arjantin", "position": "İkinci Forvet", "age": 31, "current_team": "Roma", "difficulty": "easy"},
    {"name": "Lorenzo Pellegrini", "team_history": [{"team": "Roma", "years": "2015-", "logo": "🟡"}, {"team": "Sassuolo", "years": "2016-2017 (Kiralık)", "logo": "🟢"}], "nationality": "İtalya", "position": "Orta Saha", "age": 28, "current_team": "Roma", "difficulty": "medium"},
    {"name": "Mile Svilar", "team_history": [{"team": "Anderlecht", "years": "2016-2017", "logo": "🟣"}, {"team": "Benfica", "years": "2017-2022", "logo": "🔴"}, {"team": "Roma", "years": "2022-", "logo": "🟡"}], "nationality": "Belçika", "position": "Kaleci", "age": 25, "current_team": "Roma", "difficulty": "medium"},
    {"name": "Gianluca Mancini", "team_history": [{"team": "Atalanta", "years": "2016-2019", "logo": "🔵"}, {"team": "Roma", "years": "2019-", "logo": "🟡"}], "nationality": "İtalya", "position": "Stoper", "age": 28, "current_team": "Roma", "difficulty": "medium"},
    {"name": "Bryan Cristante", "team_history": [{"team": "AC Milan", "years": "2014-2016", "logo": "🔴"}, {"team": "Benfica", "years": "2016-2017", "logo": "🔴"}, {"team": "Atalanta", "years": "2017-2018", "logo": "🔵"}, {"team": "Roma", "years": "2018-", "logo": "🟡"}], "nationality": "İtalya", "position": "Orta Saha", "age": 29, "current_team": "Roma", "difficulty": "medium"},
    {"name": "Stephan El Shaarawy", "team_history": [{"team": "Genoa", "years": "2008-2011", "logo": "🔴"}, {"team": "AC Milan", "years": "2011-2016", "logo": "🔴"}, {"team": "Monaco", "years": "2015-2016 (Kiralık)", "logo": "🔴"}, {"team": "Roma", "years": "2016-2019", "logo": "🟡"}, {"team": "Shanghai Shenhua", "years": "2019-2020", "logo": "🔵"}, {"team": "Roma", "years": "2021-", "logo": "🟡"}], "nationality": "İtalya", "position": "Kanat", "age": 32, "current_team": "Roma", "difficulty": "medium"},
    {"name": "Matías Soulé", "team_history": [{"team": "Juventus", "years": "2021-2024", "logo": "⚫"}, {"team": "Frosinone", "years": "2023-2024 (Kiralık)", "logo": "🟡"}, {"team": "Roma", "years": "2024-", "logo": "🟡"}], "nationality": "Arjantin", "position": "Kanat", "age": 21, "current_team": "Roma", "difficulty": "medium"},
    {"name": "Mats Hummels", "team_history": [{"team": "Bayern Münih", "years": "2007-2009", "logo": "🔴"}, {"team": "Borussia Dortmund", "years": "2009-2016", "logo": "🟡"}, {"team": "Bayern Münih", "years": "2016-2019", "logo": "🔴"}, {"team": "Borussia Dortmund", "years": "2019-2024", "logo": "🟡"}, {"team": "Roma", "years": "2024-", "logo": "🟡"}], "nationality": "Almanya", "position": "Stoper", "age": 35, "current_team": "Roma", "difficulty": "easy"},
    {"name": "Mario Hermoso", "team_history": [{"team": "Real Madrid", "years": "2017-2019", "logo": "⚪"}, {"team": "Espanyol", "years": "2018-2019 (Kiralık)", "logo": "🔵"}, {"team": "Atlético Madrid", "years": "2019-2024", "logo": "🔴"}, {"team": "Roma", "years": "2024-", "logo": "🟡"}], "nationality": "İspanya", "position": "Stoper", "age": 29, "current_team": "Roma", "difficulty": "medium"},
    
    # ============ ATALANTA ============
    {"name": "Ademola Lookman", "team_history": [{"team": "Charlton", "years": "2014-2017", "logo": "🔴"}, {"team": "Everton", "years": "2017-2019", "logo": "🔵"}, {"team": "RB Leipzig", "years": "2018-2019 (Kiralık)", "logo": "🔴"}, {"team": "Fulham", "years": "2019-2020 (Kiralık)", "logo": "⚪"}, {"team": "RB Leipzig", "years": "2019-2022", "logo": "🔴"}, {"team": "Leicester", "years": "2021-2022 (Kiralık)", "logo": "🔵"}, {"team": "Atalanta", "years": "2022-", "logo": "🔵"}], "nationality": "Nijerya", "position": "Kanat", "age": 27, "current_team": "Atalanta", "difficulty": "easy"},
    {"name": "Charles De Ketelaere", "team_history": [{"team": "Club Brugge", "years": "2019-2022", "logo": "🔵"}, {"team": "AC Milan", "years": "2022-2023", "logo": "🔴"}, {"team": "Atalanta", "years": "2023-", "logo": "🔵"}], "nationality": "Belçika", "position": "İkinci Forvet", "age": 23, "current_team": "Atalanta", "difficulty": "medium"},
    {"name": "Mateo Retegui", "team_history": [{"team": "Boca Juniors", "years": "2017-2020", "logo": "🔵"}, {"team": "Talleres", "years": "2020-2021", "logo": "🔵"}, {"team": "Tigre", "years": "2021-2022 (Kiralık)", "logo": "🔵"}, {"team": "Genoa", "years": "2023-2024", "logo": "🔴"}, {"team": "Atalanta", "years": "2024-", "logo": "🔵"}], "nationality": "Arjantin", "position": "Forvet", "age": 25, "current_team": "Atalanta", "difficulty": "medium"},
    {"name": "Gianluca Scamacca", "team_history": [{"team": "Roma", "years": "2015-2016", "logo": "🟡"}, {"team": "PSV", "years": "2016-2017 (Kiralık)", "logo": "🔴"}, {"team": "Sassuolo", "years": "2017-2022", "logo": "🟢"}, {"team": "Genoa", "years": "2019-2020 (Kiralık)", "logo": "🔴"}, {"team": "Ascoli", "years": "2020 (Kiralık)", "logo": "⚪"}, {"team": "West Ham", "years": "2022-2023", "logo": "🟣"}, {"team": "Atalanta", "years": "2023-", "logo": "🔵"}], "nationality": "İtalya", "position": "Forvet", "age": 25, "current_team": "Atalanta", "difficulty": "medium"},
    {"name": "Éderson", "team_history": [{"team": "Corinthians", "years": "2015-2017", "logo": "⚫"}, {"team": "Desportivo Brasil", "years": "2018", "logo": "🟢"}, {"team": "Cruzeiro", "years": "2018-2019", "logo": "🔵"}, {"team": "Fortaleza", "years": "2019", "logo": "🔴"}, {"team": "Salernitana", "years": "2021-2022", "logo": "🟣"}, {"team": "Atalanta", "years": "2022-", "logo": "🔵"}], "nationality": "Brezilya", "position": "Orta Saha", "age": 25, "current_team": "Atalanta", "difficulty": "medium"},
    {"name": "Isak Hien", "team_history": [{"team": "Djurgårdens IF", "years": "2019-2022", "logo": "🔵"}, {"team": "Verona", "years": "2022-2023", "logo": "🟡"}, {"team": "Atalanta", "years": "2023-", "logo": "🔵"}], "nationality": "İsveç", "position": "Stoper", "age": 25, "current_team": "Atalanta", "difficulty": "medium"},
    {"name": "Juan Musso", "team_history": [{"team": "Racing Club", "years": "2014-2018", "logo": "🔵"}, {"team": "Udinese", "years": "2018-2021", "logo": "⚫"}, {"team": "Atalanta", "years": "2021-", "logo": "🔵"}], "nationality": "Arjantin", "position": "Kaleci", "age": 30, "current_team": "Atalanta", "difficulty": "medium"},
    {"name": "Marten de Roon", "team_history": [{"team": "Heerenveen", "years": "2008-2016", "logo": "🔵"}, {"team": "Atalanta", "years": "2016-2017", "logo": "🔵"}, {"team": "Middlesbrough", "years": "2016-2017", "logo": "🔴"}, {"team": "Atalanta", "years": "2017-", "logo": "🔵"}], "nationality": "Hollanda", "position": "Defansif Orta Saha", "age": 33, "current_team": "Atalanta", "difficulty": "medium"},
    {"name": "Sead Kolašinac", "team_history": [{"team": "Schalke 04", "years": "2011-2017", "logo": "🔵"}, {"team": "Arsenal", "years": "2017-2022", "logo": "🔴"}, {"team": "Schalke 04", "years": "2020-2021 (Kiralık)", "logo": "🔵"}, {"team": "Marsilya", "years": "2022-2023", "logo": "🔵"}, {"team": "Atalanta", "years": "2023-", "logo": "🔵"}], "nationality": "Bosna Hersek", "position": "Sol Bek", "age": 31, "current_team": "Atalanta", "difficulty": "medium"},
    {"name": "Berat Djimsiti", "team_history": [{"team": "Atalanta", "years": "2016-", "logo": "🔵"}, {"team": "Avellino", "years": "2016-2017 (Kiralık)", "logo": "🟢"}, {"team": "Benevento", "years": "2017-2018 (Kiralık)", "logo": "🟡"}], "nationality": "Arnavutluk", "position": "Stoper", "age": 31, "current_team": "Atalanta", "difficulty": "medium"},
    
    # ============ LAZIO ============
    {"name": "Mattia Zaccagni", "team_history": [{"team": "Verona", "years": "2015-2022", "logo": "🟡"}, {"team": "Lazio", "years": "2022-", "logo": "🔵"}], "nationality": "İtalya", "position": "Sol Kanat", "age": 29, "current_team": "Lazio", "difficulty": "medium"},
    {"name": "Taty Castellanos", "team_history": [{"team": "Torque", "years": "2018", "logo": "🔵"}, {"team": "New York City FC", "years": "2018-2023", "logo": "🔵"}, {"team": "Girona", "years": "2022-2023 (Kiralık)", "logo": "🔴"}, {"team": "Lazio", "years": "2023-", "logo": "🔵"}], "nationality": "Arjantin", "position": "Forvet", "age": 25, "current_team": "Lazio", "difficulty": "medium"},
    {"name": "Nuno Tavares", "team_history": [{"team": "Benfica", "years": "2018-2021", "logo": "🔴"}, {"team": "Arsenal", "years": "2021-2024", "logo": "🔴"}, {"team": "Marsilya", "years": "2022-2023 (Kiralık)", "logo": "🔵"}, {"team": "Nottingham Forest", "years": "2023-2024 (Kiralık)", "logo": "🔴"}, {"team": "Lazio", "years": "2024-", "logo": "🔵"}], "nationality": "Portekiz", "position": "Sol Bek", "age": 24, "current_team": "Lazio", "difficulty": "medium"},
    {"name": "Boulaye Dia", "team_history": [{"team": "Reims", "years": "2018-2021", "logo": "🔴"}, {"team": "Villarreal", "years": "2021-2023", "logo": "🟡"}, {"team": "Salernitana", "years": "2022-2023 (Kiralık)", "logo": "🟣"}, {"team": "Lazio", "years": "2023-", "logo": "🔵"}], "nationality": "Senegal", "position": "Forvet", "age": 27, "current_team": "Lazio", "difficulty": "medium"},
    {"name": "Ivan Provedel", "team_history": [{"team": "Modena", "years": "2015-2016", "logo": "🟡"}, {"team": "Juve Stabia", "years": "2016-2017", "logo": "🟡"}, {"team": "Empoli", "years": "2017-2019", "logo": "🔵"}, {"team": "Spezia", "years": "2019-2022", "logo": "⚪"}, {"team": "Lazio", "years": "2022-", "logo": "🔵"}], "nationality": "İtalya", "position": "Kaleci", "age": 30, "current_team": "Lazio", "difficulty": "medium"},
    {"name": "Nicolò Rovella", "team_history": [{"team": "Genoa", "years": "2019-2021", "logo": "🔴"}, {"team": "Juventus", "years": "2021-2023", "logo": "⚫"}, {"team": "Monza", "years": "2022-2023 (Kiralık)", "logo": "🔴"}, {"team": "Lazio", "years": "2023-", "logo": "🔵"}], "nationality": "İtalya", "position": "Orta Saha", "age": 22, "current_team": "Lazio", "difficulty": "medium"},
    {"name": "Alessio Romagnoli", "team_history": [{"team": "Roma", "years": "2012-2015", "logo": "🟡"}, {"team": "AC Milan", "years": "2015-2022", "logo": "🔴"}, {"team": "Lazio", "years": "2022-", "logo": "🔵"}], "nationality": "İtalya", "position": "Stoper", "age": 29, "current_team": "Lazio", "difficulty": "medium"},
    
    # ============ FIORENTINA ============
    {"name": "Moise Kean", "team_history": [{"team": "Juventus", "years": "2016-2019", "logo": "⚫"}, {"team": "Verona", "years": "2016-2017 (Kiralık)", "logo": "🟡"}, {"team": "Everton", "years": "2019-2021", "logo": "🔵"}, {"team": "PSG", "years": "2020-2021 (Kiralık)", "logo": "🔵"}, {"team": "Juventus", "years": "2021-2023", "logo": "⚫"}, {"team": "Fiorentina", "years": "2023-", "logo": "🟣"}], "nationality": "İtalya", "position": "Forvet", "age": 24, "current_team": "Fiorentina", "difficulty": "easy"},
    {"name": "Lucas Beltrán", "team_history": [{"team": "River Plate", "years": "2020-2023", "logo": "🔴"}, {"team": "Fiorentina", "years": "2023-", "logo": "🟣"}], "nationality": "Arjantin", "position": "Forvet", "age": 23, "current_team": "Fiorentina", "difficulty": "medium"},
    {"name": "Andrea Colpani", "team_history": [{"team": "Atalanta", "years": "2019-2021", "logo": "🔵"}, {"team": "Trapani", "years": "2019-2020 (Kiralık)", "logo": "🟣"}, {"team": "Monza", "years": "2021-2024", "logo": "🔴"}, {"team": "Fiorentina", "years": "2024-", "logo": "🟣"}], "nationality": "İtalya", "position": "Orta Saha", "age": 25, "current_team": "Fiorentina", "difficulty": "medium"},
    {"name": "Albert Guðmundsson", "team_history": [{"team": "PSV", "years": "2017-2019", "logo": "🔴"}, {"team": "AZ Alkmaar", "years": "2019-2021", "logo": "🔴"}, {"team": "Genoa", "years": "2022-2024", "logo": "🔴"}, {"team": "Fiorentina", "years": "2024-", "logo": "🟣"}], "nationality": "İzlanda", "position": "Forvet", "age": 27, "current_team": "Fiorentina", "difficulty": "medium"},
    {"name": "Yacine Adli", "team_history": [{"team": "PSG", "years": "2018-2020", "logo": "🔵"}, {"team": "Bordeaux", "years": "2020-2022", "logo": "🔵"}, {"team": "AC Milan", "years": "2022-2024", "logo": "🔴"}, {"team": "Fiorentina", "years": "2024-", "logo": "🟣"}], "nationality": "Fransa", "position": "Orta Saha", "age": 24, "current_team": "Fiorentina", "difficulty": "medium"},
    {"name": "David De Gea", "team_history": [{"team": "Atlético Madrid", "years": "2008-2011", "logo": "🔴"}, {"team": "Manchester United", "years": "2011-2023", "logo": "🔴"}, {"team": "Fiorentina", "years": "2024-", "logo": "🟣"}], "nationality": "İspanya", "position": "Kaleci", "age": 33, "current_team": "Fiorentina", "difficulty": "easy"},
    {"name": "Rolando Mandragora", "team_history": [{"team": "Genoa", "years": "2014-2016", "logo": "🔴"}, {"team": "Juventus", "years": "2016-2022", "logo": "⚫"}, {"team": "Crotone", "years": "2017-2018 (Kiralık)", "logo": "🔴"}, {"team": "Udinese", "years": "2018-2020 (Kiralık)", "logo": "⚫"}, {"team": "Torino", "years": "2020-2022 (Kiralık)", "logo": "🟣"}, {"team": "Fiorentina", "years": "2022-", "logo": "🟣"}], "nationality": "İtalya", "position": "Orta Saha", "age": 27, "current_team": "Fiorentina", "difficulty": "medium"},
    
    # ============ TORINO ============
    {"name": "Duván Zapata", "team_history": [{"team": "América de Cali", "years": "2008-2013", "logo": "🔴"}, {"team": "Estudiantes", "years": "2013-2014", "logo": "🔴"}, {"team": "Napoli", "years": "2014-2017", "logo": "🔵"}, {"team": "Udinese", "years": "2015-2016 (Kiralık)", "logo": "⚫"}, {"team": "Sampdoria", "years": "2017-2018", "logo": "🔵"}, {"team": "Atalanta", "years": "2018-2023", "logo": "🔵"}, {"team": "Torino", "years": "2023-", "logo": "🟣"}], "nationality": "Kolombiya", "position": "Forvet", "age": 33, "current_team": "Torino", "difficulty": "easy"},
    {"name": "Antonio Sanabria", "team_history": [{"team": "Barcelona", "years": "2012-2014", "logo": "🔵"}, {"team": "Sassuolo", "years": "2014-2016", "logo": "🟢"}, {"team": "Sporting Gijón", "years": "2015-2016 (Kiralık)", "logo": "🔴"}, {"team": "Real Betis", "years": "2016-2019", "logo": "🟢"}, {"team": "Genoa", "years": "2018-2019 (Kiralık)", "logo": "🔴"}, {"team": "Torino", "years": "2019-", "logo": "🟣"}, {"team": "Real Betis", "years": "2020-2021 (Kiralık)", "logo": "🟢"}], "nationality": "Paraguay", "position": "Forvet", "age": 28, "current_team": "Torino", "difficulty": "medium"},
    {"name": "Samuele Ricci", "team_history": [{"team": "Empoli", "years": "2019-2022", "logo": "🔵"}, {"team": "Torino", "years": "2022-", "logo": "🟣"}], "nationality": "İtalya", "position": "Orta Saha", "age": 23, "current_team": "Torino", "difficulty": "medium"},
    {"name": "Alessandro Buongiorno", "team_history": [{"team": "Torino", "years": "2019-2024", "logo": "🟣"}, {"team": "Napoli", "years": "2024-", "logo": "🔵"}], "nationality": "İtalya", "position": "Stoper", "age": 25, "current_team": "Napoli", "difficulty": "medium"},
    {"name": "Nikola Vlašić", "team_history": [{"team": "Hajduk Split", "years": "2015-2017", "logo": "🔵"}, {"team": "Everton", "years": "2017-2019", "logo": "🔵"}, {"team": "CSKA Moscow", "years": "2019-2022", "logo": "🔴"}, {"team": "West Ham", "years": "2022-2023", "logo": "🟣"}, {"team": "Torino", "years": "2022-", "logo": "🟣"}], "nationality": "Hırvatistan", "position": "Orta Saha", "age": 27, "current_team": "Torino", "difficulty": "medium"},
    {"name": "Vanja Milinković-Savić", "team_history": [{"team": "Manchester United", "years": "2014-2015", "logo": "🔴"}, {"team": "Lechia Gdańsk", "years": "2015-2017", "logo": "🟢"}, {"team": "Torino", "years": "2017-", "logo": "🟣"}, {"team": "SPAL", "years": "2018-2019 (Kiralık)", "logo": "⚪"}, {"team": "Ascoli", "years": "2019 (Kiralık)", "logo": "⚪"}, {"team": "Standard Liège", "years": "2020-2021 (Kiralık)", "logo": "🔴"}], "nationality": "Sırbistan", "position": "Kaleci", "age": 27, "current_team": "Torino", "difficulty": "medium"},
    
    # ============ BOLOGNA ============
    {"name": "Riccardo Orsolini", "team_history": [{"team": "Juventus", "years": "2017-2019", "logo": "⚫"}, {"team": "Ascoli", "years": "2016-2017 (Kiralık)", "logo": "⚪"}, {"team": "Atalanta", "years": "2017-2018 (Kiralık)", "logo": "🔵"}, {"team": "Bologna", "years": "2018-", "logo": "🔴"}], "nationality": "İtalya", "position": "Sağ Kanat", "age": 27, "current_team": "Bologna", "difficulty": "medium"},
    {"name": "Lewis Ferguson", "team_history": [{"team": "Hamilton", "years": "2017-2018", "logo": "🔴"}, {"team": "Aberdeen", "years": "2018-2022", "logo": "🔴"}, {"team": "Bologna", "years": "2022-", "logo": "🔴"}], "nationality": "İskoçya", "position": "Orta Saha", "age": 25, "current_team": "Bologna", "difficulty": "medium"},
    {"name": "Dan Ndoye", "team_history": [{"team": "Nice", "years": "2018-2021", "logo": "🔴"}, {"team": "Lausanne", "years": "2019-2020 (Kiralık)", "logo": "🔵"}, {"team": "Basel", "years": "2021-2023", "logo": "🔴"}, {"team": "Bologna", "years": "2023-", "logo": "🔴"}], "nationality": "İsviçre", "position": "Kanat", "age": 24, "current_team": "Bologna", "difficulty": "medium"},
    {"name": "Stefan Posch", "team_history": [{"team": "Hoffenheim", "years": "2019-2023", "logo": "🔵"}, {"team": "Bologna", "years": "2023-", "logo": "🔴"}], "nationality": "Avusturya", "position": "Sağ Bek", "age": 27, "current_team": "Bologna", "difficulty": "medium"},
    {"name": "Łukasz Skorupski", "team_history": [{"team": "Roma", "years": "2013-2018", "logo": "🟡"}, {"team": "Empoli", "years": "2014-2015 (Kiralık)", "logo": "🔵"}, {"team": "Empoli", "years": "2015-2018 (Kiralık)", "logo": "🔵"}, {"team": "Bologna", "years": "2018-", "logo": "🔴"}], "nationality": "Polonya", "position": "Kaleci", "age": 33, "current_team": "Bologna", "difficulty": "medium"},
    {"name": "Sam Beukema", "team_history": [{"team": "AZ Alkmaar", "years": "2021-2023", "logo": "🔴"}, {"team": "Bologna", "years": "2023-", "logo": "🔴"}], "nationality": "Hollanda", "position": "Stoper", "age": 25, "current_team": "Bologna", "difficulty": "medium"},
    {"name": "Santiago Castro", "team_history": [{"team": "Vélez Sarsfield", "years": "2021-2023", "logo": "🔵"}, {"team": "Bologna", "years": "2023-", "logo": "🔴"}], "nationality": "Arjantin", "position": "Forvet", "age": 20, "current_team": "Bologna", "difficulty": "medium"},
    
    # ============ MONZA ============
    {"name": "Daniel Maldini", "team_history": [{"team": "AC Milan", "years": "2020-2024", "logo": "🔴"}, {"team": "Spezia", "years": "2021-2022 (Kiralık)", "logo": "⚪"}, {"team": "Empoli", "years": "2023-2024 (Kiralık)", "logo": "🔵"}, {"team": "Monza", "years": "2024-", "logo": "🔴"}], "nationality": "İtalya", "position": "Forvet", "age": 23, "current_team": "Monza", "difficulty": "medium"},
    {"name": "Gianluca Caprari", "team_history": [{"team": "Roma", "years": "2012-2015", "logo": "🟡"}, {"team": "Pescara", "years": "2014-2015 (Kiralık)", "logo": "🔵"}, {"team": "Pescara", "years": "2015-2016 (Kiralık)", "logo": "🔵"}, {"team": "Sampdoria", "years": "2017-2021", "logo": "🔵"}, {"team": "Benevento", "years": "2020-2021 (Kiralık)", "logo": "🟡"}, {"team": "Verona", "years": "2021-2023", "logo": "🟡"}, {"team": "Monza", "years": "2023-", "logo": "🔴"}], "nationality": "İtalya", "position": "Forvet", "age": 31, "current_team": "Monza", "difficulty": "medium"},
]
