"""Türkiye Süper Lig Players"""

SUPER_LIG_PLAYERS = [
    # ============ GALATASARAY ============
    {"name": "Victor Osimhen", "team_history": [{"team": "Wolfsburg", "years": "2017-2018", "logo": "🟢"}, {"team": "Charleroi", "years": "2018-2019", "logo": "⚫"}, {"team": "Lille", "years": "2019-2020", "logo": "🔴"}, {"team": "Napoli", "years": "2020-", "logo": "🔵"}, {"team": "Galatasaray", "years": "2024- (Kiralık)", "logo": "🟡"}], "nationality": "Nijerya", "position": "Forvet", "age": 25, "current_team": "Galatasaray", "difficulty": "easy"},
    {"name": "Mauro Icardi", "team_history": [{"team": "Sampdoria", "years": "2011-2013", "logo": "🔵"}, {"team": "Inter", "years": "2013-2020", "logo": "🔵"}, {"team": "Paris Saint-Germain", "years": "2019-2022", "logo": "🔵"}, {"team": "Galatasaray", "years": "2022-", "logo": "🟡"}], "nationality": "Arjantin", "position": "Forvet", "age": 31, "current_team": "Galatasaray", "difficulty": "easy"},
    {"name": "Dries Mertens", "team_history": [{"team": "Gent", "years": "2006-2009", "logo": "🔵"}, {"team": "AGOVV", "years": "2009", "logo": "🟢"}, {"team": "Utrecht", "years": "2009-2011", "logo": "🔴"}, {"team": "PSV", "years": "2011-2013", "logo": "🔴"}, {"team": "Napoli", "years": "2013-2022", "logo": "🔵"}, {"team": "Galatasaray", "years": "2022-", "logo": "🟡"}], "nationality": "Belçika", "position": "Forvet", "age": 37, "current_team": "Galatasaray", "difficulty": "easy"},
    {"name": "Barış Alper Yılmaz", "team_history": [{"team": "Galatasaray", "years": "2021-", "logo": "🟡"}], "nationality": "Türkiye", "position": "Sağ Kanat", "age": 24, "current_team": "Galatasaray", "difficulty": "easy"},
    {"name": "Kerem Aktürkoğlu", "team_history": [{"team": "Galatasaray", "years": "2020-", "logo": "🟡"}], "nationality": "Türkiye", "position": "Sol Kanat", "age": 25, "current_team": "Galatasaray", "difficulty": "easy"},
    {"name": "Kaan Ayhan", "team_history": [{"team": "Schalke 04", "years": "2013-2016", "logo": "🔵"}, {"team": "Eintracht Frankfurt", "years": "2016-2017", "logo": "⚫"}, {"team": "Fortuna Düsseldorf", "years": "2017-2020", "logo": "🔴"}, {"team": "Sassuolo", "years": "2020-2023", "logo": "🟢"}, {"team": "Galatasaray", "years": "2023-", "logo": "🟡"}], "nationality": "Türkiye", "position": "Stoper", "age": 29, "current_team": "Galatasaray", "difficulty": "medium"},
    {"name": "Davinson Sánchez", "team_history": [{"team": "Atlético Nacional", "years": "2013-2016", "logo": "🟢"}, {"team": "Ajax", "years": "2016-2017", "logo": "⚪"}, {"team": "Tottenham", "years": "2017-2023", "logo": "⚪"}, {"team": "Galatasaray", "years": "2023-", "logo": "🟡"}], "nationality": "Kolombiya", "position": "Stoper", "age": 28, "current_team": "Galatasaray", "difficulty": "easy"},
    {"name": "Fernando Muslera", "team_history": [{"team": "Nacional", "years": "2003-2007", "logo": "⚪"}, {"team": "Lazio", "years": "2007-2011", "logo": "🔵"}, {"team": "Galatasaray", "years": "2011-", "logo": "🟡"}], "nationality": "Uruguay", "position": "Kaleci", "age": 38, "current_team": "Galatasaray", "difficulty": "easy"},
    {"name": "Lucas Torreira", "team_history": [{"team": "Pescara", "years": "2015-2016", "logo": "🔵"}, {"team": "Sampdoria", "years": "2016-2018", "logo": "🔵"}, {"team": "Arsenal", "years": "2018-2022", "logo": "🔴"}, {"team": "Atlético Madrid", "years": "2020-2021 (Kiralık)", "logo": "🔴"}, {"team": "Fiorentina", "years": "2021-2022 (Kiralık)", "logo": "🟣"}, {"team": "Galatasaray", "years": "2022-", "logo": "🟡"}], "nationality": "Uruguay", "position": "Defansif Orta Saha", "age": 28, "current_team": "Galatasaray", "difficulty": "easy"},
    {"name": "Sergio Oliveira", "team_history": [{"team": "Porto", "years": "2012-2022", "logo": "🔵"}, {"team": "Roma", "years": "2022", "logo": "🟡"}, {"team": "Galatasaray", "years": "2022-", "logo": "🟡"}], "nationality": "Portekiz", "position": "Orta Saha", "age": 32, "current_team": "Galatasaray", "difficulty": "medium"},
    {"name": "Yunus Akgün", "team_history": [{"team": "Galatasaray", "years": "2019-", "logo": "🟡"}, {"team": "Adana Demirspor", "years": "2021-2023 (Kiralık)", "logo": "🔵"}, {"team": "Leicester City", "years": "2023-2024 (Kiralık)", "logo": "🔵"}], "nationality": "Türkiye", "position": "Kanat", "age": 24, "current_team": "Galatasaray", "difficulty": "medium"},
    {"name": "Gabriel Sara", "team_history": [{"team": "São Paulo", "years": "2019-2022", "logo": "🔴"}, {"team": "Norwich City", "years": "2022-2024", "logo": "🟡"}, {"team": "Galatasaray", "years": "2024-", "logo": "🟡"}], "nationality": "Brezilya", "position": "Orta Saha", "age": 25, "current_team": "Galatasaray", "difficulty": "medium"},
    {"name": "Michy Batshuayi", "team_history": [{"team": "Standard Liège", "years": "2011-2014", "logo": "🔴"}, {"team": "Marsilya", "years": "2014-2016", "logo": "🔵"}, {"team": "Chelsea", "years": "2016-2022", "logo": "🔵"}, {"team": "Borussia Dortmund", "years": "2018 (Kiralık)", "logo": "🟡"}, {"team": "Valencia", "years": "2018-2019 (Kiralık)", "logo": "⚪"}, {"team": "Crystal Palace", "years": "2019 (Kiralık)", "logo": "🔴"}, {"team": "Beşiktaş", "years": "2021-2022 (Kiralık)", "logo": "⚫"}, {"team": "Fenerbahçe", "years": "2022-2024", "logo": "🟡"}, {"team": "Galatasaray", "years": "2024-", "logo": "🟡"}], "nationality": "Belçika", "position": "Forvet", "age": 30, "current_team": "Galatasaray", "difficulty": "easy"},
    {"name": "Elias Jelert", "team_history": [{"team": "Copenhagen", "years": "2021-2024", "logo": "🔵"}, {"team": "Galatasaray", "years": "2024-", "logo": "🟡"}], "nationality": "Danimarka", "position": "Sol Bek", "age": 21, "current_team": "Galatasaray", "difficulty": "medium"},
    {"name": "Roland Sallai", "team_history": [{"team": "Puskás Akadémia", "years": "2014-2016", "logo": "🔴"}, {"team": "Palermo", "years": "2016-2017", "logo": "🟣"}, {"team": "APOEL", "years": "2017-2018", "logo": "🟡"}, {"team": "Freiburg", "years": "2018-2024", "logo": "⚫"}, {"team": "Galatasaray", "years": "2024-", "logo": "🟡"}], "nationality": "Macaristan", "position": "Kanat", "age": 27, "current_team": "Galatasaray", "difficulty": "medium"},
    
    # ============ FENERBAHÇE ============
    {"name": "Edin Džeko", "team_history": [{"team": "Teplice", "years": "2005-2007", "logo": "🟡"}, {"team": "Wolfsburg", "years": "2007-2011", "logo": "🟢"}, {"team": "Manchester City", "years": "2011-2015", "logo": "🔵"}, {"team": "Roma", "years": "2015-2021", "logo": "🟡"}, {"team": "Inter", "years": "2021-2023", "logo": "🔵"}, {"team": "Fenerbahçe", "years": "2023-", "logo": "🟡"}], "nationality": "Bosna Hersek", "position": "Forvet", "age": 38, "current_team": "Fenerbahçe", "difficulty": "easy"},
    {"name": "Fred", "team_history": [{"team": "Internacional", "years": "2013-2016", "logo": "🔴"}, {"team": "Shakhtar Donetsk", "years": "2016-2018", "logo": "🟠"}, {"team": "Manchester United", "years": "2018-2023", "logo": "🔴"}, {"team": "Fenerbahçe", "years": "2023-", "logo": "🟡"}], "nationality": "Brezilya", "position": "Orta Saha", "age": 31, "current_team": "Fenerbahçe", "difficulty": "easy"},
    {"name": "Dusan Tadić", "team_history": [{"team": "Vojvodina", "years": "2007-2010", "logo": "🔴"}, {"team": "Groningen", "years": "2010-2012", "logo": "🟢"}, {"team": "Twente", "years": "2012-2014", "logo": "🔴"}, {"team": "Southampton", "years": "2014-2018", "logo": "🔴"}, {"team": "Ajax", "years": "2018-2023", "logo": "⚪"}, {"team": "Fenerbahçe", "years": "2023-", "logo": "🟡"}], "nationality": "Sırbistan", "position": "Kanat", "age": 35, "current_team": "Fenerbahçe", "difficulty": "easy"},
    {"name": "Cengiz Ünder", "team_history": [{"team": "Altınordu", "years": "2014-2016", "logo": "🔴"}, {"team": "Başakşehir", "years": "2016-2017", "logo": "🟠"}, {"team": "Roma", "years": "2017-2021", "logo": "🟡"}, {"team": "Leicester", "years": "2020-2021 (Kiralık)", "logo": "🔵"}, {"team": "Marsilya", "years": "2021-2022", "logo": "🔵"}, {"team": "Fenerbahçe", "years": "2022-", "logo": "🟡"}], "nationality": "Türkiye", "position": "Sağ Kanat", "age": 27, "current_team": "Fenerbahçe", "difficulty": "easy"},
    {"name": "Sebastian Szymański", "team_history": [{"team": "Legia Warsaw", "years": "2017-2019", "logo": "🟢"}, {"team": "Dynamo Moscow", "years": "2019-2022", "logo": "🔵"}, {"team": "Feyenoord", "years": "2022-2023", "logo": "🔴"}, {"team": "Fenerbahçe", "years": "2023-", "logo": "🟡"}], "nationality": "Polonya", "position": "Orta Saha", "age": 25, "current_team": "Fenerbahçe", "difficulty": "medium"},
    {"name": "İrfan Can Kahveci", "team_history": [{"team": "Gençlerbirliği", "years": "2014-2018", "logo": "🔴"}, {"team": "Başakşehir", "years": "2018-2021", "logo": "🟠"}, {"team": "Fenerbahçe", "years": "2021-", "logo": "🟡"}], "nationality": "Türkiye", "position": "Orta Saha", "age": 28, "current_team": "Fenerbahçe", "difficulty": "easy"},
    {"name": "İsmail Yüksek", "team_history": [{"team": "Fenerbahçe", "years": "2021-", "logo": "🟡"}], "nationality": "Türkiye", "position": "Orta Saha", "age": 24, "current_team": "Fenerbahçe", "difficulty": "medium"},
    {"name": "Youssef En-Nesyri", "team_history": [{"team": "Málaga", "years": "2016-2018", "logo": "🔵"}, {"team": "Leganés", "years": "2018-2020", "logo": "🔵"}, {"team": "Sevilla", "years": "2020-2024", "logo": "⚪"}, {"team": "Fenerbahçe", "years": "2024-", "logo": "🟡"}], "nationality": "Fas", "position": "Forvet", "age": 27, "current_team": "Fenerbahçe", "difficulty": "easy"},
    {"name": "Allan Saint-Maximin", "team_history": [{"team": "Saint-Étienne", "years": "2013-2015", "logo": "🟢"}, {"team": "Hannover 96", "years": "2015-2016 (Kiralık)", "logo": "🔴"}, {"team": "Monaco", "years": "2015-2017", "logo": "🔴"}, {"team": "Bastia", "years": "2016-2017 (Kiralık)", "logo": "🔵"}, {"team": "Nice", "years": "2017-2019", "logo": "🔴"}, {"team": "Newcastle", "years": "2019-2023", "logo": "⚫"}, {"team": "Al-Ahli", "years": "2023-2024", "logo": "🟢"}, {"team": "Fenerbahçe", "years": "2024-", "logo": "🟡"}], "nationality": "Fransa", "position": "Kanat", "age": 27, "current_team": "Fenerbahçe", "difficulty": "easy"},
    {"name": "Dominik Livaković", "team_history": [{"team": "Dinamo Zagreb", "years": "2016-2024", "logo": "🔵"}, {"team": "Fenerbahçe", "years": "2024-", "logo": "🟡"}], "nationality": "Hırvatistan", "position": "Kaleci", "age": 29, "current_team": "Fenerbahçe", "difficulty": "easy"},
    {"name": "Çağlar Söyüncü", "team_history": [{"team": "Altınordu", "years": "2014-2016", "logo": "🔴"}, {"team": "Freiburg", "years": "2016-2018", "logo": "⚫"}, {"team": "Leicester City", "years": "2018-2023", "logo": "🔵"}, {"team": "Atlético Madrid", "years": "2023-2024", "logo": "🔴"}, {"team": "Fenerbahçe", "years": "2024-", "logo": "🟡"}], "nationality": "Türkiye", "position": "Stoper", "age": 28, "current_team": "Fenerbahçe", "difficulty": "easy"},
    {"name": "Sofyan Amrabat", "team_history": [{"team": "Feyenoord", "years": "2014-2017", "logo": "🔴"}, {"team": "Utrecht", "years": "2016-2017 (Kiralık)", "logo": "🔴"}, {"team": "Club Brugge", "years": "2017-2019", "logo": "🔵"}, {"team": "Verona", "years": "2019-2020", "logo": "🟡"}, {"team": "Fiorentina", "years": "2020-2024", "logo": "🟣"}, {"team": "Manchester United", "years": "2023-2024 (Kiralık)", "logo": "🔴"}, {"team": "Fenerbahçe", "years": "2024-", "logo": "🟡"}], "nationality": "Fas", "position": "Orta Saha", "age": 28, "current_team": "Fenerbahçe", "difficulty": "easy"},
    {"name": "Mert Müldür", "team_history": [{"team": "Rapid Wien", "years": "2017-2019", "logo": "🟢"}, {"team": "Sassuolo", "years": "2019-2024", "logo": "🟢"}, {"team": "Fenerbahçe", "years": "2024-", "logo": "🟡"}], "nationality": "Türkiye", "position": "Sağ Bek", "age": 25, "current_team": "Fenerbahçe", "difficulty": "medium"},
    {"name": "Maximin Caufriez", "team_history": [{"team": "Waasland-Beveren", "years": "2017-2021", "logo": "🟡"}, {"team": "Sparta Prag", "years": "2021-2022", "logo": "🔴"}, {"team": "STVV", "years": "2022-2023", "logo": "🟡"}, {"team": "Fenerbahçe", "years": "2023-", "logo": "🟡"}], "nationality": "Belçika", "position": "Stoper", "age": 27, "current_team": "Fenerbahçe", "difficulty": "hard"},
    
    # ============ BEŞİKTAŞ ============
    {"name": "Ciro Immobile", "team_history": [{"team": "Juventus", "years": "2008-2012", "logo": "⚫"}, {"team": "Siena", "years": "2009-2010 (Kiralık)", "logo": "⚫"}, {"team": "Grosseto", "years": "2010-2011 (Kiralık)", "logo": "🔴"}, {"team": "Pescara", "years": "2011-2012 (Kiralık)", "logo": "🔵"}, {"team": "Genoa", "years": "2012-2013", "logo": "🔴"}, {"team": "Torino", "years": "2013-2014", "logo": "🟣"}, {"team": "Borussia Dortmund", "years": "2014-2015", "logo": "🟡"}, {"team": "Sevilla", "years": "2015-2016 (Kiralık)", "logo": "⚪"}, {"team": "Lazio", "years": "2016-2024", "logo": "🔵"}, {"team": "Beşiktaş", "years": "2024-", "logo": "⚫"}], "nationality": "İtalya", "position": "Forvet", "age": 34, "current_team": "Beşiktaş", "difficulty": "easy"},
    {"name": "Gedson Fernandes", "team_history": [{"team": "Benfica", "years": "2018-", "logo": "🔴"}, {"team": "Tottenham", "years": "2020 (Kiralık)", "logo": "⚪"}, {"team": "Galatasaray", "years": "2020-2021 (Kiralık)", "logo": "🟡"}, {"team": "Beşiktaş", "years": "2021-", "logo": "⚫"}], "nationality": "Portekiz", "position": "Orta Saha", "age": 25, "current_team": "Beşiktaş", "difficulty": "medium"},
    {"name": "Rafa Silva", "team_history": [{"team": "Feirense", "years": "2010-2012", "logo": "🔵"}, {"team": "Braga", "years": "2012-2016", "logo": "🔴"}, {"team": "Benfica", "years": "2016-2023", "logo": "🔴"}, {"team": "Beşiktaş", "years": "2023-", "logo": "⚫"}], "nationality": "Portekiz", "position": "Kanat", "age": 31, "current_team": "Beşiktaş", "difficulty": "easy"},
    {"name": "João Mário", "team_history": [{"team": "Sporting CP", "years": "2013-2016", "logo": "🟢"}, {"team": "Inter", "years": "2016-2021", "logo": "🔵"}, {"team": "West Ham", "years": "2017-2018 (Kiralık)", "logo": "🟣"}, {"team": "Lokomotiv Moscow", "years": "2019-2020 (Kiralık)", "logo": "🔴"}, {"team": "Sporting CP", "years": "2020-2021 (Kiralık)", "logo": "🟢"}, {"team": "Benfica", "years": "2021-2023", "logo": "🔴"}, {"team": "Beşiktaş", "years": "2023-", "logo": "⚫"}], "nationality": "Portekiz", "position": "Orta Saha", "age": 31, "current_team": "Beşiktaş", "difficulty": "easy"},
    {"name": "Milot Rashica", "team_history": [{"team": "Vitesse", "years": "2015-2018", "logo": "🟡"}, {"team": "Werder Bremen", "years": "2018-2021", "logo": "🟢"}, {"team": "Norwich City", "years": "2021-2022", "logo": "🟡"}, {"team": "Beşiktaş", "years": "2022-", "logo": "⚫"}], "nationality": "Kosova", "position": "Kanat", "age": 28, "current_team": "Beşiktaş", "difficulty": "medium"},
    {"name": "Gabriel Paulista", "team_history": [{"team": "Vitória", "years": "2012-2013", "logo": "🔴"}, {"team": "Villarreal", "years": "2013-2015", "logo": "🟡"}, {"team": "Arsenal", "years": "2015-2017", "logo": "🔴"}, {"team": "Valencia", "years": "2017-2023", "logo": "⚪"}, {"team": "Beşiktaş", "years": "2023-", "logo": "⚫"}], "nationality": "Brezilya", "position": "Stoper", "age": 33, "current_team": "Beşiktaş", "difficulty": "easy"},
    {"name": "Mert Günok", "team_history": [{"team": "Galatasaray", "years": "2006-2014", "logo": "🟡"}, {"team": "Bursaspor", "years": "2011-2012 (Kiralık)", "logo": "🟢"}, {"team": "Bursaspor", "years": "2014-2018", "logo": "🟢"}, {"team": "Başakşehir", "years": "2018-2021", "logo": "🟠"}, {"team": "Beşiktaş", "years": "2021-", "logo": "⚫"}], "nationality": "Türkiye", "position": "Kaleci", "age": 35, "current_team": "Beşiktaş", "difficulty": "easy"},
    {"name": "Semih Kılıçsoy", "team_history": [{"team": "Beşiktaş", "years": "2023-", "logo": "⚫"}], "nationality": "Türkiye", "position": "Forvet", "age": 18, "current_team": "Beşiktaş", "difficulty": "medium"},
    {"name": "Ernest Muçi", "team_history": [{"team": "Partizani Tirana", "years": "2019-2022", "logo": "🔴"}, {"team": "Beşiktaş", "years": "2022-", "logo": "⚫"}], "nationality": "Arnavutluk", "position": "Kanat", "age": 22, "current_team": "Beşiktaş", "difficulty": "medium"},
    {"name": "Cher Ndour", "team_history": [{"team": "Benfica", "years": "2021-2023", "logo": "🔴"}, {"team": "Braga", "years": "2022-2023 (Kiralık)", "logo": "🔴"}, {"team": "PSG", "years": "2023-", "logo": "🔵"}, {"team": "Beşiktaş", "years": "2024- (Kiralık)", "logo": "⚫"}], "nationality": "İtalya", "position": "Orta Saha", "age": 19, "current_team": "Beşiktaş", "difficulty": "medium"},
    
    # ============ TRABZONSPOR ============
    {"name": "Enis Bardhi", "team_history": [{"team": "Újpest", "years": "2015-2017", "logo": "🟣"}, {"team": "Levante", "years": "2017-2023", "logo": "🔵"}, {"team": "Trabzonspor", "years": "2023-", "logo": "🔵"}], "nationality": "Kuzey Makedonya", "position": "Orta Saha", "age": 29, "current_team": "Trabzonspor", "difficulty": "medium"},
    {"name": "Anastasios Bakasetas", "team_history": [{"team": "AEK Athens", "years": "2014-2018", "logo": "🟡"}, {"team": "Alanyaspor", "years": "2018-2021", "logo": "🟠"}, {"team": "Trabzonspor", "years": "2021-", "logo": "🔵"}], "nationality": "Yunanistan", "position": "Orta Saha", "age": 31, "current_team": "Trabzonspor", "difficulty": "medium"},
    {"name": "Cihan Çanak", "team_history": [{"team": "Trabzonspor", "years": "2023-", "logo": "🔵"}], "nationality": "Türkiye", "position": "Kanat", "age": 19, "current_team": "Trabzonspor", "difficulty": "medium"},
    {"name": "Edin Višća", "team_history": [{"team": "Başakşehir", "years": "2011-2021", "logo": "🟠"}, {"team": "Trabzonspor", "years": "2021-", "logo": "🔵"}], "nationality": "Bosna Hersek", "position": "Kanat", "age": 34, "current_team": "Trabzonspor", "difficulty": "medium"},
    {"name": "Uğurcan Çakır", "team_history": [{"team": "Trabzonspor", "years": "2017-", "logo": "🔵"}], "nationality": "Türkiye", "position": "Kaleci", "age": 28, "current_team": "Trabzonspor", "difficulty": "easy"},
    {"name": "Simon Falette", "team_history": [{"team": "Metz", "years": "2013-2017", "logo": "🟤"}, {"team": "Eintracht Frankfurt", "years": "2017-2019", "logo": "⚫"}, {"team": "Fenerbahçe", "years": "2019-2021", "logo": "🟡"}, {"team": "Trabzonspor", "years": "2021-", "logo": "🔵"}], "nationality": "Gine", "position": "Stoper", "age": 31, "current_team": "Trabzonspor", "difficulty": "medium"},
    {"name": "Paul Onuachu", "team_history": [{"team": "Midtjylland", "years": "2016-2019", "logo": "🔴"}, {"team": "Genk", "years": "2019-2023", "logo": "🔵"}, {"team": "Southampton", "years": "2023 (Kiralık)", "logo": "🔴"}, {"team": "Trabzonspor", "years": "2023-", "logo": "🔵"}], "nationality": "Nijerya", "position": "Forvet", "age": 30, "current_team": "Trabzonspor", "difficulty": "medium"},
    
    # ============ DİĞER TÜRK OYUNCULAR ============
    {"name": "Orkun Kökçü", "team_history": [{"team": "Feyenoord", "years": "2018-2023", "logo": "🔴"}, {"team": "Benfica", "years": "2023-", "logo": "🔴"}], "nationality": "Türkiye", "position": "Orta Saha", "age": 23, "current_team": "Benfica", "difficulty": "easy"},
    {"name": "Merih Demiral", "team_history": [{"team": "Sporting CP", "years": "2017-2018", "logo": "🟢"}, {"team": "Sassuolo", "years": "2018-2019", "logo": "🟢"}, {"team": "Juventus", "years": "2019-2021", "logo": "⚫"}, {"team": "Atalanta", "years": "2021-2024", "logo": "🔵"}, {"team": "Al-Ahli", "years": "2024-", "logo": "🟢"}], "nationality": "Türkiye", "position": "Stoper", "age": 26, "current_team": "Al-Ahli", "difficulty": "easy"},
    {"name": "Ferdi Kadıoğlu", "team_history": [{"team": "NEC Nijmegen", "years": "2018-2021", "logo": "🔴"}, {"team": "Fenerbahçe", "years": "2021-2024", "logo": "🟡"}, {"team": "Brighton", "years": "2024-", "logo": "🔵"}], "nationality": "Türkiye", "position": "Sol Bek", "age": 24, "current_team": "Brighton", "difficulty": "easy"},
    {"name": "Okay Yokuşlu", "team_history": [{"team": "Trabzonspor", "years": "2014-2018", "logo": "🔵"}, {"team": "Celta Vigo", "years": "2018-2022", "logo": "🔵"}, {"team": "West Brom", "years": "2021 (Kiralık)", "logo": "⚪"}, {"team": "Getafe", "years": "2022 (Kiralık)", "logo": "🔵"}, {"team": "West Brom", "years": "2022-", "logo": "⚪"}], "nationality": "Türkiye", "position": "Orta Saha", "age": 30, "current_team": "West Brom", "difficulty": "medium"},
    {"name": "Ozan Kabak", "team_history": [{"team": "Galatasaray", "years": "2017-2019", "logo": "🟡"}, {"team": "Stuttgart", "years": "2019-2020", "logo": "⚪"}, {"team": "Schalke 04", "years": "2020-2022", "logo": "🔵"}, {"team": "Liverpool", "years": "2021 (Kiralık)", "logo": "🔴"}, {"team": "Norwich City", "years": "2021-2022 (Kiralık)", "logo": "🟡"}, {"team": "Hoffenheim", "years": "2022-", "logo": "🔵"}], "nationality": "Türkiye", "position": "Stoper", "age": 24, "current_team": "Hoffenheim", "difficulty": "medium"},
    {"name": "Yunus Musah", "team_history": [{"team": "Arsenal", "years": "2012-2019", "logo": "🔴"}, {"team": "Valencia", "years": "2019-2023", "logo": "⚪"}, {"team": "AC Milan", "years": "2023-", "logo": "🔴"}], "nationality": "ABD", "position": "Orta Saha", "age": 21, "current_team": "AC Milan", "difficulty": "medium"},
    {"name": "Cenk Tosun", "team_history": [{"team": "Gaziantepspor", "years": "2009-2014", "logo": "🔴"}, {"team": "Beşiktaş", "years": "2014-2018", "logo": "⚫"}, {"team": "Everton", "years": "2018-2022", "logo": "🔵"}, {"team": "Crystal Palace", "years": "2020 (Kiralık)", "logo": "🔴"}, {"team": "Beşiktaş", "years": "2020-2021 (Kiralık)", "logo": "⚫"}, {"team": "Beşiktaş", "years": "2022-", "logo": "⚫"}], "nationality": "Türkiye", "position": "Forvet", "age": 33, "current_team": "Beşiktaş", "difficulty": "easy"},
]
